//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIPowerDownView.h"

@interface _SBInternalPowerDownView : SBUIPowerDownView
{
    _Bool _canAlterScreenBrightness;
    id <SBPowerDownAlertViewDelegate> _powerDownDelegate;
    _Bool _hiddenLockScreenForeground;
}

- (void).cxx_destruct;
- (void)_cancelButtonTapped;
- (void)_idleTimerFired;
- (void)_powerDownSliderDidBeginSlide;
- (void)_powerDownSliderDidCancelSlide;
- (void)_powerDownSliderDidCompleteSlide;
- (void)_powerDownSliderDidUpdateSlideWithValue:(double)arg1;
@property(nonatomic) _Bool canAlterScreenBrightness; // @synthesize canAlterScreenBrightness=_canAlterScreenBrightness;
@property(retain, nonatomic) id <SBPowerDownAlertViewDelegate> powerDownDelegate; // @synthesize powerDownDelegate=_powerDownDelegate;
- (void)resetScreenBrightness;

@end

