//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLockScreenBatteryChargingView.h"

@class SBLockScreenBatteryFillView, SBUILegibilityLabel, UIImageView, UIView, _UIBackdropView;

@interface _SBLockScreenDoubleBatteryChargingView : SBLockScreenBatteryChargingView
{
    UIView *_batteryContainerView;
    UIView *_internalBatteryContainerView;
    UIView *_externalBatteryContainerView;
    _UIBackdropView *_internalBatteryBlurView;
    _UIBackdropView *_externalBatteryBlurView;
    SBLockScreenBatteryFillView *_internalBatteryFillView;
    SBLockScreenBatteryFillView *_externalBatteryFillView;
    SBUILegibilityLabel *_internalChargePercentLabel;
    SBUILegibilityLabel *_externalChargePercentLabel;
    SBUILegibilityLabel *_internalChargingNameLabel;
    SBUILegibilityLabel *_externalChargingNameLabel;
    UIImageView *_internalChargingIndicator;
    UIImageView *_externalChargingIndicator;
}

- (void).cxx_destruct;
- (double)_batteryTopPadding;
- (id)_chargePercentFont;
- (double)_chargingBoltTopOffset;
- (double)_deviceChargeBaselineOffset;
- (double)_deviceNameBaselineOffset;
- (double)_spaceBetweenBatteryImages;
- (_Bool)batteryVisible;
- (double)desiredVisibilityDuration;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setBatteryVisible:(_Bool)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)setPrimaryBatteryText:(id)arg1 forBattery:(id)arg2;
- (void)setSecondaryBatteryText:(id)arg1 forBattery:(id)arg2;

@end

