//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController;

@interface _SBModalViewControllerStackTransition : NSObject
{
    UIViewController *_viewController;
    unsigned long long _operation;
    _Bool _animated;
    CDUnknownBlockType _completion;
}

+ (id)transitionForViewController:(id)arg1 operation:(unsigned long long)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void).cxx_destruct;
@property(nonatomic) _Bool animated; // @synthesize animated=_animated;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (id)description;
- (void)invokeCompletionIfNecessaryWithResult:(_Bool)arg1;
@property(nonatomic) unsigned long long operation; // @synthesize operation=_operation;
@property(retain, nonatomic) UIViewController *viewController; // @synthesize viewController=_viewController;

@end

