//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface _SBStatusBarAreaStyleAnimationContext : NSObject
{
    long long _statusBarAreaStyle;
    id _statusBarHiddenAnimationContext;
}

- (void).cxx_destruct;
@property(nonatomic) long long statusBarAreaStyle; // @synthesize statusBarAreaStyle=_statusBarAreaStyle;
@property(retain, nonatomic) id statusBarHiddenAnimationContext; // @synthesize statusBarHiddenAnimationContext=_statusBarHiddenAnimationContext;

@end

