//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSFastEnumeration.h"

@class NSMutableOrderedSet;

@interface SBAlertItemsObjectQueue : NSObject <NSFastEnumeration>
{
    NSMutableOrderedSet *_objects;
}

- (void).cxx_destruct;
- (void)appendObject:(id)arg1;
- (_Bool)containsObject:(id)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)dequeueAllObjects;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (_Bool)hasObject;
- (_Bool)hasObjectOfClass:(Class)arg1;
- (id)init;
@property(retain, nonatomic) NSMutableOrderedSet *objects; // @synthesize objects=_objects;
- (id)objectsOfClass:(Class)arg1;
- (void)prependObject:(id)arg1;
- (void)removeObject:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end

