//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BSDescriptionProviding.h"
#import "SBActivationSettings.h"
#import "SBApplicationHosting.h"
#import "SBButtonEventsHandler.h"
#import "SBDeactivationSettings.h"
#import "SBDisplay.h"
#import "SBFluidGestureDismissable.h"
#import "SBHomeGrabberDelegate.h"
#import "SBIdleTimerProviding.h"

@class FBDisplayLayoutElement, MTMaterialView, NSHashTable, NSMutableDictionary, NSString, SBActivationSettings, SBAlertManager, SBAlertView, SBAppStatusBarSettingsAssertion, SBDeactivationSettings, SBFluidDismissalState, SBHomeGrabberView, SBUIKeyboardHomeAffordanceAssertion, SBUIRemoteAlertMaterialDescriptor, UIScreen, UIStatusBar, UIView;

@interface SBAlert : UIViewController <SBFluidGestureDismissable, SBHomeGrabberDelegate, SBDisplay, SBApplicationHosting, SBActivationSettings, SBDeactivationSettings, SBButtonEventsHandler, SBIdleTimerProviding, BSDescriptionProviding>
{
    id <SBAlertDelegate> _alertDelegate;
    SBAlertView *_display;
    NSMutableDictionary *_dictionary;
    _Bool _isWallpaperTunnelActive;
    _Bool _backgroundStyleIsSet;
    long long _backgroundStyle;
    _Bool _isForcingBackgroundStyleUpdate;
    _Bool _suppressesBanners;
    _Bool _expectsFaceContact;
    _Bool _occluding;
    SBUIRemoteAlertMaterialDescriptor *_backgroundDescriptor;
    double _backgroundWeighting;
    SBFluidDismissalState *_fluidDismissalState;
    _Bool _keyboardPresented;
    _Bool _keyboardStashed;
    SBUIKeyboardHomeAffordanceAssertion *_keyboardHomeAffordanceAssertion;
    UIView *_dimmingView;
    MTMaterialView *_backgroundView;
    UIView *_contentView;
    SBHomeGrabberView *_grabberView;
    SBActivationSettings *_activationSettings;
    SBDeactivationSettings *_deactivationSettings;
    int _orientationChangedEventsEnabled;
    _Bool _requestedDismissal;
    UIScreen *_targetScreen;
    FBDisplayLayoutElement *_displayLayoutElement;
    NSHashTable *_observers;
    id <SBIdleTimerCoordinating> _idleTimerCoordinator;
    SBAppStatusBarSettingsAssertion *_hideStatusBarAssertion;
    UIStatusBar *_fakeStatusBar;
    _Bool _targetFakeStatusBarVisibility;
    _Bool _ownsHomeGesture;
    _Bool _alwaysDrawsHomeAffordance;
    id <SBIdleTimer> _idleTimer;
    SBAlertManager *_alertManager;
}

+ (void)registerForAlerts;
+ (void)test;
- (void).cxx_destruct;
- (void)_deactivateLayoutElement;
- (id)_displayLayoutElementIdentifier;
@property(retain, nonatomic, getter=_idleTimer, setter=_setIdleTimer:) id <SBIdleTimer> idleTimer; // @synthesize idleTimer=_idleTimer;
@property(nonatomic, getter=_idleTimerCoordinator, setter=_setIdleTimerCoordinator:) __weak id <SBIdleTimerCoordinating> idleTimerCoordinator; // @synthesize idleTimerCoordinator=_idleTimerCoordinator;
- (id)_impersonatesApplicationWithBundleID;
- (_Bool)_isActiveAlert;
@property(nonatomic, getter=_isOccluding, setter=_setOccluding:) _Bool _occluding;
- (void)_keyboardWillHideNotification:(id)arg1;
- (void)_keyboardWillShowNotification:(id)arg1;
- (_Bool)_needsDimmingView;
- (void)_removeFromImpersonatedAppIfNecessary;
@property(nonatomic, getter=_requestedDismissal, setter=_setRequestedDismissal:) _Bool requestedDismissal; // @synthesize requestedDismissal=_requestedDismissal;
- (id)_screen;
- (void)_setTargetScreen:(id)arg1;
- (_Bool)_shouldDismissSwitcherOnActivation;
- (_Bool)_shouldDrawHomeAffordance;
- (void)_updateBackgroundView;
- (void)_updateContentLayout;
- (void)_updateDimmingView;
- (void)_updateHomeAffordance;
- (void)_updateHomeAffordanceVisibility;
- (void)_updateKeyboardForHomeGesture;
- (void)_updateStatusBarForFluidDismissalAnimated:(_Bool)arg1;
- (void)activate;
@property(readonly, nonatomic) _Bool activatedForSiri;
- (void)addObserver:(id)arg1;
- (double)additionalEdgeSpacingForHomeGrabberView:(id)arg1;
- (id)alertDelegate;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
@property(retain, nonatomic) SBAlertManager *alertManager; // @synthesize alertManager=_alertManager;
- (void)alertViewIsReadyToDismiss:(id)arg1;
- (_Bool)allowsEventOnlySuspension;
- (_Bool)allowsStackingOfAlert:(id)arg1;
@property(nonatomic) _Bool alwaysDrawsHomeAffordance; // @synthesize alwaysDrawsHomeAffordance=_alwaysDrawsHomeAffordance;
- (void)animateDeactivation;
- (void)applyActivationSettings:(id)arg1;
- (void)applyDeactivationSettings:(id)arg1;
- (double)autoDimTime;
- (double)autoLockTime;
@property(retain, nonatomic) SBUIRemoteAlertMaterialDescriptor *backgroundMaterialDescriptor;
@property(nonatomic) double backgroundWeighting;
- (_Bool)boolForActivationSetting:(unsigned int)arg1;
- (_Bool)boolForDeactivationSetting:(unsigned int)arg1;
- (_Bool)canHostAnApp;
- (void)cleanupFromFakeStatusBarAnimation;
- (void)clearActivationSettings;
- (void)clearDeactivationSettings;
- (void)clearDisplay;
- (id)contentView;
- (id)coordinatorRequestedIdleTimerDescriptor:(id)arg1;
- (id)copyActivationSettings;
- (id)copyDeactivationSettings;
- (_Bool)currentlyAnimatingDeactivation;
- (long long)customBackgroundStyle;
- (void)deactivate;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)dismissAlert;
- (id)display;
- (void)displayDidDisappear;
- (void)displayWillAppear;
- (void)displayWillDisappear;
- (id)effectiveStatusBarStyleRequest;
- (id)effectiveViewController;
@property(nonatomic) _Bool expectsFaceContact; // @synthesize expectsFaceContact=_expectsFaceContact;
- (float)finalAlpha;
- (long long)flagForActivationSetting:(unsigned int)arg1;
- (long long)flagForDeactivationSetting:(unsigned int)arg1;
@property(retain, nonatomic) SBFluidDismissalState *fluidDismissalState;
- (void)handleAutoLock;
- (_Bool)handleHeadsetButtonPress:(_Bool)arg1;
- (_Bool)handleHomeButtonDoublePress;
- (_Bool)handleHomeButtonLongPress;
- (_Bool)handleHomeButtonPress;
- (_Bool)handleLockButtonPress;
- (_Bool)handleVolumeDownButtonPress;
- (_Bool)handleVolumeUpButtonPress;
- (_Bool)hasTranslucentBackground;
- (id)hostedApp;
- (void)hostedAppWillRotateToInterfaceOrientation:(long long)arg1;
- (id)init;
@property(readonly, nonatomic, getter=isFakeStatusBarVisible) _Bool fakeStatusBarVisible;
- (_Bool)isHostingAnApp;
- (_Bool)isRemote;
- (_Bool)isWallpaperTunnelActive;
- (id)legibilitySettings;
- (void)loadView;
- (double)longPressDurationForHomeButton;
- (_Bool)matchesAnyInCallService;
- (_Bool)matchesInCallUIService;
- (_Bool)matchesRemoteAlertService:(id)arg1 options:(id)arg2;
- (id)objectForActivationSetting:(unsigned int)arg1;
- (id)objectForDeactivationSetting:(unsigned int)arg1;
- (id)objectForKey:(id)arg1;
- (_Bool)orientationChangedEventsEnabled;
@property(nonatomic) _Bool ownsHomeGesture; // @synthesize ownsHomeGesture=_ownsHomeGesture;
- (void)performFakeStatusBarAnimation;
- (long long)preferredInterfaceOrientationForPresentation;
- (long long)preferredStatusBarStyle;
- (void)prepareToAnimateFakeStatusBarFromStartingVisibility:(_Bool)arg1 toEndVisibility:(_Bool)arg2;
- (void)relinquishHiddenAssertionForHomeGrabber:(id)arg1;
- (void)removeBackgroundStyleWithAnimationFactory:(id)arg1;
- (void)removeFromView;
- (void)removeObjectForKey:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)setAlertDelegate:(id)arg1;
- (void)setBackgroundStyle:(long long)arg1 withAnimationFactory:(id)arg2;
- (void)setBackgroundStyle:(long long)arg1 withAnimationFactory:(id)arg2 force:(_Bool)arg3;
- (void)setBackgroundWeighting:(double)arg1 animationSettings:(id)arg2;
- (void)setDisplay:(id)arg1;
- (void)setFlag:(long long)arg1 forActivationSetting:(unsigned int)arg2;
- (void)setFlag:(long long)arg1 forDeactivationSetting:(unsigned int)arg2;
- (void)setHidesSpringBoardStatusBarForTransition:(_Bool)arg1 reason:(id)arg2;
- (void)setNeedsUpdateOfHomeIndicatorAutoHidden;
- (void)setNeedsUpdateOfScreenEdgesDeferringSystemGestures;
- (void)setObject:(id)arg1 forActivationSetting:(unsigned int)arg2;
- (void)setObject:(id)arg1 forDeactivationSetting:(unsigned int)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setOrientationChangedEventsEnabled:(_Bool)arg1;
@property(nonatomic) _Bool suppressesBanners;
- (void)setWallpaperTunnelActive:(_Bool)arg1;
- (_Bool)shouldAllowAutoHideForHomeGrabberView:(id)arg1;
- (_Bool)shouldAllowThinStyleForHomeGrabberView:(id)arg1;
- (_Bool)shouldAutorotate;
- (_Bool)shouldDisableAutoLockWarn;
@property(readonly, nonatomic) _Bool shouldDismissOnUILock;
@property(readonly, nonatomic) _Bool shouldDismissWithGoToHomeShortcut;
- (_Bool)shouldPendAlertItemsWhileActive;
- (int)statusBarStyleOverridesToCancel;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (unsigned long long)supportedInterfaceOrientations;
@property(readonly, nonatomic) _Bool suppressesControlCenter;
@property(readonly, nonatomic) _Bool suppressesCoverSheetGesture;
@property(readonly, nonatomic) _Bool suppressesSiri;
@property(readonly, nonatomic) long long swipeDismissalStyle;
- (void)takeHiddenAssertionForHomeGrabber:(id)arg1;
- (_Bool)undimsDisplay;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (_Bool)wantsCustomBackgroundStyle;
- (_Bool)wantsCustomBackgroundStyleForAllWallpaperVariants;
- (_Bool)wantsFullScreenLayout;
- (_Bool)wantsHomeButtonPress;
- (void)wantsHomeButtonPressDidChange;
- (_Bool)wantsTimeInStatusBar;
@property(readonly, nonatomic) long long whitePointAdaptivityStyle;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

