//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBUIActiveOrientationObserver.h"

@class NSArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString, SBAppSwitcherSettings, SBApplicationController, SBIconController, SBOrientationLockManager;

@interface SBAppSwitcherSnapshotImageCache : NSObject <SBUIActiveOrientationObserver>
{
    NSObject<OS_dispatch_queue> *_snapshotQueue;
    NSObject<OS_dispatch_queue> *_controlQueue;
    NSMutableDictionary *_cachedSnapshots;
    NSMutableDictionary *_cacheEntryUpdateObservers;
    NSMutableDictionary *_snapshotRequestsCurrentlyBeingLoaded;
    unsigned long long _snapshotRequestSequenceID;
    NSArray *_appLayoutsInPriorityOrder;
    NSArray *_defaultAppLayouts;
    long long _lastKnownInterfaceOrientation;
    SBAppSwitcherSettings *_settings;
    struct _NSRange _lastVisibleRange;
    NSArray *_lastHighPriorityAppLayouts;
    NSArray *_lastAllAppLayouts;
    _Bool _lastPriorityBiasedForward;
    _Bool _shouldPurgeNilEntries;
    SBIconController *_iconController;
    SBApplicationController *_applicationController;
    SBOrientationLockManager *_orientationLockManager;
    _Bool _cachingEnabled;
    id <SBAppSwitcherSnapshotImageCacheDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_addCacheEntryForImage:(id)arg1 fromRequest:(id)arg2;
- (void)_addObserver:(id)arg1 forDisplayItem:(id)arg2;
- (id)_allAppLayouts;
- (id)_appLayoutsInPriorityOrder;
- (unsigned long long)_appLayoutsToCacheCount;
- (void)_asynchronouslyLoadSnapshotFromRequest:(id)arg1;
- (_Bool)_biasForwardLoading;
- (id)_cachableAppLayouts;
- (id)_cachableAppLayoutsForTesting;
- (void)_cacheSnapshotForRequest:(id)arg1 withDisplayItem:(id)arg2 inAppLayout:(id)arg3;
- (struct CGImage *)_createDecodedImageIfPossible:(struct CGImage *)arg1;
- (void)_createDownscaledVariantForRequest:(id)arg1 snapshot:(id)arg2 displayItem:(id)arg3 sceneHandle:(id)arg4 application:(id)arg5;
- (id)_createSnapshotRequestWithDisplayItem:(id)arg1 inAppLayout:(id)arg2;
- (id)_defaultAppLayouts;
- (void)_enqueueNextSnapshotRequestIfNecessary;
- (id)_highPriorityAppLayouts;
- (id)_initWithDelegate:(id)arg1 iconController:(id)arg2 applicationController:(id)arg3 orientationLockManager:(id)arg4 settings:(id)arg5;
- (_Bool)_isLoadingForDefaultDisplayItem:(id)arg1;
- (_Bool)_isValidAppLayout:(id)arg1 withSnapshot:(id)arg2 givenCachableAppLayouts:(id)arg3;
- (_Bool)_isValidSnapshotRequest:(id)arg1;
- (_Bool)_keepGoingForRequest:(id)arg1;
- (void)_loadSnapshotForRequest:(id)arg1 withDisplayItem:(id)arg2 inAppLayout:(id)arg3;
- (long long)_orientationForAppLayout:(id)arg1;
- (void)_purgeAllSnapshotRequests;
- (void)_purgeAllSnapshots;
- (void)_purgeLowPrioritySnapshotRequests;
- (void)_purgeLowPrioritySnapshots;
- (void)_purgeSnapshotRequest:(id)arg1;
- (void)_purgeSnapshotRequestsForDisplayItem:(id)arg1;
- (void)_purgeSnapshotsForDisplayItem:(id)arg1;
- (id)_representedApplicationSceneEntityForDisplayItem:(id)arg1;
- (void)_resetLastCachedValues;
- (double)_scaleForDownscaledSnapshots;
- (void)_setShouldPurgeNilEntry:(_Bool)arg1;
- (void)_snapshotChanged:(id)arg1;
- (void)_snapshotImage:(id)arg1 finishedLoadingForRequest:(id)arg2;
- (id)_uiImageForCGImage:(struct CGImage *)arg1 forSnapshotRequest:(id)arg2;
- (void)_updateAppLayoutPriorityList;
- (void)_updateCacheForDisplayItem:(id)arg1;
- (void)_updateObserversForDisplayItem:(id)arg1 withCacheEntry:(id)arg2;
- (struct _NSRange)_visibleAppLayoutRange;
- (void)activeInterfaceOrientationDidChangeToOrientation:(long long)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(long long)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(long long)arg1;
- (void)addSnapshotUpdateObserver:(id)arg1 forDisplayItem:(id)arg2 inAppLayout:(id)arg3;
@property(nonatomic) _Bool cachingEnabled; // @synthesize cachingEnabled=_cachingEnabled;
@property(nonatomic) __weak id <SBAppSwitcherSnapshotImageCacheDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
- (id)init;
- (id)initWithDelegate:(id)arg1;
- (void)removeSnapshotObserver:(id)arg1;
- (void)updateCache;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

