//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBApplicationPlaceholder.h"

@class NSString;

@interface SBApplicationPlaceholderProxy : FBApplicationPlaceholder
{
    NSString *_customIconClassName;
}

- (void).cxx_destruct;
- (void)_reloadFromProxy:(id)arg1;
@property(copy) NSString *customIconClassName; // @synthesize customIconClassName=_customIconClassName;
@property(readonly, nonatomic) Class iconClass;

@end

