//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLeafIcon.h"

@class NSString, SBApplication, UIImage;

@interface SBApplicationIcon : SBLeafIcon
{
    SBApplication *_application;
    UIImage *_cachedSquareHomeScreenContentsImage;
    NSString *_masqueradeIdentifier;
}

+ (_Bool)canGenerateIconsInBackground;
- (void).cxx_destruct;
- (id)__loadIconImageForDataSource:(id)arg1 format:(int)arg2;
- (id)__loadUnmaskedIconImageForFormat:(int)arg1 bundleIdentifier:(id)arg2;
- (CDUnknownBlockType)_blockForGeneratingIconImageInBackgroundWithFormat:(int)arg1 bundleIdentifier:(id)arg2 complete:(CDUnknownBlockType)arg3;
- (void)_noteActiveDataSourceDidChangeAndReloadIcon:(_Bool)arg1;
- (id)application;
- (void)asynchronouslyRequestIconImageForFormat:(int)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)automationID;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)folderFallbackTitle;
- (id)folderTitleOptions;
- (id)generateIconImage:(int)arg1;
- (id)getUnmaskedIconImage:(int)arg1;
- (id)initWithApplication:(id)arg1;
- (_Bool)isApplicationIcon;
- (id)masqueradeIdentifier;
- (void)possibleUserTapBeganWithAbsoluteTime:(unsigned long long)arg1 andContinuousTime:(unsigned long long)arg2;
- (void)purgeCachedImages;
- (void)setBadge:(id)arg1;
- (id)tags;

@end

