//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAWDMetricData.h"

@class NSString;

@interface SBAppBrightnessMetricData : SBAWDMetricData
{
    NSString *_appBundleID;
    unsigned long long _brightness;
    unsigned long long _duration;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *appBundleID; // @synthesize appBundleID=_appBundleID;
@property(nonatomic) unsigned long long brightness; // @synthesize brightness=_brightness;
@property(nonatomic) unsigned long long duration; // @synthesize duration=_duration;

@end

