//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBAlertObserver.h"
#import "SBAssistantObserver.h"
#import "SBBannerContainerViewControllerDelegate.h"
#import "SBBulletinBusyClient.h"
#import "SBBulletinWindowClient.h"
#import "SBUIBannerTargetImplementation.h"

@class NSHashTable, NSMapTable, NSMutableArray, NSString, SBAlert, SBBannerContainerViewController;

@interface SBBannerController : NSObject <SBUIBannerTargetImplementation, SBAssistantObserver, SBAlertObserver, SBBannerContainerViewControllerDelegate, SBBulletinWindowClient, SBBulletinBusyClient>
{
    NSHashTable *_sources;
    NSMutableArray *_pendingBannerContextsNeedingRepop;
    SBAlert *_topAlert;
    SBBannerContainerViewController *_bannerViewController;
    _Bool _soundIsPlaying;
    _Bool _dismissalOverdue;
    _Bool _replaceDelayIsActive;
    _Bool _showingStickyDurationBanner;
    _Bool _suppressingBanners;
    _Bool _enableDelayActive;
    _Bool _assistantIsFullyVisible;
    _Bool _locked;
    unsigned long long _transitionCount;
    long long _overdueDismissReason;
    CDUnknownBlockType _overdueCompletionBlock;
    _Bool _dismissingBannerForAssistantReveal;
    _Bool _dismissingBannerForAssistantDismiss;
    CDUnknownBlockType _assistantRevealCompletionBlock;
    CDUnknownBlockType _assistantDismissCompletionBlock;
    NSMapTable *_bannerContextToViewControllerCache;
}

+ (id)_sharedInstanceCreateIfNecessary:(_Bool)arg1;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
- (void).cxx_destruct;
- (id)_bannerContainerView;
- (id)_bannerContext;
- (id)_bannerItem;
- (_Bool)_canDequeueIgnoringStickyBanner:(_Bool)arg1;
- (void)_cancelBannerDismissTimers;
- (void)_dequeueAfterDelayIfPossible;
- (_Bool)_dequeueBannerIfPossible;
- (_Bool)_dequeueBannerIfPossibleIgnoringStickyBanner:(_Bool)arg1 existingDismissReason:(long long)arg2;
- (id)_dequeueNextBannerContext;
- (void)_dismissIntervalElapsed;
- (void)_dismissOverdueOrDequeueIfPossible;
- (void)_fireCompletionBlockForBannerAnimationForAssistantDismissIfNecessary;
- (void)_fireCompletionBlockForBannerAnimationForAssistantRevealIfNecessary;
- (_Bool)_isItemShowable:(id)arg1 fromSource:(id)arg2;
- (void)_lockStateChanged:(id)arg1;
- (id)_newBannerContentViewController;
- (id)_pendingBannerContextForSourceNeedingRepop:(id)arg1;
- (void)_performHideTransitionWithContext:(id)arg1 animated:(_Bool)arg2 reason:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_performReplaceTransitionWithContext:(id)arg1 reason:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_performRevealTransitionWithContext:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_performTransition:(long long)arg1 withAnimation:(_Bool)arg2 context:(id)arg3 reason:(long long)arg4 completion:(CDUnknownBlockType)arg5;
- (void)_presentBannerForContext:(id)arg1 reason:(long long)arg2;
- (void)_removePendingContextsForSourceNeedingRepop:(id)arg1;
- (void)_replaceIntervalElapsed;
- (void)_setBannerSticky:(_Bool)arg1;
- (void)_setBannerViewControllerForContext:(id)arg1;
- (void)_setOverdueCompletionBlock:(CDUnknownBlockType)arg1;
- (void)_setupBannerDismissTimers;
- (_Bool)_shouldPendStickyBannerContext:(id)arg1 withReason:(long long)arg2;
- (void)_soundDidFinishPlayingForBannerContext:(id)arg1;
- (void)_stopCurrentSound;
- (void)_tryToDismissWithAnimation:(_Bool)arg1 reason:(long long)arg2 forceEvenIfBusy:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_updateBannerSuppressionState;
- (void)_updateBannerSuppressionStateAndDequeueIfPossible:(_Bool)arg1 withDelay:(_Bool)arg2;
- (id)_viewControllerForPresentation;
- (void)alertBannerSuppressionChanged:(id)arg1;
- (void)assistant:(id)arg1 viewDidAppear:(long long)arg2;
- (void)assistant:(id)arg1 viewDidDisappear:(long long)arg2;
- (void)assistant:(id)arg1 viewWillAppear:(long long)arg2;
- (void)assistant:(id)arg1 viewWillDisappear:(long long)arg2;
@property(readonly, nonatomic) void *bannerTargetIdentifier;
@property(readonly, nonatomic) long long bannerTargetIdiom;
- (void)bannerViewControllerDidDismissAction:(id)arg1;
- (void)bannerViewControllerDidSelectAction:(id)arg1;
- (void)bulletinWindowStoppedBeingBusy;
- (void)cacheBannerForContext:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)currentBannerContextForSource:(id)arg1;
- (void)dealloc;
- (void)dismissBannerWithAnimation:(_Bool)arg1 reason:(long long)arg2;
- (void)dismissBannerWithAnimation:(_Bool)arg1 reason:(long long)arg2 forceEvenIfBusy:(_Bool)arg3;
- (void)dismissBannerWithAnimation:(_Bool)arg1 reason:(long long)arg2 forceEvenIfBusy:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)dismissCurrentBannerContextForSource:(id)arg1;
- (id)init;
- (_Bool)isShowingBanner;
- (_Bool)isShowingModalBanner;
- (_Bool)isShowingModalBannerWithKeyboard;
- (_Bool)isTransitioningBanner;
- (void)modallyPresentBannerWithContext:(id)arg1;
- (void)registerSource:(id)arg1;
- (void)removeCachedBannerForContext:(id)arg1;
@property(retain, nonatomic) SBAlert *topAlert; // @synthesize topAlert=_topAlert;
- (void)signalSource:(id)arg1;
- (void)unregisterSource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

