//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTPlatterView.h"

@class SBBannerContextView, SBUIBannerContext;

@interface SBBannerContainerView : MTPlatterView
{
    SBBannerContextView *_bannerContextView;
}

- (void).cxx_destruct;
@property(readonly, retain, nonatomic) SBUIBannerContext *bannerContext;
@property(retain, nonatomic) SBBannerContextView *bannerContextView; // @synthesize bannerContextView=_bannerContextView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)noteDidAppear;
- (void)noteDidDismissWithReason:(int)arg1;
- (void)noteWillAppear;
- (void)noteWillDismissWithReason:(int)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

