//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIFetchContentInBackgroundAction;

@interface SBBackgroundFetchExternalRequest : NSObject
{
    int _sequenceNumber;
    UIFetchContentInBackgroundAction *_action;
    NSString *_bundleID;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIFetchContentInBackgroundAction *action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (void)execute;
- (id)initForBundleID:(id)arg1;
@property(nonatomic) int sequenceNumber; // @synthesize sequenceNumber=_sequenceNumber;

@end

