//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SBBaseStatusBarChangeAssertion : NSObject
{
    NSString *_reason;
}

- (void).cxx_destruct;
- (id)_initWithReason:(id)arg1;
- (id)description;
- (id)init;
- (void)invalidate;
@property(readonly, copy, nonatomic) NSString *reason; // @synthesize reason=_reason;

@end

