//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBTestRecipe.h"

@class FBWorkspaceEventQueueLock, NSString, NSTimer;

@interface SBBlockWorkspaceQueueTestRecipe : NSObject <SBTestRecipe>
{
    NSTimer *_blockTimer;
    FBWorkspaceEventQueueLock *_queueLock;
}

+ (id)title;
- (void).cxx_destruct;
@property(retain, nonatomic) NSTimer *blockTimer; // @synthesize blockTimer=_blockTimer;
- (void)blockTimerDidFire:(id)arg1;
- (void)handleVolumeDecrease;
- (void)handleVolumeIncrease;
@property(retain, nonatomic) FBWorkspaceEventQueueLock *queueLock; // @synthesize queueLock=_queueLock;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

