//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBBrightnessController : NSObject
{
    _Bool _debounce;
    struct BKSDisplayBrightnessTransaction *_brightnessDownTransaction;
    struct BKSDisplayBrightnessTransaction *_brightnessUpTransaction;
}

+ (id)sharedBrightnessController;
- (float)_calcButtonRepeatDelay;
- (void)_setBrightnessLevel:(float)arg1 showHUD:(_Bool)arg2;
- (void)adjustBacklightLevel:(_Bool)arg1;
- (void)cancelBrightnessEvent;
- (void)decreaseBrightnessAndRepeat;
- (void)handleBrightnessEvent:(struct __IOHIDEvent *)arg1;
- (void)increaseBrightnessAndRepeat;
- (void)setBrightnessLevel:(float)arg1;

@end

