//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBDateTimeOverrideObserver.h"

@class NSString, SBDateTimeController;

@interface SBCalendarIconImageProvider : NSObject <SBDateTimeOverrideObserver>
{
    id <SBCalendarIconImageProviderDelegate> _delegate;
    SBDateTimeController *_dateTimeController;
}

- (void).cxx_destruct;
- (void)_startListeningForSignificantTimeChanges;
- (void)_stopListeningForSignificantTimeChanges;
- (void)controller:(id)arg1 didChangeOverrideDateFromDate:(id)arg2;
@property(readonly, nonatomic) SBDateTimeController *dateTimeController; // @synthesize dateTimeController=_dateTimeController;
- (void)dealloc;
@property(nonatomic) __weak id <SBCalendarIconImageProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (id)iconImageForFormat:(int)arg1 baseImageProvider:(CDUnknownBlockType)arg2;
- (id)init;
- (id)initWithDateTimeController:(id)arg1;
- (void)localeChanged;
- (void)reloadIconImage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

