//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLiveIconImageView.h"

#import "SBDateTimeOverrideObserver.h"

@class CALayer, NSString;

@interface SBClockApplicationIconImageView : SBLiveIconImageView <SBDateTimeOverrideObserver>
{
    CALayer *_seconds;
    CALayer *_minutes;
    CALayer *_hours;
    CALayer *_blackDot;
    CALayer *_redDot;
    NSString *_currentNumberingSystem;
}

+ (void)_handleTimeChange:(id)arg1;
+ (void)_iconEditingStateChanged:(id)arg1;
+ (void)_timerFired:(id)arg1;
+ (id)generateProcessedMappedIconImageWithName:(id)arg1 iconOptions:(int)arg2;
+ (void)initialize;
+ (id)systemNumberingSystem;
- (void).cxx_destruct;
- (id)_generateSquareContentsImage;
- (void)_setAnimating:(_Bool)arg1;
- (void)_timerFiredWithComponents:(id)arg1 flags:(unsigned long long)arg2;
- (void)_updateUnanimatedWithComponents:(id)arg1;
- (id)backgroundImageName;
- (id)contentsImage;
- (void)controller:(id)arg1 didChangeOverrideDateFromDate:(id)arg2;
@property(copy, nonatomic) NSString *currentNumberingSystem; // @synthesize currentNumberingSystem=_currentNumberingSystem;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isAnimationAllowed;
- (void)layoutSubviews;
- (void)localeDidChange:(id)arg1;
- (void)setIcon:(id)arg1 location:(long long)arg2 animated:(_Bool)arg3;
- (void)updateAnimatingState;
- (void)updateUnanimated;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

