//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BBRemoteDataProvider.h"

@class BBDataProviderProxy, NSMutableDictionary, NSString;

@interface SBClockDataProvider : NSObject <BBRemoteDataProvider>
{
    BBDataProviderProxy *_dataProviderProxy;
    NSMutableDictionary *_snoozedAlarmRequests;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)_actionWithIdentifier:(id)arg1 title:(id)arg2;
- (id)_alarmIDFromNotificationRequest:(id)arg1;
- (id)_bulletinRequestForAlarmNotification:(id)arg1;
- (id)_bulletinRequestForAlarmSnoozeNotificationRequest:(id)arg1;
- (id)_bulletinRequestForBedtimeNotification:(id)arg1;
- (id)_bulletinRequestForTimerNotification:(id)arg1;
- (id)_bulletinSoundWithAlertType:(long long)arg1 notificationSound:(id)arg2;
- (void)_deviceFirstUnlocked;
- (void)_handleBulletinAlarmDismissResponse:(id)arg1;
- (void)_handleBulletinAlarmSnoozeResponse:(id)arg1;
- (void)_handleBulletinBedtimeDismissResponse:(id)arg1;
- (void)_handleBulletinBedtimeSnoozeResponse:(id)arg1;
- (void)_handleBulletinBedtimeStopResponse:(id)arg1;
- (void)_handleBulletinSnoozeStopResponse:(id)arg1;
- (void)_handleBulletinTimerRepeatResponse:(id)arg1;
- (void)_handleClockNotificationUpdate:(id)arg1;
- (void)_handleNotificationDidDeliver:(id)arg1;
- (void)_interruptAudioAndLockDeviceForNotification:(id)arg1;
- (_Bool)_isAlarmNotification:(id)arg1;
- (_Bool)_isAlarmNotificationRequest:(id)arg1;
- (_Bool)_isBedtimeNotification:(id)arg1;
- (_Bool)_isBedtimeNotificationRequest:(id)arg1;
- (_Bool)_isTimerNotification:(id)arg1;
- (_Bool)_isWakeNotification:(id)arg1;
- (_Bool)_isWakeNotificationRequest:(id)arg1;
- (id)_notificationRequestFromActionResponse:(id)arg1;
- (id)_notificationRequestFromData:(id)arg1;
- (void)_publishBulletinForNotification:(id)arg1;
- (id)_recordIDFromNotification:(id)arg1;
- (id)_recordIDFromNotificationRequest:(id)arg1;
- (void)_removeSnoozeBulletinForResponse:(id)arg1;
- (void)_saveTimeInBedSamples;
- (void)_scheduledClockPendingNotificationRequestsDidChange:(id)arg1;
- (id)_timerIDFromNotificationRequest:(id)arg1;
- (id)_vibrationPatternForVibrationName:(id)arg1;
- (id)bulletinsWithRequestParameters:(id)arg1 lastCleared:(id)arg2;
- (void)dealloc;
- (id)defaultSectionInfo;
- (void)handleBulletinActionResponse:(id)arg1;
- (id)init;
- (id)sectionIdentifier;
- (id)sectionParameters;
- (id)sortDescriptors;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

