//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSCountedSet, NSMutableDictionary;

@interface SBCountedMap : NSObject
{
    NSCountedSet *_countedKeys;
    NSMutableDictionary *_map;
}

- (void).cxx_destruct;
- (void)checkinValue:(id)arg1;
- (void)checkinValues:(id)arg1;
- (id)checkoutValueForKey:(id)arg1 creationBlock:(CDUnknownBlockType)arg2;
- (_Bool)containsValue:(id)arg1;
- (id)init;

@end

