//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "NSCopying.h"
#import "SBDashBoardAppearanceProviding.h"

@class NSMutableSet, NSSet, NSString, SBDashBoardLayoutStrategy, UIColor, _UILegibilitySettings;

@interface SBDashBoardAppearance : NSObject <BSDescriptionProviding, SBDashBoardAppearanceProviding, NSCopying>
{
    NSMutableSet *_components;
    _Bool _transitional;
    SBDashBoardLayoutStrategy *_layoutStrategy;
    NSString *_identifier;
    long long _backgroundStyle;
    _UILegibilitySettings *_legibilitySettings;
    UIColor *_backgroundColor;
}

+ (id)appearanceForProvider:(id)arg1;
+ (id)appearanceWithIdentifier:(id)arg1;
- (void).cxx_destruct;
- (void)addComponent:(id)arg1;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) long long backgroundStyle; // @synthesize backgroundStyle=_backgroundStyle;
- (id)componentForType:(long long)arg1 identifier:(id)arg2;
- (id)componentForType:(long long)arg1 property:(unsigned long long)arg2;
@property(copy, nonatomic) NSSet *components; // @synthesize components=_components;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (long long)flagForComponentType:(long long)arg1;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithIdentifier:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToAppearance:(id)arg1;
@property(nonatomic, getter=isTransitional) _Bool transitional; // @synthesize transitional=_transitional;
@property(retain, nonatomic) SBDashBoardLayoutStrategy *layoutStrategy; // @synthesize layoutStrategy=_layoutStrategy;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
- (void)removeAllComponentsWithIdentifier:(id)arg1;
- (void)removeComponent:(id)arg1;
- (void)reset;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (void)unionAppearance:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

