//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "SBDashBoardPresentationProviding.h"
#import "UICoordinateSpace.h"

@class NSArray, NSMutableArray, NSString;

@interface SBDashBoardPresentation : NSObject <SBDashBoardPresentationProviding, UICoordinateSpace, NSCopying>
{
    NSMutableArray *_regions;
    id <UICoordinateSpace> _coordinateSpace;
    NSString *_identifier;
}

+ (id)presentation;
+ (id)presentationForProvider:(id)arg1;
+ (id)presentationWithCoordinateSpace:(id)arg1;
- (void).cxx_destruct;
- (void)addRegion:(id)arg1;
- (void)addRegions:(id)arg1;
@property(readonly, nonatomic) struct CGRect bounds;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 fromCoordinateSpace:(id)arg2;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 toCoordinateSpace:(id)arg2;
- (struct CGRect)convertRect:(struct CGRect)arg1 fromCoordinateSpace:(id)arg2;
- (struct CGRect)convertRect:(struct CGRect)arg1 toCoordinateSpace:(id)arg2;
@property(nonatomic) __weak id <UICoordinateSpace> coordinateSpace; // @synthesize coordinateSpace=_coordinateSpace;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)firstRegionIntersectingCoordinateSpace:(id)arg1;
- (id)firstRegionIntersectingCoordinateSpace:(id)arg1 excludingRegionsWithRole:(long long)arg2;
@property(readonly) unsigned long long hash;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)init;
- (_Bool)intersectsCoordinateSpace:(id)arg1;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) __weak id <UICoordinateSpace> presentationCoordinateSpace;
- (id)presentationForRole:(long long)arg1;
@property(readonly, copy, nonatomic) NSArray *presentationRegions;
@property(readonly, copy, nonatomic) NSArray *regions; // @synthesize regions=_regions;
- (id)regionsIntersectingCoordinateSpace:(id)arg1;
- (void)reset;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (struct UIEdgeInsets)suggestedInsetsForPreferredContentFrame:(struct CGRect)arg1;
- (void)unionPresentation:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

