//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBDashBoardDateViewScrolling.h"
#import "SBDashBoardStatusBarBackgroundIntersecting.h"
#import "SPUISearchViewControllerDelegate.h"
#import "WGWidgetGroupViewControllerDelegate.h"

@class NSSet, NSString, SBDashBoardComponent, SBDashBoardLayoutStrategy, SBDashBoardPageViewController, SBDashBoardTodayPageView, SBViewControllerTransitionContext, UIView, WGWidgetGroupViewController;

@interface SBDashBoardTodayViewController : SBDashBoardViewControllerBase <WGWidgetGroupViewControllerDelegate, SPUISearchViewControllerDelegate, SBDashBoardStatusBarBackgroundIntersecting, SBDashBoardDateViewScrolling>
{
    _Bool _runningOnPad;
    SBDashBoardComponent *_dateViewComponent;
    SBDashBoardComponent *_statusBarBackgroundComponent;
    SBDashBoardComponent *_proudLockComponent;
    SBDashBoardComponent *_homeAffordanceComponent;
    SBDashBoardComponent *_controlCenterGrabberComponent;
    NSSet *_contentViews;
    WGWidgetGroupViewController *_todayViewController;
    UIView *_fakeCanvasView;
    _Bool _pullToSearchPossible;
    _Bool _pullToSearchRecognizing;
    _Bool transitionedToSearchInteractively;
    _Bool _scrollViewContentOffsetDirty;
    struct CGPoint _scrollViewLastContentOffset;
    SBDashBoardLayoutStrategy *_layoutStrategy;
    id <SBDashBoardTodayViewControllerDelegate> _todayViewControllerDelegate;
    id <SBDashBoardPersistentContentLayoutProviding> _persistentLayoutProviding;
    SBDashBoardPageViewController *_pageController;
    SBViewControllerTransitionContext *_transitionContext;
}

+ (_Bool)_isPortrait;
+ (double)verticalSpacingBetweenWidgets;
+ (Class)viewClass;
- (void).cxx_destruct;
- (_Bool)_allowsDateViewScroll;
- (void)_becomeSpotlightDelegateIfNecessary;
- (double)_dateMinY;
- (id)_dateMovingScrollView;
- (void)_evaluateContentViews;
- (void)_initializeTodayViewControllerIfNecessary;
- (id)_majorScrollView;
- (double)_maxClippingOffset;
- (void)_prepareChildViewControllersIfNecessary;
- (void)_resignSpotlightDelegateIfNecessary;
- (id)_searchNavigationBar;
- (void)_setTodayViewController:(id)arg1;
- (double)_statusBarHeight;
- (double)_topContentInsetForNavigationBar:(id)arg1;
- (double)_totalDistanceForBlurTransition;
- (void)_updateAppearance;
- (void)_updateAppearanceForScrollView:(id)arg1;
- (void)_updateAppearanceForScrollView:(id)arg1 animated:(_Bool)arg2;
- (void)_updateBehavior;
- (void)_updateContentInsets;
- (void)_widgetEditViewDidDisappear:(id)arg1;
- (void)_widgetEditViewDidDisappearImplementation;
- (void)_widgetEditViewWillAppear:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)aggregateBehavior:(id)arg1;
- (void)cleanupAfterSpotlightDismissal;
@property(readonly, nonatomic) double clippingOffset;
- (void)dismissSearchViewWithReason:(unsigned long long)arg1;
@property(readonly, nonatomic) double distanceFromBarToContent;
- (void)handleDraggingWillEndWithTargetContentOffset:(inout struct CGPoint *)arg1 forScrollView:(id)arg2;
- (void)handleScrollingEnded:(id)arg1;
- (id)init;
- (_Bool)isWidgetExtensionWithIdentifierVisible:(id)arg1;
- (id)layoutStrategy;
- (void)loadView;
@property(nonatomic) __weak SBDashBoardPageViewController *pageController; // @synthesize pageController=_pageController;
- (long long)participantState;
@property(nonatomic) __weak id <SBDashBoardPersistentContentLayoutProviding> persistentLayoutProviding; // @synthesize persistentLayoutProviding=_persistentLayoutProviding;
- (_Bool)pullDownSearchGestureDraggingFromTopOfScrollView:(id)arg1;
- (double)pullDownSearchGesturePercentComplete;
- (double)pullDownSearchGestureYOffset;
- (void)resetForSpotlightDismissalAnimated:(_Bool)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)searchFieldDidFocus;
- (void)setLayoutStrategy:(id)arg1;
@property(nonatomic) __weak id <SBDashBoardTodayViewControllerDelegate> todayViewControllerDelegate; // @synthesize todayViewControllerDelegate=_todayViewControllerDelegate;
@property(retain, nonatomic) SBViewControllerTransitionContext *transitionContext; // @synthesize transitionContext=_transitionContext;
@property(readonly, nonatomic) double topContentInset;
- (void)updateAccessoryLegibility;
- (void)updateAppearanceForHidden:(_Bool)arg1 offset:(struct CGPoint)arg2;
- (void)updateAppearanceForStatusBarBackgroundHidden:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (struct UIEdgeInsets)widgetGroupViewController:(id)arg1 contentOccludingInsetsForInterfaceOrientation:(long long)arg2;
- (struct CGSize)widgetGroupViewController:(id)arg1 sizeForInterfaceOrientation:(long long)arg2;
- (struct UIEdgeInsets)widgetListViewEdgeInsetsIncludingSearchHeader:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SBDashBoardTodayPageView *view; // @dynamic view;

@end

