//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BSDescriptionProviding.h"
#import "SBDashBoardViewPresenting.h"

@class FBDisplayLayoutElement, NSArray, NSHashTable, NSSet, NSString, SBDashBoardAppearance, SBDashBoardBehavior, SBDashBoardIsolatingViewController, SBDashBoardLayoutStrategy, SBDashBoardPresentation, UIColor, _UILegibilitySettings;

@interface SBDashBoardViewControllerBase : UIViewController <SBDashBoardViewPresenting, BSDescriptionProviding>
{
    SBDashBoardAppearance *_appearance;
    SBDashBoardBehavior *_behavior;
    SBDashBoardPresentation *_presentation;
    _UILegibilitySettings *_legibilitySettings;
    FBDisplayLayoutElement *_displayLayoutElement;
    SBDashBoardIsolatingViewController *_isolatingViewController;
    SBDashBoardViewControllerBase *_isolatedViewController;
    Class _isolationClass;
    NSHashTable *_regionProviders;
    _Bool _forcingLayoutForPresentation;
    _Bool _isBeingPresented;
    SBDashBoardLayoutStrategy *_layoutStrategy;
    id <SBDashBoardViewPresenting> _presenter;
}

+ (id)dashBoardIdentifier;
+ (Class)isolationViewControllerClass;
+ (Class)viewClass;
- (void).cxx_destruct;
- (void)_layoutIfNeededForPresentation;
- (_Bool)_presentationParticipant;
- (id)_presenter;
- (_Bool)_rebuildAppearance;
- (_Bool)_rebuildBehavior;
- (void)_rebuildDisposition;
- (_Bool)_rebuildPresentation;
- (id)_regionsForView:(id)arg1;
@property(readonly, copy, nonatomic) SBDashBoardAppearance *activeAppearance;
@property(readonly, copy, nonatomic) SBDashBoardBehavior *activeBehavior;
- (void)aggregateAppearance:(id)arg1;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregatePresentation:(id)arg1;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) long long backgroundStyle;
- (_Bool)clipsIsolatedContent;
@property(readonly, copy, nonatomic) NSSet *components;
- (void)configureDisplayLayoutElement:(id)arg1;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)didTransitionToPresented:(_Bool)arg1;
- (void)dismiss;
- (id)displayLayoutElementIdentifier;
- (struct CGSize)effectiveContentSizeForScrollView:(id)arg1;
@property(readonly, copy, nonatomic) SBDashBoardPresentation *externalPresentation;
- (_Bool)handleAction:(id)arg1 fromController:(id)arg2;
- (void)handleAction:(id)arg1 fromSender:(id)arg2;
- (_Bool)handleAppearanceUpdateFromController:(id)arg1 animationSettings:(inout id *)arg2;
- (_Bool)handleEvent:(id)arg1;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(readonly, nonatomic, getter=isDisappeared) _Bool disappeared;
@property(readonly, nonatomic, getter=isIsolatingContent) _Bool isolatingContent;
@property(readonly, nonatomic, getter=isPresentation) _Bool presentation; // @synthesize presentation=_isBeingPresented;
- (void)isolateViewController:(id)arg1;
@property(readonly, nonatomic) SBDashBoardViewControllerBase *isolatedViewController;
@property(readonly, nonatomic) UIViewController *isolatingViewController; // @synthesize isolatingViewController=_isolatingViewController;
@property(readonly, nonatomic) UIViewController *kitPresentedViewController;
@property(retain, nonatomic) SBDashBoardLayoutStrategy *layoutStrategy; // @synthesize layoutStrategy=_layoutStrategy;
@property(readonly, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
- (void)loadView;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long participantState;
- (void)performCustomTransitionToVisible:(_Bool)arg1 withAnimationSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) long long presentationAltitude;
@property(readonly, nonatomic) _Bool presentationCancelsTouches;
@property(readonly, nonatomic) __weak id <UICoordinateSpace> presentationCoordinateSpace;
@property(readonly, nonatomic) long long presentationPriority;
@property(readonly, copy, nonatomic) NSArray *presentationRegions;
@property(readonly, nonatomic) long long presentationStyle;
@property(readonly, nonatomic) long long presentationTransition;
@property(readonly, nonatomic) long long presentationType;
@property(nonatomic) __weak id <SBDashBoardViewPresenting> presenter; // @synthesize presenter=_presenter;
@property(readonly, nonatomic) long long proximityDetectionMode;
- (void)rebuildAppearance;
- (void)rebuildBehavior;
- (void)rebuildEverythingForReason:(id)arg1;
- (void)registerView:(id)arg1 forRole:(long long)arg2;
- (void)registerView:(id)arg1 forRole:(long long)arg2 options:(unsigned long long)arg3;
@property(readonly, nonatomic) unsigned long long restrictedCapabilities;
@property(readonly, nonatomic) long long scrollingStrategy;
- (void)sendAction:(id)arg1;
- (void)setDisplayLayoutElementActive:(_Bool)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (void)synchronizeDrawingWithIsolatedContent;
- (void)unregisterAllViews;
- (void)unregisterView:(id)arg1;
- (void)updateAppearance:(CDUnknownBlockType)arg1;
- (void)updateAppearance:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateAppearanceForController:(id)arg1;
- (void)updateAppearanceForController:(id)arg1 withAnimationSettings:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateBehavior:(CDUnknownBlockType)arg1;
- (void)updateBehaviorForController:(id)arg1;
- (void)updateForPresentation:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willTransitionToPresented:(_Bool)arg1;
- (_Bool)wouldHandleButtonEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

