//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTPlatterView.h"

@class UIViewController<SBDashBoardAdjunctItemHosting>;

@interface SBDashBoardAdjunctItemView : MTPlatterView
{
    UIViewController<SBDashBoardAdjunctItemHosting> *_contentHost;
    struct CGSize _sizeToMimic;
}

- (void).cxx_destruct;
- (void)_layoutContentHost;
@property(nonatomic) __weak UIViewController<SBDashBoardAdjunctItemHosting> *contentHost; // @synthesize contentHost=_contentHost;
- (id)initWithRecipe:(long long)arg1 options:(unsigned long long)arg2;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
@property(nonatomic) struct CGSize sizeToMimic; // @synthesize sizeToMimic=_sizeToMimic;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;

@end

