//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "MediaControlsPanelViewControllerDelegate.h"
#import "SBDashBoardAdjunctItemHosting.h"

@class MediaControlsPanelViewController, NSString;

@interface SBDashBoardMediaControlsViewController : SBDashBoardViewControllerBase <MediaControlsPanelViewControllerDelegate, SBDashBoardAdjunctItemHosting>
{
    MediaControlsPanelViewController *_mediaControlsPanelViewController;
    struct CGSize _containerSize;
}

+ (Class)viewClass;
- (void).cxx_destruct;
- (void)_layoutMediaControls;
- (struct CGRect)_suggestedFrameForMediaControls;
- (void)_updatePersistentUpdatesEnabled:(_Bool)arg1;
@property(nonatomic) struct CGSize containerSize; // @synthesize containerSize=_containerSize;
- (_Bool)handleEvent:(id)arg1;
- (id)init;
- (void)mediaControlsPanelViewController:(id)arg1 didReceiveInteractionEvent:(id)arg2;
- (struct CGSize)preferredContentSize;
- (long long)presentationPriority;
- (long long)presentationType;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

