//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

#import "SBDashBoardEventHandling.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, NSTimer, SBActivationInfoViewController, SBSetupManager, SBSetupRegulatoryInfoViewController, SBSetupWiFiScanner;

@interface SBDashBoardSetupViewController : SBDashBoardViewControllerBase <SBDashBoardEventHandling>
{
    SBSetupWiFiScanner *_wifiScanner;
    SBActivationInfoViewController *_activationInfoViewController;
    SBSetupRegulatoryInfoViewController *_regulatoryInfoViewController;
    SBSetupManager *_setupManager;
    NSString *_configureKey;
    NSString *_wifiPrimaryLanguage;
    NSString *_telephonyPrimaryLanguage;
    NSTimer *_cycleStartTimer;
    NSDictionary *_localizedStrings;
    NSArray *_stringsOrdering;
    NSMutableArray *_currentStringsOrdering;
    unsigned long long _currentStringsIndex;
    _Bool _shouldResetOrderingOnNextCycle;
    _Bool _isCyclingComponents;
    unsigned long long _componentsToCycle;
}

- (void).cxx_destruct;
- (void)_animateComponentsForNewCycle;
- (void)_cancelWifiScan;
- (id)_currentLanguageIdentifier;
- (id)_currentStringsDictionary;
- (void)_fetchLanguageFromTelephony;
- (id)_importantLanguageIdentifiers;
- (void)_incrementLocalizedStringsForNewCycle;
- (void)_infoButtonTapped:(id)arg1;
- (void)_regulatoryInfoButtonTapped:(id)arg1;
- (void)_resetDisplayedLocalizedStringsImmediately:(_Bool)arg1;
- (void)_startCyclingComponents:(unsigned long long)arg1 withDelay:(double)arg2;
- (void)_startWifiScan;
- (void)_stopCyclingComponents:(unsigned long long)arg1;
- (void)_updateDisplayedStrings;
- (void)_updateWifiPrimaryLanguageFromGuessedCountries:(id)arg1;
- (void)aggregateAppearance:(id)arg1;
- (void)aggregateBehavior:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (id)init;
- (void)loadView;
- (long long)presentationPriority;
- (long long)presentationType;
- (id)setupView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

