//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBFAuthenticationPolicy.h"

@class NSString, SecureBackup;

@interface SBDefaultAuthenticationPolicy : NSObject <SBFAuthenticationPolicy>
{
    SecureBackup *_secureBackupHelper;
}

- (void).cxx_destruct;
@property(retain, nonatomic, getter=_secureBackupHelper, setter=_setSecureBackupHelper:) SecureBackup *secureBackupHelper; // @synthesize secureBackupHelper=_secureBackupHelper;
- (_Bool)allowAuthenticationRevocation;
- (void)cachePasscode:(id)arg1;
- (void)clearPasscodeCache;
- (void)passcodeAuthenticationFailedWithError:(id)arg1;
- (_Bool)shouldClearBlockStateOnSync;
- (_Bool)usesSecureMode;
- (void)wipeDeviceWithReason:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

