//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMutableCopying.h"
#import "SBScenePlaceholderContentContext.h"

@class NSString, NSURL;

@interface SBDeviceApplicationScenePlaceholderContentContext : NSObject <SBScenePlaceholderContentContext, NSMutableCopying>
{
    id <SBActivationSettings> _settings;
    NSString *_requestedLaunchIdentifier;
    NSURL *_url;
    _Bool _prefersLiveXIB;
    unsigned long long _preferredContentType;
}

- (void).cxx_destruct;
@property(copy, nonatomic) id <SBActivationSettings> activationSettings; // @synthesize activationSettings=_settings;
@property(readonly, nonatomic) _Bool canShowUserContent;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithActivationSettings:(id)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) unsigned long long preferredContentType; // @synthesize preferredContentType=_preferredContentType;
@property(nonatomic) _Bool prefersLiveXIB; // @synthesize prefersLiveXIB=_prefersLiveXIB;
@property(copy, nonatomic) NSString *requestedLaunchIdentifier; // @synthesize requestedLaunchIdentifier=_requestedLaunchIdentifier;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

