//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBApplicationSceneView.h"

#import "SBAppSwitcherPageContentView.h"

@class NSMutableArray, NSString, SBApplicationSceneViewStatusBarDescriptor, SBDeviceApplicationSceneHandle, SBHomeGrabberSettings, SBHomeGrabberView, SBSceneHandleBlockObserver, UIApplicationSceneClientSettingsDiffInspector, UIView, UIView<SBApplicationSceneBackgroundView>;

@interface SBDeviceApplicationSceneView : SBApplicationSceneView <SBAppSwitcherPageContentView>
{
    SBSceneHandleBlockObserver *_sceneHandleObserver;
    UIApplicationSceneClientSettingsDiffInspector *_clientSettingsInspector;
    SBApplicationSceneViewStatusBarDescriptor *_statusBarDescriptor;
    UIView *_hostCounterRotationView;
    NSMutableArray *_clientRotationViews;
    SBHomeGrabberView *_grabberView;
    SBHomeGrabberSettings *_grabberSettings;
    double _statusBarAlpha;
}

- (void).cxx_destruct;
- (void)_configureSceneLiveHostView:(id)arg1;
- (void)_configureSceneSnapshotContext:(id)arg1;
- (void)_refresh;
- (_Bool)_representsTranslucentContent;
- (void)_sceneHandleDidUpdateClientSettingsWithDiff:(id)arg1 transitionContext:(id)arg2;
- (void)_updateStatusBarVisibilityForHostView;
- (long long)_wallpaperStyle;
@property(readonly, nonatomic) _Bool contentRequiresGroupOpacity;
@property(nonatomic) double cornerRadius;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)deviceApplicationSceneView;
@property(nonatomic) _Bool forcesStatusBarHidden;
@property(readonly, nonatomic) SBHomeGrabberView *homeGrabberView;
- (id)initWithSceneHandle:(id)arg1 referenceSize:(struct CGSize)arg2 orientation:(long long)arg3 hostRequester:(id)arg4;
- (void)invalidate;
- (void)layoutSubviews;
- (void)setActive:(_Bool)arg1;
@property(retain, nonatomic) UIView<SBApplicationSceneBackgroundView> *backgroundView; // @dynamic backgroundView;
@property(nonatomic) double statusBarAlpha; // @synthesize statusBarAlpha=_statusBarAlpha;
@property(retain, nonatomic) SBApplicationSceneViewStatusBarDescriptor *statusBarDescriptor; // @synthesize statusBarDescriptor=_statusBarDescriptor;
- (void)setVisible:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long orientation;
@property(readonly, nonatomic) SBDeviceApplicationSceneHandle *sceneHandle; // @dynamic sceneHandle;
@property(readonly) Class superclass;

@end

