//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface SBDistanceFieldView : UIView
{
}

+ (Class)layerClass;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
@property struct CGColor *foregroundColor;
@property _Bool invertsShape;
@property double lineWidth;
@property double offset;
@property(copy, nonatomic) NSString *renderMode;
@property double sharpness;

@end

