//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBRootIconListView.h"

@interface SBDockIconListView : SBRootIconListView
{
    long long _layoutStyle;
    double _spacing;
    unsigned long long _minimumNumberOfIconsToDistributeEvenlyToEdges;
    struct UIEdgeInsets _layoutInsets;
}

+ (double)defaultHeight;
+ (unsigned long long)defaultIconContentType;
+ (unsigned long long)iconColumnsForInterfaceOrientation:(long long)arg1;
+ (unsigned long long)iconRowsForInterfaceOrientation:(long long)arg1;
+ (unsigned long long)maxIcons;
+ (unsigned long long)maxVisibleIconRowsInterfaceOrientation:(long long)arg1;
- (double)_additionalHorizontalInsetToCenterIcons;
- (double)_additionalVerticalInsetToCenterIcons;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (_Bool)allowsAddingIconCount:(unsigned long long)arg1;
- (struct CGRect)boundsForLayout;
@property(readonly, nonatomic) double effectiveSpacing;
- (double)effectiveSpacingForNumberOfIcons:(unsigned long long)arg1;
- (id)iconAtPoint:(struct CGPoint)arg1 index:(unsigned long long *)arg2 proposedOrder:(int *)arg3;
- (long long)iconLocation;
- (unsigned long long)iconsInColumnForSpacingCalculation;
- (unsigned long long)iconsInRowForSpacingCalculation;
- (id)initWithModel:(id)arg1 orientation:(long long)arg2 viewMap:(id)arg3;
- (struct CGSize)intrinsicContentSize;
@property(nonatomic) struct UIEdgeInsets layoutInsets; // @synthesize layoutInsets=_layoutInsets;
@property(nonatomic) long long layoutStyle; // @synthesize layoutStyle=_layoutStyle;
@property(nonatomic) unsigned long long minimumNumberOfIconsToDistributeEvenlyToEdges; // @synthesize minimumNumberOfIconsToDistributeEvenlyToEdges=_minimumNumberOfIconsToDistributeEvenlyToEdges;
- (struct CGPoint)originForIconAtCoordinate:(struct SBIconCoordinate)arg1;
- (struct CGPoint)originForIconAtCoordinate:(struct SBIconCoordinate)arg1 numberOfIcons:(unsigned long long)arg2;
- (unsigned long long)rowAtPoint:(struct CGPoint)arg1;
- (struct CGSize)scaledAlignmentIconSize;
@property(nonatomic) double spacing; // @synthesize spacing=_spacing;

@end

