//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBMainWorkspaceTransaction.h"

#import "UIDropInteractionDelegate.h"

@class NSSet, NSString, NSURL, SBDeviceApplicationSceneHandle, SBFloatingApplicationController, SBMainDisplayLayoutState, SBMainDisplaySceneLayoutViewController, SBMedusaPlatterDragPreview, SBToAppsWorkspaceTransaction, SBWindow;

@interface SBDragAndDropAppActivationWorkspaceTransaction : SBMainWorkspaceTransaction <UIDropInteractionDelegate>
{
    SBMainDisplaySceneLayoutViewController *_sceneLayoutViewController;
    SBFloatingApplicationController *_floatingApplicationController;
    SBMainDisplayLayoutState *_initialLayoutState;
    SBMainDisplayLayoutState *_finalLayoutState;
    id <UIDropSession> _dropSession;
    unsigned long long _sessionState;
    SBDeviceApplicationSceneHandle *_draggingApplicationSceneHandle;
    NSSet *_draggingLaunchActions;
    NSURL *_draggingLaunchURL;
    long long _draggingStartLocation;
    SBToAppsWorkspaceTransaction *_currentWorkspaceTransaction;
    unsigned long long _currentDropAction;
    _Bool _performedDrop;
    _Bool _dropAnimationCompleted;
    unsigned long long _blurState;
    _Bool _resizingElementViewControllers;
    SBMedusaPlatterDragPreview *_activePreviewPlatter;
    SBWindow *_setDownCoordinateSpaceProvidingWindow;
}

+ (double)prototypeSettingsMinifiedPlatterHeightScaleForOrientation:(long long)arg1;
+ (double)prototypeSettingsMinifiedPlatterWidthScaleForOrientation:(long long)arg1;
+ (double)prototypeSettingsSideActivationGutterSize;
- (void).cxx_destruct;
- (void)_addChildWorkspaceTransaction:(id)arg1;
- (_Bool)_areLayoutElementViewControllersBlurred;
- (_Bool)_areLayoutElementViewControllersCorrectlySizedForDropAction:(unsigned long long)arg1;
- (void)_begin;
- (_Bool)_canBeInterrupted;
- (void)_childTransactionDidComplete:(id)arg1;
- (void)_cleanUpAndCompleteTransactionIfNecessary;
- (void)_configurePlatterPreview:(id)arg1 forSceneHandle:(id)arg2;
- (void)_didComplete;
- (void)_didInterruptForTransitionRequest:(id)arg1;
- (void)_dismissSpotlightAlertIfNeeded;
- (_Bool)_draggingAppIsAlreadyActiveAndVisible;
- (void)_getPrimaryLayoutElementViewFrame:(struct CGRect *)arg1 sideLayoutElementViewFrame:(struct CGRect *)arg2 separatorViewFrame:(struct CGRect *)arg3 forDropAction:(unsigned long long)arg4 state:(unsigned long long)arg5;
- (void)_getPrimaryLayoutElementViewFrame:(struct CGRect *)arg1 sideLayoutElementViewFrame:(struct CGRect *)arg2 separatorViewFrame:(struct CGRect *)arg3 forDropAction:(unsigned long long)arg4 state:(unsigned long long)arg5 spaceConfiguration:(long long)arg6;
- (void)_handleDropSessionDidEnd:(id)arg1;
- (_Bool)_handleDropSessionDidUpdate:(id)arg1;
- (void)_hideSetDownCoordinateSpaceProvidingWindow;
- (long long)_layoutRoleForDropAction:(unsigned long long)arg1;
- (id)_primaryLayoutElementViewController;
- (void)_setFloatingApplicationHidden:(_Bool)arg1;
- (void)_setFloatingApplicationStashed:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)_shouldComplete;
- (_Bool)_showResizeUI;
- (void)_showSetDownCoordinateSpaceProvidingWindow;
- (id)_sideLayoutElementViewController;
- (struct CGSize)_sizeForFloatingApplication;
- (id)_transitionRequestForDropAction:(unsigned long long)arg1;
- (void)_updateCurrentDropActionForSession:(id)arg1;
- (void)_updateLayoutElementViewControllerBlurringWithCompletion:(CDUnknownBlockType)arg1;
- (void)_updateLayoutElementViewControllerDarkeningWithCompletion:(CDUnknownBlockType)arg1;
- (void)_updateLayoutElementViewControllerForDropCompletion;
- (void)_updateLayoutElementViewControllerFrames;
- (void)_updateLayoutElementViewControllersWithCompletion:(CDUnknownBlockType)arg1;
- (void)_updatePlatterSizeAndStateForSetDown:(_Bool)arg1;
- (_Bool)canInterruptForTransitionRequest:(id)arg1;
- (void)dropInteraction:(id)arg1 concludeDrop:(id)arg2;
- (void)dropInteraction:(id)arg1 item:(id)arg2 willAnimateDropWithAnimator:(id)arg3;
- (void)dropInteraction:(id)arg1 performDrop:(id)arg2;
- (id)dropInteraction:(id)arg1 previewForDroppingItem:(id)arg2 withDefault:(id)arg3;
- (void)dropInteraction:(id)arg1 sessionDidEnd:(id)arg2;
- (void)dropInteraction:(id)arg1 sessionDidEnter:(id)arg2;
- (void)dropInteraction:(id)arg1 sessionDidExit:(id)arg2;
- (id)dropInteraction:(id)arg1 sessionDidUpdate:(id)arg2;
- (id)initWithTransitionRequest:(id)arg1;
- (id)initWithTransitionRequest:(id)arg1 sceneLayoutViewController:(id)arg2 dropSession:(id)arg3;
- (id)resizeUIAnimationFactory;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

