//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "SBMainDisplayWorkspaceAppInteractionEventSourceObserving.h"

@class NSDate, NSString, SBAppLayout, SBFluidSwitcherGesture, SBHomeGestureSettings, SBMainDisplayLayoutState, SBWorkspaceApplicationSceneTransitionContext;

@interface SBFluidSwitcherLayoutContext : NSObject <BSDescriptionProviding, SBMainDisplayWorkspaceAppInteractionEventSourceObserving>
{
    _Bool _hasUserInteractedWithActiveApplication;
    long long _layoutPhase;
    SBMainDisplayLayoutState *_previousLayoutState;
    SBFluidSwitcherGesture *_activeGesture;
    long long _previousGestureType;
    SBWorkspaceApplicationSceneTransitionContext *_activeTransitionContext;
    unsigned long long _generationCount;
    SBAppLayout *_transitioningFromAppLayout;
    SBAppLayout *_transitioningToAppLayout;
    SBMainDisplayLayoutState *_currentLayoutState;
    long long _previousInterfaceOrientation;
    SBAppLayout *_currentAppLayout;
    NSDate *_lastTransitionCompletionDate;
    SBHomeGestureSettings *_homeGestureSettings;
}

- (void).cxx_destruct;
- (void)_cacheAppLayouts;
- (_Bool)_shouldUpdateSwitcherModelBasedOnTimeOrUserInteraction;
@property(retain, nonatomic) SBFluidSwitcherGesture *activeGesture; // @synthesize activeGesture=_activeGesture;
@property(readonly, nonatomic) SBWorkspaceApplicationSceneTransitionContext *activeTransitionContext; // @synthesize activeTransitionContext=_activeTransitionContext;
@property(readonly, nonatomic) SBAppLayout *appLayout;
@property(retain, nonatomic) SBAppLayout *currentAppLayout; // @synthesize currentAppLayout=_currentAppLayout;
@property(retain, nonatomic) SBMainDisplayLayoutState *currentLayoutState; // @synthesize currentLayoutState=_currentLayoutState;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)eventSource:(id)arg1 userTouchedApplication:(id)arg2;
@property(readonly, nonatomic) unsigned long long generationCount; // @synthesize generationCount=_generationCount;
@property(nonatomic) _Bool hasUserInteractedWithActiveApplication; // @synthesize hasUserInteractedWithActiveApplication=_hasUserInteractedWithActiveApplication;
@property(retain, nonatomic) SBHomeGestureSettings *homeGestureSettings; // @synthesize homeGestureSettings=_homeGestureSettings;
- (void)incrementGenerationCount;
- (id)initWithLayoutState:(id)arg1;
@property(retain, nonatomic) NSDate *lastTransitionCompletionDate; // @synthesize lastTransitionCompletionDate=_lastTransitionCompletionDate;
@property(readonly, nonatomic) long long layoutPhase; // @synthesize layoutPhase=_layoutPhase;
@property(readonly, nonatomic) SBMainDisplayLayoutState *layoutState;
@property(nonatomic) long long previousGestureType; // @synthesize previousGestureType=_previousGestureType;
@property(nonatomic) long long previousInterfaceOrientation; // @synthesize previousInterfaceOrientation=_previousInterfaceOrientation;
@property(retain, nonatomic) SBMainDisplayLayoutState *previousLayoutState; // @synthesize previousLayoutState=_previousLayoutState;
@property(readonly, nonatomic) double secondsSinceLastTransitionCompletion;
@property(retain, nonatomic) SBAppLayout *transitioningFromAppLayout; // @synthesize transitioningFromAppLayout=_transitioningFromAppLayout;
@property(retain, nonatomic) SBAppLayout *transitioningToAppLayout; // @synthesize transitioningToAppLayout=_transitioningToAppLayout;
- (_Bool)shouldAddAppLayoutToFront:(id)arg1 forTransitionWithContext:(id)arg2 currentAppLayouts:(id)arg3 transitionCompleted:(_Bool)arg4;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
@property(readonly, nonatomic) unsigned long long supportedOrientationsForGesture;
@property(readonly, nonatomic) SBMainDisplayLayoutState *transitioningFromLayoutState;
@property(readonly, nonatomic) SBMainDisplayLayoutState *transitioningToLayoutState;
- (void)updateLayoutStateWithContext:(id)arg1;
- (void)updateLayoutStateWithContext:(id)arg1 prepareIfNeeded:(CDUnknownBlockType)arg2 transition:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

