//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, SBAppLayout, SBFluidBehaviorSettings, SBFluidSwitcherGesture, SBFluidSwitcherViewController, SBWorkspaceApplicationSceneTransitionContext;

@protocol SBFluidSwitcherPersonality <NSObject>
- (SBAppLayout *)appLayoutForHomeScreenIconZoom;
- (SBAppLayout *)appLayoutToScrollToWhenActivatingSwitcher;
- (SBAppLayout *)appLayoutUnderWhichToAddDimmingView;
- (double)baseHysteresisForStartingKillGesture;
- (double)cardCornerRadiusForIndex:(unsigned long long)arg1;
- (_Bool)clipsToUnobscuredMarginAtIndex:(unsigned long long)arg1;
- (struct CGPoint)contentOffsetForIndex:(unsigned long long)arg1 ignoreInsertionsAndRemovals:(_Bool)arg2;
- (struct CGSize)contentSize;
- (double)darkeningAlphaForIndex:(unsigned long long)arg1;
- (double)decelerationRate;
- (void)didInsertAppLayout:(SBAppLayout *)arg1 atIndex:(unsigned long long)arg2;
- (void)didRemoveAppLayout:(SBAppLayout *)arg1 fromIndex:(unsigned long long)arg2;
- (double)dimmingAlpha;
- (struct CGRect)frameForIndex:(unsigned long long)arg1 mode:(long long)arg2;
- (double)homeScreenAlpha;
- (double)homeScreenBlurProgress;
- (double)homeScreenScale;
- (struct CGSize)interpageSpacingForPaging;
- (_Bool)isIndexVisible:(unsigned long long)arg1 ignoreInsertionsAndRemovals:(_Bool)arg2;
- (_Bool)itemsOverlapDuringScrolling;
- (NSArray *)itemsToKeepInHierarchyDuringAnimationForInsertion:(_Bool)arg1 direction:(unsigned long long)arg2 visibleItemRange:(struct _NSRange)arg3;
- (unsigned long long)movementDirectionForInsertionOrRemovalAtIndex:(unsigned long long)arg1 isInserting:(_Bool)arg2;
- (unsigned long long)numberOfAppLayoutsForWhichToCacheSnapshots;
- (double)opacityForIndex:(unsigned long long)arg1;
- (SBFluidBehaviorSettings *)overrideLayoutSettingsForIndex:(unsigned long long)arg1 defaultSettings:(SBFluidBehaviorSettings *)arg2;
- (SBFluidBehaviorSettings *)overridePositionSettingsForIndex:(unsigned long long)arg1 defaultSettings:(SBFluidBehaviorSettings *)arg2;
- (SBFluidBehaviorSettings *)overrideScaleSettingsForIndex:(unsigned long long)arg1 defaultSettings:(SBFluidBehaviorSettings *)arg2;
- (struct CGPoint)pagingOrigin;
- (void)performUpdatesWithCachedValues:(void (^)(void))arg1;
- (struct CGPoint)restingOffsetForScrollOffset:(struct CGPoint)arg1 velocity:(struct CGPoint)arg2;
- (double)scaleForIndex:(unsigned long long)arg1 mode:(long long)arg2;
- (_Bool)scrollViewPagingEnabled;
@property(nonatomic) __weak SBFluidSwitcherViewController *switcherViewController;
- (double)shadowOpacityForIndex:(unsigned long long)arg1;
- (_Bool)shouldAnimateInsertionOrRemovalAtIndex:(unsigned long long)arg1 visibleItemRange:(struct _NSRange)arg2;
- (_Bool)shouldAnimateTransitionForContext:(SBWorkspaceApplicationSceneTransitionContext *)arg1;
- (_Bool)shouldHideStatusBarForActiveGesture;
- (_Bool)shouldInterruptPresentationAndDismiss;
- (_Bool)shouldPreserveScrollPositionForInsertionOrRemovalAtIndex:(unsigned long long)arg1 isInserting:(_Bool)arg2 visibleItemRange:(struct _NSRange)arg3 startingScrollIndex:(unsigned long long *)arg4 finalScrollIndex:(unsigned long long *)arg5 animated:(_Bool)arg6;
- (_Bool)shouldScrollWhenActivatingAppLayoutAtIndex:(unsigned long long)arg1;
- (_Bool)shouldUseLiveHomeScreenBlurForAllTransitions;
- (_Bool)shouldWaitForLayoutAndStyleUpdatesForTransactionCompletion;
- (double)snapshotScale;
- (double)switcherCardScale;
- (double)switcherOpacity;
- (double)titleAndIconOpacityForIndex:(unsigned long long)arg1;
- (double)titleOpacityForIndex:(unsigned long long)arg1;
- (SBAppLayout *)topMostAppLayout;
- (double)visibleMarginForItemContainerAtIndex:(unsigned long long)arg1;
- (double)wallpaperScale;

@optional
- (struct CGPoint)adjustedOffsetForOffset:(struct CGPoint)arg1 translation:(struct CGPoint)arg2 startPoint:(struct CGPoint)arg3 locationInView:(struct CGPoint)arg4 horizontalVelocity:(inout double *)arg5 verticalVelocity:(inout double *)arg6;
- (struct CGPoint)contentOffsetForActiveGesture;
- (NSArray *)defaultAppLayouts;
- (void)didBeginGesture:(SBFluidSwitcherGesture *)arg1;
- (void)didEndGesture:(SBFluidSwitcherGesture *)arg1;
- (void)didUpdateGesture:(SBFluidSwitcherGesture *)arg1;
- (double)dockProgress;
- (struct CGRect)frameForControlCenter;
- (double)opacityForControlCenter;
- (void)resetAdjustedScrollingState;
- (double)scaleForControlCenter;
- (void)scrollViewKillingProgressUpdated:(double)arg1 ofAppLayout:(SBAppLayout *)arg2;
- (_Bool)shouldAdjustContentOffsetForActiveGesture;
- (_Bool)shouldAnimateScaleForDosidoTransitions;
- (_Bool)shouldShowControlCenter;
- (double)statusTextHeightForControlCenter;
- (_Bool)supportsForcePressGesture;
- (_Bool)usesExternalAnimatorForDosido;
- (void)willPerformLayout;
@end

