//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSString, SBFluidSwitcherGestureWorkspaceTransaction, UIGestureRecognizer;

@interface SBFluidSwitcherGesture : NSObject <BSDescriptionProviding>
{
    long long _type;
    long long _state;
    SBFluidSwitcherGestureWorkspaceTransaction *_gestureTransaction;
}

- (void).cxx_destruct;
- (void)_setState:(long long)arg1;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, nonatomic) UIGestureRecognizer *gestureRecognizer;
@property(readonly, nonatomic) SBFluidSwitcherGestureWorkspaceTransaction *gestureTransaction; // @synthesize gestureTransaction=_gestureTransaction;
- (id)initWithType:(long long)arg1 gestureTransaction:(id)arg2;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

