//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSDate, NSString, SBFloatingDockController;

@interface SBFloatingDockBehaviorAssertion : NSObject <BSDescriptionProviding>
{
    _Bool _gesturePossible;
    unsigned long long _level;
    double _progress;
    NSString *_reason;
    NSDate *_timestamp;
    SBFloatingDockController *_floatingDockController;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, nonatomic) __weak SBFloatingDockController *floatingDockController; // @synthesize floatingDockController=_floatingDockController;
@property(readonly, nonatomic) _Bool gesturePossible; // @synthesize gesturePossible=_gesturePossible;
- (id)init;
- (id)initWithFloatingDockController:(id)arg1 visibleProgress:(double)arg2 gesturePossible:(_Bool)arg3 atLevel:(unsigned long long)arg4 reason:(id)arg5 withCompletion:(CDUnknownBlockType)arg6;
- (id)initWithPinned:(_Bool)arg1 gesturePossible:(_Bool)arg2 atLevel:(unsigned long long)arg3 reason:(id)arg4 withCompletion:(CDUnknownBlockType)arg5;
- (id)initWithVisibleProgress:(double)arg1 gesturePossible:(_Bool)arg2 atLevel:(unsigned long long)arg3 reason:(id)arg4 withCompletion:(CDUnknownBlockType)arg5;
- (void)invalidate;
- (void)invalidateWithCompletion:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic, getter=isPinned) _Bool pinned;
@property(readonly, nonatomic) unsigned long long level; // @synthesize level=_level;
- (void)modifyProgress:(double)arg1 interactive:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) double progress; // @synthesize progress=_progress;
@property(readonly, copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
@property(readonly, copy, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

