//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SBFailureNotifyingTapGestureRecognizerDelegate.h"
#import "SBFluidSwitcherItemContainerHeaderViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSString, SBAppLayout, SBAppSwitcherPageView, SBAppSwitcherSettings, SBFailureNotifyingTapGestureRecognizer, SBFluidBehaviorSettings, SBFluidSwitcherIconOverlayView, SBFluidSwitcherItemContainerHeaderView, SBSwitcherCardCloseBox, UILongPressGestureRecognizer, UIScrollView, UITapGestureRecognizer, UIView<SBAppSwitcherPageContentView>;

@interface SBFluidSwitcherItemContainer : UIView <UIScrollViewDelegate, UIGestureRecognizerDelegate, SBFluidSwitcherItemContainerHeaderViewDelegate, SBFailureNotifyingTapGestureRecognizerDelegate>
{
    SBAppSwitcherPageView *_pageView;
    SBAppLayout *_appLayout;
    id <SBFluidSwitcherItemContainerDelegate> _delegate;
    UIScrollView *_verticalScrollView;
    SBFluidSwitcherItemContainerHeaderView *_iconAndLabelHeader;
    SBFluidSwitcherIconOverlayView *_iconOverlayView;
    SBSwitcherCardCloseBox *_closeBox;
    double _killVelocity;
    double _contentCornerRadius;
    double _contentPageViewScale;
    double _titleOpacity;
    double _titleAndIconOpacity;
    UILongPressGestureRecognizer *_pressDownGestureRecognizer;
    UILongPressGestureRecognizer *_selectionHighlightGestureRecognizer;
    UILongPressGestureRecognizer *_enableKillAffordanceLongPressGestureRecognizer;
    SBFailureNotifyingTapGestureRecognizer *_tapGestureRecognizer;
    UITapGestureRecognizer *_doubleTapGestureRecognizer;
    SBFluidBehaviorSettings *_squishSettings;
    SBAppSwitcherSettings *_settings;
    _Bool _isActive;
    _Bool _isVisible;
    _Bool _killingAffordanceEnabled;
    _Bool _sentKillRequest;
    struct CGPoint _highlightTapDownLocation;
    _Bool _highlighted;
    _Bool _clipsToUnobscuredMargin;
    _Bool _blurEnabled;
    double _unobscuredMargin;
    double _contentAlpha;
}

+ (struct SBSwitcherItemContainerHeaderMetrics)_headerMetrics;
+ (double)preferredRestingVisibleMarginForBounds:(struct CGRect)arg1;
- (void).cxx_destruct;
- (void)_addPageView;
- (void)_applyVisualStyleToSubviews;
- (struct CGPoint)_closeBoxCenter;
- (id)_createCloseBox;
- (id)_createScrollView;
- (double)_effectiveTitleAndIconOpacityConsideringKillProgress;
- (void)_ensureSubviewOrder;
- (struct CGRect)_frameForIconTitleViewContainer;
- (struct CGRect)_frameForPageView;
- (struct CGRect)_frameForScrollView;
- (void)_handleEnableKillAffordanceLongPressGesture:(id)arg1;
- (void)_handlePageViewPressDown:(id)arg1;
- (void)_handlePageViewTap:(id)arg1;
- (void)_handleSelectionHighlightGesture:(id)arg1;
- (double)_inverseScaleTransformFactor;
- (_Bool)_isContainedInGridSwitcher;
- (double)_killingProgressForContentOffset:(struct CGPoint)arg1;
- (void)_resetKillProgressScrollState;
- (double)_scaleTransformFactor;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)_springLoadingEffectTargetView;
- (struct CGAffineTransform)_squishedPageViewScaleTransform;
- (void)_tappedCloseBox:(id)arg1;
- (struct CGAffineTransform)_transformForIconTitleViewContainer;
- (void)_updateHeader;
- (void)_updateScrollEnabled;
@property(retain, nonatomic) SBAppLayout *appLayout; // @synthesize appLayout=_appLayout;
@property(nonatomic) _Bool blocksContentViewTouches;
@property(readonly, nonatomic) _Bool blurEnabled; // @synthesize blurEnabled=_blurEnabled;
@property(nonatomic) _Bool clipsToUnobscuredMargin; // @synthesize clipsToUnobscuredMargin=_clipsToUnobscuredMargin;
- (void)configureOverlayForIconZoomWithView:(id)arg1;
@property(nonatomic) double contentAlpha; // @synthesize contentAlpha=_contentAlpha;
@property(nonatomic) double contentCornerRadius; // @synthesize contentCornerRadius=_contentCornerRadius;
@property(retain, nonatomic) UIView *contentOverlay;
@property(nonatomic) double contentPageViewScale; // @synthesize contentPageViewScale=_contentPageViewScale;
@property(retain, nonatomic) UIView<SBAppSwitcherPageContentView> *contentView;
@property(nonatomic) double darkeningAlpha;
@property(readonly, nonatomic) __weak id <SBFluidSwitcherItemContainerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)gestureRecognizerTransitionedToFailed:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 appLayout:(id)arg2 delegate:(id)arg3 active:(_Bool)arg4;
- (_Bool)isContainerVisibleFor:(id)arg1;
@property(nonatomic, getter=isHighlighted) _Bool highlighted;
@property(nonatomic) double killGestureHysteresis;
@property(nonatomic) _Bool killingAffordanceEnabled;
@property(readonly, nonatomic) double killingProgress;
- (void)layoutSubviews;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)prepareForReuse;
- (void)removeIconOverlay;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)setActive:(_Bool)arg1;
- (void)setContentOverlay:(id)arg1 animated:(_Bool)arg2;
- (void)setKillingAffordanceEnabled:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) double shadowAlpha;
@property(nonatomic) struct CGRect shadowClippingFrame;
@property(nonatomic) _Bool shouldClipShadow;
@property(nonatomic) double titleAndIconOpacity; // @synthesize titleAndIconOpacity=_titleAndIconOpacity;
@property(nonatomic) double titleOpacity; // @synthesize titleOpacity=_titleOpacity;
@property(nonatomic) double unobscuredMargin; // @synthesize unobscuredMargin=_unobscuredMargin;
- (void)setVisible:(_Bool)arg1;
- (void)transitionDidEnd:(_Bool)arg1 forPresentation:(_Bool)arg2 transitionRequest:(id)arg3;
- (void)viewDismissing:(id)arg1 forTransitionRequest:(id)arg2;
- (void)viewPresenting:(id)arg1 forTransitionRequest:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

