//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SBIconObserver.h"

@class NSString, SBDisplayItem, SBIcon, UIImageView;

@interface SBFluidSwitcherIconImageContainerView : UIView <SBIconObserver>
{
    SBDisplayItem *_displayItem;
    SBIcon *_icon;
    UIImageView *_imageView;
    id <SBFluidSwitcherIconImageContainerViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_configureIconImageView:(id)arg1;
- (void)_crossfadeToIconImage:(id)arg1;
- (_Bool)_deviceIsCapableOfCrossfadingIconDuringScroll;
- (_Bool)_isVisible;
@property(readonly, nonatomic) __weak id <SBFluidSwitcherIconImageContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SBDisplayItem *displayItem; // @synthesize displayItem=_displayItem;
@property(readonly, nonatomic) NSString *displayName;
@property(retain, nonatomic) SBIcon *icon; // @synthesize icon=_icon;
- (void)iconImageDidUpdate:(id)arg1;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithDelegate:(id)arg1;
- (void)layoutSubviews;
- (void)updateIcon;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

