//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBSystemServiceServerHardwareButtonDelegate.h"

@class FBServiceClientAuthenticator, NSMutableOrderedSet, NSString;

@interface SBHardwareButtonService : NSObject <SBSystemServiceServerHardwareButtonDelegate>
{
    FBServiceClientAuthenticator *_serviceClientHomeHardwareButtonHintSuppressionEntitlementAuthenticator;
    FBServiceClientAuthenticator *_serviceClientEventConsumerEntitlement;
    NSMutableOrderedSet *_homeButtonClients;
    NSMutableOrderedSet *_lockButtonClients;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_addClientInfo:(id)arg1 buttonKind:(long long)arg2;
- (id)_clientsForButtonKind:(long long)arg1;
- (_Bool)_hasNonSuspendedClientsInSet:(id)arg1;
- (id)_init;
- (id)_mutableClientsForButtonKind:(long long)arg1;
- (id)_mutableClientsForButtonKind:(long long)arg1 createIfNecessary:(_Bool)arg2;
- (void)_removeClientInfo:(id)arg1 buttonKind:(long long)arg2;
- (_Bool)_sendEvent:(long long)arg1 buttonKind:(long long)arg2 withPriority:(long long)arg3;
- (_Bool)_sendXPCMessageForEvent:(long long)arg1 buttonKind:(long long)arg2 priority:(long long)arg3 toClient:(id)arg4;
- (void)_setSystemServiceClient:(id)arg1 buttonKind:(long long)arg2 eventMask:(unsigned long long)arg3 priority:(long long)arg4;
- (_Bool)consumeHomeButtonDoublePressDownWithPriority:(long long)arg1;
- (_Bool)consumeHomeButtonLongPressWithPriority:(long long)arg1;
- (_Bool)consumeHomeButtonSinglePressUpWithPriority:(long long)arg1;
- (_Bool)consumeHomeButtonTriplePressUpWithPriority:(long long)arg1;
- (_Bool)consumeLockButtonDoublePressUpWithPriority:(long long)arg1;
- (_Bool)consumeLockButtonLongPressWithPriority:(long long)arg1;
- (_Bool)consumeLockButtonSinglePressUpWithPriority:(long long)arg1;
- (_Bool)hasConsumersForHomeButtonPresses;
- (_Bool)hasConsumersForHomeButtonSinglePress;
- (_Bool)hasConsumersForLockButtonPresses;
@property(retain, nonatomic) NSMutableOrderedSet *homeButtonClients; // @synthesize homeButtonClients=_homeButtonClients;
- (id)init;
@property(retain, nonatomic) NSMutableOrderedSet *lockButtonClients; // @synthesize lockButtonClients=_lockButtonClients;
- (void)systemServiceServer:(id)arg1 client:(id)arg2 acquireAssertionOfType:(long long)arg3 forReason:(id)arg4 withCompletion:(CDUnknownBlockType)arg5;
- (void)systemServiceServer:(id)arg1 client:(id)arg2 fetchHapticTypeForButtonKind:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)systemServiceServer:(id)arg1 client:(id)arg2 setEventMask:(unsigned long long)arg3 buttonKind:(long long)arg4 priority:(long long)arg5;
- (void)systemServiceServer:(id)arg1 client:(id)arg2 setHapticType:(long long)arg3 buttonKind:(long long)arg4;
- (void)systemServiceServer:(id)arg1 clientDidDisconnect:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

