//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSMutableArray, NSString, SBHomeGestureParticipant;

@interface SBHomeGestureArbiter : NSObject <BSDescriptionProviding>
{
    id <BSInvalidatable> _stateCaptureHandle;
    NSMutableArray *_participants;
    SBHomeGestureParticipant *_owningParticipant;
    SBHomeGestureParticipant *_hardwareButtonServiceParticipant;
}

- (void).cxx_destruct;
- (void)_registerParticipant:(id)arg1;
- (void)_unregisterParticipant:(id)arg1;
- (void)_updateHardwareButtonServiceParticipant;
- (void)_updateOwningParticipant;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(retain, nonatomic) SBHomeGestureParticipant *hardwareButtonServiceParticipant; // @synthesize hardwareButtonServiceParticipant=_hardwareButtonServiceParticipant;
- (id)init;
@property(retain, nonatomic) SBHomeGestureParticipant *owningParticipant; // @synthesize owningParticipant=_owningParticipant;
- (id)participantWithIdentifier:(long long)arg1 delegate:(id)arg2;
@property(retain, nonatomic) NSMutableArray *participants; // @synthesize participants=_participants;
@property(retain, nonatomic) id <BSInvalidatable> stateCaptureHandle; // @synthesize stateCaptureHandle=_stateCaptureHandle;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

