//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBIconModelStore.h"

@class NSDictionary, NSString;

@interface SBIconModelMemoryStore : NSObject <SBIconModelStore>
{
    NSDictionary *_currentState;
    NSDictionary *_desiredState;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *currentState; // @synthesize currentState=_currentState;
- (_Bool)deleteCurrentIconState:(id *)arg1;
- (_Bool)deleteDesiredIconState:(id *)arg1;
@property(copy, nonatomic) NSDictionary *desiredState; // @synthesize desiredState=_desiredState;
- (id)init;
- (id)initWithCurrentState:(id)arg1 desiredState:(id)arg2;
- (id)initWithITunesRepresentation:(id)arg1;
- (id)loadCurrentIconState:(id *)arg1;
- (id)loadDesiredIconState:(id *)arg1;
- (_Bool)saveCurrentIconState:(id)arg1 error:(id *)arg2;
- (_Bool)saveDesiredIconState:(id)arg1 error:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

