//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "BSDescriptionProviding.h"
#import "SBIconObserver.h"
#import "SBIconProgressViewDelegate.h"
#import "SBReusableView.h"

@class NSString, SBIcon, SBIconProgressView, SBIconView, UIImage, UIImageView;

@interface SBIconImageView : UIView <SBIconObserver, SBIconProgressViewDelegate, SBReusableView, BSDescriptionProviding>
{
    SBIcon *_icon;
    double _brightness;
    long long _location;
    UIImageView *_overlayView;
    SBIconProgressView *_progressView;
    UIImage *_cachedSquareContentsImage;
    _Bool _paused;
    _Bool _showsSquareCorners;
    _Bool _jittering;
    SBIconView *_iconView;
    double _overlayAlpha;
}

+ (double)cornerRadius;
+ (id)dequeueRecycledIconImageViewOfClass:(Class)arg1;
+ (void)recycleIconImageView:(id)arg1;
+ (id)viewMap;
+ (unsigned long long)viewMap:(id)arg1 maxRecycledViewsOfClass:(Class)arg2;
+ (id)windowForRecycledViewsInViewMap:(id)arg1;
- (void).cxx_destruct;
- (void)_clearProgressView;
- (id)_currentOverlayImage;
- (void)_didReceiveLowMemoryWarning:(id)arg1;
- (id)_generateIconBasicOverlayImageForFormat:(int)arg1;
- (id)_generateIconSquareOverlayImageForFormat:(int)arg1;
- (id)_generateSquareContentsImage;
- (id)_iconBasicOverlayImage;
- (id)_iconSquareOverlayImage;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_updateOverlayAlpha;
- (void)_updateOverlayImage;
- (void)_updateProgressMask;
@property(nonatomic) double brightness; // @synthesize brightness=_brightness;
- (void)clearCachedImages;
- (id)contentsImage;
- (id)darkeningOverlayImage;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, nonatomic) SBIcon *icon; // @synthesize icon=_icon;
- (void)iconImageDidUpdate:(id)arg1;
@property(nonatomic) __weak SBIconView *iconView; // @synthesize iconView=_iconView;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isJittering) _Bool jittering; // @synthesize jittering=_jittering;
@property(nonatomic, getter=isPaused) _Bool paused; // @synthesize paused=_paused;
- (void)layoutSubviews;
@property(nonatomic) double overlayAlpha; // @synthesize overlayAlpha=_overlayAlpha;
- (void)prepareForReuse;
- (void)progressViewCanBeRemoved:(id)arg1;
- (void)setIcon:(id)arg1 location:(long long)arg2 animated:(_Bool)arg3;
- (void)setProgressAlpha:(double)arg1;
- (void)setProgressState:(long long)arg1 paused:(_Bool)arg2 percent:(double)arg3 animated:(_Bool)arg4;
@property(nonatomic) _Bool showsSquareCorners; // @synthesize showsSquareCorners=_showsSquareCorners;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)snapshot;
- (id)squareContentsImage;
- (id)squareDarkeningOverlayImage;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (void)updateImageAnimated:(_Bool)arg1;
- (struct CGRect)visibleBounds;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

