//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSArray, NSCountedSet, NSDate, NSMapTable, NSMutableDictionary, NSMutableSet, NSSet, NSString, NSTimer, SBIconView, SBPlaceholderIcon;

@interface SBIconDragContext : NSObject <BSDescriptionProviding>
{
    NSMutableSet *_sourceIconViews;
    NSMapTable *_iconToExpandAfterDropAnimation;
    NSMutableSet *_destinationIconViews;
    NSCountedSet *_messageExpectations;
    NSMutableSet *_enteredIconListViews;
    NSMapTable *_targetsForCancellingIconViews;
    NSMapTable *_dragPreviewForIconViews;
    NSMutableSet *_appLocalContexts;
    NSMutableDictionary *_destinationFolderIconViews;
    NSMutableSet *_dropAnimatingDragItems;
    NSMutableDictionary *_initialIconPaths;
    _Bool _performedIconDrop;
    _Bool _cancelled;
    long long _state;
    SBPlaceholderIcon *_iconPlaceholder;
    NSArray *_grabbedIconViews;
    NSSet *_itemIdentifiers;
    NSSet *_sourceIcons;
    SBIconView *_primaryIconView;
    SBIconView *_recipientIconView;
    NSDate *_lastUserInteractionDate;
    NSTimer *_watchdogTimer;
}

- (void).cxx_destruct;
- (void)addAppLocalContext:(id)arg1;
- (void)addDestinationIconView:(id)arg1;
- (void)addDropAnimatingDragItem:(id)arg1;
- (void)addEnteredIconListView:(id)arg1;
- (void)addGrabbedIconView:(id)arg1;
- (void)addItemIdentifier:(id)arg1;
- (void)addMessageExpectationNamed:(id)arg1;
- (void)addSourceIcon:(id)arg1;
- (void)addSourceIconView:(id)arg1;
- (void)addSourceIcons:(id)arg1;
@property(readonly, copy, nonatomic) NSSet *appLocalContexts;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)destinationFolderIconViewForIconWithIdentifier:(id)arg1;
- (void)enumerateDestinationIconViewsUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateDragPreviewsUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateSourceIconViewsUsingBlock:(CDUnknownBlockType)arg1;
@property(readonly, copy, nonatomic) NSSet *expectedMessages;
@property(copy, nonatomic) NSArray *grabbedIconViews; // @synthesize grabbedIconViews=_grabbedIconViews;
- (_Bool)hasEnteredIconListView:(id)arg1;
- (_Bool)hasItemIdentifier:(id)arg1;
- (_Bool)hasMessageExpectationNamed:(id)arg1;
- (_Bool)hasSourceIconView:(id)arg1;
@property(readonly, nonatomic) _Bool hasUserDragged;
@property(retain, nonatomic) SBPlaceholderIcon *iconPlaceholder; // @synthesize iconPlaceholder=_iconPlaceholder;
- (id)iconToExpandAfterDropAnimationForDragItem:(id)arg1;
- (id)init;
- (id)initialIndexPathForIcon:(id)arg1;
- (id)initialIndexPathForIconWithIdentifier:(id)arg1;
- (_Bool)isAnimatingDropForDragItem:(id)arg1;
@property(nonatomic, getter=isCancelled) _Bool cancelled; // @synthesize cancelled=_cancelled;
@property(readonly, nonatomic, getter=isUserActive) _Bool userActive;
@property(readonly, nonatomic, getter=isWaitingForMessage) _Bool waitingForMessage;
@property(copy, nonatomic) NSSet *itemIdentifiers; // @synthesize itemIdentifiers=_itemIdentifiers;
@property(copy, nonatomic) NSDate *lastUserInteractionDate; // @synthesize lastUserInteractionDate=_lastUserInteractionDate;
@property(nonatomic) _Bool performedIconDrop; // @synthesize performedIconDrop=_performedIconDrop;
@property(retain, nonatomic) SBIconView *primaryIconView; // @synthesize primaryIconView=_primaryIconView;
@property(retain, nonatomic) SBIconView *recipientIconView; // @synthesize recipientIconView=_recipientIconView;
- (void)removeAllMessageExpectations;
- (void)removeMessageExpectationNamed:(id)arg1;
- (void)resetLastUserInteractionDate;
- (void)setDestinationFolderIconView:(id)arg1 forIconWithIdentifier:(id)arg2;
- (void)setDragPreview:(id)arg1 forIconView:(id)arg2;
- (void)setIcon:(id)arg1 shouldExpandAfterDropAnimationForDragItems:(id)arg2;
- (void)setInitialIndexPath:(id)arg1 forIcon:(id)arg2;
@property(copy, nonatomic) NSSet *sourceIcons; // @synthesize sourceIcons=_sourceIcons;
@property(nonatomic) long long state; // @synthesize state=_state;
- (void)setTargetIconView:(id)arg1 forCancellingIconView:(id)arg2;
@property(retain, nonatomic) NSTimer *watchdogTimer; // @synthesize watchdogTimer=_watchdogTimer;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (void)swapSourceIcon:(id)arg1 withIcon:(id)arg2;
- (id)targetIconViewForCancellingIconView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

