//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBIdleTimer.h"
#import "SBIdleTimerActivation.h"

@class NSHashTable, NSString;

@interface SBIdleTimerBase : NSObject <SBIdleTimerActivation, SBIdleTimer>
{
    NSHashTable *_observers;
}

- (void).cxx_destruct;
- (void)_enumerateObserversRespondingToSelector:(SEL)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)_makeObserversPerformSelector:(SEL)arg1;
- (void)addIdleTimerObserver:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly) unsigned long long hash;
@property(nonatomic, getter=isActivated) _Bool activated;
@property(readonly, nonatomic, getter=isDisabled) _Bool disabled;
- (_Bool)isEqualToTimer:(id)arg1;
@property(readonly, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
- (void)removeAllIdleTimerObservers;
- (void)removeIdleTimerObserver:(id)arg1;
- (void)reset;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

