//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "SBLayoutElementDescriptor.h"
#import "SBWorkspaceEntityGenerating.h"

@class NSString;

@interface SBLayoutElement : NSObject <BSDescriptionProviding, SBLayoutElementDescriptor, SBWorkspaceEntityGenerating>
{
    NSString *_identifier;
    long long _layoutRole;
    unsigned long long _layoutElementMode;
    unsigned long long _supportedLayoutRoles;
    unsigned long long _layoutAttributes;
    Class _viewControllerClass;
    CDUnknownBlockType _entityGenerator;
}

+ (id)elementWithDescriptor:(id)arg1;
+ (id)elementWithDescriptor:(id)arg1 layoutRole:(long long)arg2;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType entityGenerator; // @synthesize entityGenerator=_entityGenerator;
- (_Bool)hasLayoutAttributes:(unsigned long long)arg1;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSString *identifier;
- (id)initWithIdentifier:(id)arg1 layoutRole:(long long)arg2 layoutElementMode:(unsigned long long)arg3 supportedLayoutRoles:(unsigned long long)arg4 layoutAttributes:(unsigned long long)arg5 viewControllerClass:(Class)arg6 entityGenerator:(CDUnknownBlockType)arg7;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) unsigned long long layoutAttributes;
@property(readonly, nonatomic) unsigned long long layoutElementMode;
@property(readonly, nonatomic) long long layoutRole;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
@property(readonly, nonatomic) unsigned long long supportedLayoutRoles;
- (_Bool)supportsLayoutRole:(long long)arg1;
@property(readonly, nonatomic) Class viewControllerClass;
- (id)workspaceEntity;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

