//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"

@class NSSet, NSString;

@interface SBLayoutState : NSObject <BSDescriptionProviding>
{
    long long _interfaceOrientation;
    long long _elementInterfaceOrientation;
    NSSet *_elements;
}

+ (long long)_defaultInterfaceOrientation;
- (void).cxx_destruct;
- (id)_initWithLayoutElements:(id)arg1 interfaceOrientation:(long long)arg2 elementInterfaceOrientation:(long long)arg3;
- (id)appLayout;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, nonatomic) long long elementInterfaceOrientation;
- (id)elementWithIdentifier:(id)arg1;
- (id)elementWithRole:(long long)arg1;
@property(readonly, nonatomic) NSSet *elements; // @synthesize elements=_elements;
@property(readonly) unsigned long long hash;
- (id)init;
@property(readonly, nonatomic) long long interfaceOrientation;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqual:(id)arg1 withRole:(long long)arg2;
- (_Bool)layoutContainsRole:(long long)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

