//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, SBFloatingApplicationLayoutStateNode, SBLayoutState, SBWorkspaceApplicationSceneTransitionContext, SBWorkspaceTransaction;

@interface SBLayoutStateTransitionContext : NSObject
{
    _Bool _complete;
    _Bool _animationsDisabled;
    SBLayoutState *_fromLayoutState;
    SBLayoutState *_toLayoutState;
    NSError *_error;
    SBWorkspaceApplicationSceneTransitionContext *_applicationTransitionContext;
    SBWorkspaceTransaction *_workspaceTransaction;
    SBFloatingApplicationLayoutStateNode *_mostRecentFloatingApplicationState;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool animationsDisabled; // @synthesize animationsDisabled=_animationsDisabled;
@property(readonly, nonatomic) __weak SBWorkspaceApplicationSceneTransitionContext *applicationTransitionContext; // @synthesize applicationTransitionContext=_applicationTransitionContext;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) SBLayoutState *fromLayoutState; // @synthesize fromLayoutState=_fromLayoutState;
- (id)init;
- (id)initWithWorkspaceTransaction:(id)arg1;
@property(readonly, nonatomic, getter=isComplete) _Bool complete; // @synthesize complete=_complete;
@property(readonly, nonatomic, getter=isInterrupted) _Bool interrupted;
@property(readonly, nonatomic) SBFloatingApplicationLayoutStateNode *mostRecentFloatingApplicationState; // @synthesize mostRecentFloatingApplicationState=_mostRecentFloatingApplicationState;
@property(readonly, nonatomic) SBLayoutState *toLayoutState; // @synthesize toLayoutState=_toLayoutState;
- (void)transitionCompletedWithError:(id)arg1;
@property(readonly, nonatomic) __weak SBWorkspaceTransaction *workspaceTransaction; // @synthesize workspaceTransaction=_workspaceTransaction;

@end

