//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIconImageView.h"

@interface SBLiveIconImageView : SBIconImageView
{
}

- (_Bool)isAnimationAllowed;
- (void)prepareForReuse;
- (void)setIcon:(id)arg1 location:(long long)arg2 animated:(_Bool)arg3;
- (void)setPaused:(_Bool)arg1;
- (id)snapshot;
- (void)updateAnimatingState;
- (void)updateImageAnimated:(_Bool)arg1;
- (void)updateUnanimated;

@end

