//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSInvalidatable.h"
#import "SBDashBoardExternalEventHandling.h"
#import "SBLiftToWakeObserver.h"

@class NSString, SBBacklightController, SBIdleTimerGlobalCoordinator, SBLiftToWakeController, SBLockScreenManager, SBMainDisplayPolicyAggregator;

@interface SBLiftToWakeManager : NSObject <SBDashBoardExternalEventHandling, SBLiftToWakeObserver, BSInvalidatable>
{
    SBLiftToWakeController *_liftToWakeController;
    SBLockScreenManager *_accessor_lockScreenManager;
    SBBacklightController *_accessor_backlightController;
    SBMainDisplayPolicyAggregator *_accessor_policyAggregator;
    SBIdleTimerGlobalCoordinator *_accessor_idleTimerCoordinator;
    _Bool _gestureWokeScreen;
    _Bool _observing;
    _Bool _significantUserInteractionOccuredSinceWake;
    _Bool _invalidated;
}

- (void).cxx_destruct;
@property(retain, nonatomic, getter=_backlightController, setter=_setBacklightController:) SBBacklightController *backlightController; // @synthesize backlightController=_accessor_backlightController;
- (void)_backlightWillTurnOn:(id)arg1;
@property(nonatomic, getter=_gestureWokeScreen, setter=_setGestureWokeScreen:) _Bool gestureWokeScreen; // @synthesize gestureWokeScreen=_gestureWokeScreen;
@property(retain, nonatomic, getter=_idleTimerCoordinator, setter=_setIdleTimerCoordinator:) SBIdleTimerGlobalCoordinator *idleTimerCoordinator; // @synthesize idleTimerCoordinator=_accessor_idleTimerCoordinator;
- (void)_ignoredTransition:(long long)arg1;
- (id)_initWithLiftToWakeController:(id)arg1;
- (_Bool)_isLockScreenMainPageVisible;
@property(retain, nonatomic, getter=_liftToWakeController, setter=_setLiftToWakeController:) SBLiftToWakeController *liftToWakeController; // @synthesize liftToWakeController=_liftToWakeController;
@property(retain, nonatomic, getter=_lockScreenManager, setter=_setLockScreenManager:) SBLockScreenManager *lockScreenManager; // @synthesize lockScreenManager=_accessor_lockScreenManager;
@property(retain, nonatomic, getter=_policyAggregator, setter=_setPolicyAggregator:) SBMainDisplayPolicyAggregator *policyAggregator; // @synthesize policyAggregator=_accessor_policyAggregator;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (_Bool)handleEvent:(id)arg1;
- (id)init;
- (void)invalidate;
- (void)liftToWakeController:(id)arg1 didObserveTransition:(long long)arg2;
@property(readonly, nonatomic) long long participantState;
- (_Bool)wouldHandleButtonEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

