//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "_UISettingsKeyObserver.h"

@class NSString, PCPersistentTimer, SBLockScreenSettings, SBMediaController;

@interface SBLockScreenNowPlayingController : NSObject <_UISettingsKeyObserver>
{
    SBMediaController *_mediaController;
    PCPersistentTimer *_disableTimer;
    SBLockScreenSettings *_testSettings;
    _Bool _enabled;
    long long _currentState;
    id <SBLockScreenNowPlayingControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_addObservers;
- (void)_disableTimerFired;
- (void)_invalidateDisableTimer;
- (_Bool)_isMediaRecentlyActive;
- (void)_removeObservers;
- (void)_startDisableTimer;
- (double)_timeoutInterval;
- (void)_updateNowPlayingPlugin;
- (void)_updateToState:(long long)arg1;
@property(readonly, nonatomic) long long currentState; // @synthesize currentState=_currentState;
- (void)dealloc;
@property(nonatomic) __weak id <SBLockScreenNowPlayingControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithMediaController:(id)arg1;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (_Bool)isNowPlayingActive;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

