//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBProcessObserver.h"
#import "SBLockScreenPluginAgent.h"
#import "SBLockScreenPluginController.h"

@class BSPluginBundle, FBProcess, NSMutableArray, NSString, SBDashBoardAppearance, SBDashBoardBehavior, SBLockOverlayContext, SBLockScreenPluginAction, SBLockScreenPluginAppearanceContext, UIViewController<SBLockScreenPluginViewController>, _UILegibilitySettings;

@interface SBLockScreenPlugin : NSObject <FBProcessObserver, SBLockScreenPluginAgent, SBLockScreenPluginController>
{
    BSPluginBundle *_bundle;
    NSString *_bundleName;
    FBProcess *_process;
    id <SBLockScreenPluginController> _controller;
    id <SBLockScreenPluginAgent> _agent;
    SBLockScreenPluginAppearanceContext *_appearance;
    NSMutableArray *_lifecycleObservers;
    SBLockOverlayContext *_overlay;
    CDUnknownBlockType _auxiliaryActivationAnimationBlock;
    CDUnknownBlockType _auxiliaryDeactivationAnimationBlock;
    id <SBLockScreenPluginDelegate> _delegate;
}

+ (id)_pluginBundleForPluginWithName:(id)arg1;
+ (id)pluginWithName:(id)arg1 activationContext:(id)arg2;
- (void).cxx_destruct;
- (void)_updateAppearance:(id)arg1;
- (void)activatePluginController:(id)arg1;
- (void)addLifecycleObserver:(id)arg1;
@property(readonly, nonatomic) SBLockScreenPluginAppearanceContext *appearance;
@property(copy, nonatomic) CDUnknownBlockType auxiliaryActivationAnimationBlock; // @synthesize auxiliaryActivationAnimationBlock=_auxiliaryActivationAnimationBlock;
@property(copy, nonatomic) CDUnknownBlockType auxiliaryDeactivationAnimationBlock; // @synthesize auxiliaryDeactivationAnimationBlock=_auxiliaryDeactivationAnimationBlock;
@property(readonly, nonatomic) id <SBLockScreenPluginController> controller; // @synthesize controller=_controller;
@property(readonly, nonatomic) SBDashBoardAppearance *dashBoardAppearance;
@property(readonly, nonatomic) SBDashBoardBehavior *dashBoardBehavior;
- (void)deactivatePluginController:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <SBLockScreenPluginDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)enumerateLifecycleObserversUsingBlock:(CDUnknownBlockType)arg1;
- (_Bool)handleDashBoardEvent:(id)arg1;
- (id)initWithBundle:(id)arg1 activationContext:(id)arg2;
- (_Bool)isCapabilityRestricted:(unsigned long long)arg1;
- (_Bool)isElementHidden:(long long)arg1;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_bundleName;
@property(retain, nonatomic) SBLockOverlayContext *overlay; // @synthesize overlay=_overlay;
- (id)overrideForElement:(long long)arg1;
@property(nonatomic) __weak id <SBLockScreenPluginAgent> pluginAgent; // @synthesize pluginAgent=_agent;
@property(readonly, nonatomic) id <SBLockScreenPluginAppearance> pluginAppearance;
- (_Bool)pluginController:(id)arg1 sendAction:(id)arg2;
- (void)pluginController:(id)arg1 updateAppearance:(id)arg2;
- (void)pluginDidDeactivateWithContext:(id)arg1;
- (_Bool)pluginHandleEvent:(long long)arg1;
@property(readonly, nonatomic) long long pluginPriority;
@property(readonly, retain, nonatomic) SBLockScreenPluginAction *pluginUnlockAction;
@property(readonly, nonatomic) UIViewController<SBLockScreenPluginViewController> *pluginViewController;
- (void)pluginWillActivateWithContext:(id)arg1;
- (void)processDidExit:(id)arg1;
- (void)removeLifecycleObserver:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
@property(readonly, nonatomic) SBLockScreenPluginAction *unlockAction;
@property(readonly, nonatomic) UIViewController<SBLockScreenPluginViewController> *viewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly) Class superclass;

@end

