//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

@class NSMutableArray, NSTimer, SBLockScreenBatteryChargingView;

@interface SBLockScreenBatteryChargingViewController : SBDashBoardViewControllerBase
{
    _Bool _shouldDisplayBattery;
    SBLockScreenBatteryChargingView *_chargingView;
    NSTimer *_visibilityTimer;
    NSMutableArray *_connectedDevices;
    id <SBLockScreenBatteryChargingViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_clearVisibilityTimer;
- (void)_visibilityTimerFired:(id)arg1;
- (_Bool)batteryVisible;
- (id)chargingView;
- (void)dealloc;
@property(nonatomic) __weak id <SBLockScreenBatteryChargingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initForDisplayOfBattery:(_Bool)arg1;
- (void)loadView;
- (void)prepareForDismissalWithAnimation:(_Bool)arg1;
- (void)presentWithAnimation:(_Bool)arg1;
- (long long)presentationStyle;
- (void)showChargeLevelWithBatteryVisible:(_Bool)arg1;

@end

