//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SBDateTimeOverrideObserver.h"
#import "_UISettingsKeyObserver.h"

@class NSString, _UILegibilitySettings;

@interface SBLockScreenDateViewController : UIViewController <SBDateTimeOverrideObserver, _UISettingsKeyObserver>
{
    struct NSNumber *_timerToken;
    _Bool _isScreenOn;
    _Bool _isVisible;
    _Bool _disablesUpdates;
    _UILegibilitySettings *_legibilitySettings;
}

- (void).cxx_destruct;
- (void)_addObservers;
- (void)_backlightChanged:(id)arg1;
- (void)_startUpdateTimer;
- (void)_stopUpdateTimer;
- (void)_updateFormat;
- (void)_updateLegibilityStrength;
- (void)_updateState;
- (void)_updateView;
- (void)controller:(id)arg1 didChangeOverrideDateFromDate:(id)arg2;
- (id)dateView;
- (id)dateViewIfExists;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, getter=isSubtitleHidden) _Bool subtitleHidden;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
- (void)loadView;
- (void)setContentAlpha:(double)arg1 withSubtitleVisible:(_Bool)arg2;
- (void)setCustomSubtitleView:(id)arg1;
- (void)setView:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)updateTimeNow;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willMoveToParentViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

