//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SBDashBoardPageControl, SBFLockScreenDateView, SBUICallToActionLabel, SBUILegibilityView, SBWallpaperController, UILabel, UIStatusBar, _UILegibilityLabel, _UILegibilitySettings;

@interface SBLockScreenPreviewView : UIView
{
    UIView *_wallpaperView;
    SBFLockScreenDateView *_dateView;
    _UILegibilityLabel *_slideToUnlockLegibilityLabel;
    UIStatusBar *_statusBar;
    _UILegibilitySettings *_legibilitySettings;
    SBWallpaperController *_wallpaperController;
    SBUILegibilityView *_cameraView;
    UILabel *_slideToUnlockView;
    SBDashBoardPageControl *_dashBoardPageControl;
    SBUICallToActionLabel *_callToActionLabel;
}

- (void).cxx_destruct;
- (void)_layoutCallToActionLabel;
- (void)_layoutDateView;
- (void)_layoutPageControl;
- (void)_layoutStatusBar;
- (void)_layoutWallpaperView;
- (id)_legibilityPrototypeSettings;
- (void)_setupCallToActionLabel;
- (void)_setupDateViewWithOptions:(unsigned long long)arg1;
- (void)_setupPageControl;
- (void)_setupStatusBar;
- (void)_setupWallpaperView;
- (id)initWithFrame:(struct CGRect)arg1 wallpaperController:(id)arg2 options:(unsigned long long)arg3;
- (void)layoutSubviews;

@end

