//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class FBSProcessHandle, NSString, SBApplication;

@interface SBLockScreenUnlockRequest : NSObject <NSCopying>
{
    _Bool _wantsBiometricPresentation;
    int _source;
    int _intent;
    NSString *_name;
    FBSProcessHandle *_process;
    SBApplication *_destinationApplication;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
@property(retain, nonatomic) SBApplication *destinationApplication; // @synthesize destinationApplication=_destinationApplication;
- (unsigned long long)hash;
@property(nonatomic) int intent; // @synthesize intent=_intent;
- (_Bool)isEqual:(id)arg1;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) FBSProcessHandle *process; // @synthesize process=_process;
@property(nonatomic) int source; // @synthesize source=_source;
@property(nonatomic) _Bool wantsBiometricPresentation; // @synthesize wantsBiometricPresentation=_wantsBiometricPresentation;

@end

