//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBLockScreenViewControllerBase.h"

#import "SBLockScreenBatteryChargingViewControllerDelegate.h"
#import "SBLockScreenPluginManagerDelegate.h"
#import "SBLoginAppSceneHosterDelegate.h"
#import "SBWallpaperObserver.h"

@class NSHashTable, NSMutableSet, NSString, SBAppStatusBarSettingsAssertion, SBLockScreenBatteryChargingViewController, SBLockScreenPluginManager, SBLockScreenTemperatureWarningViewController, SBLoginAppContainerPluginWrapperViewController, SBWallpaperController;

@interface SBLoginAppContainerViewController : SBLockScreenViewControllerBase <SBLockScreenBatteryChargingViewControllerDelegate, SBLoginAppSceneHosterDelegate, SBWallpaperObserver, SBLockScreenPluginManagerDelegate>
{
    id <SBLoginAppSceneHoster> _sceneHoster;
    SBLockScreenBatteryChargingViewController *_batteryChargingViewController;
    SBLockScreenTemperatureWarningViewController *_thermalWarningViewController;
    SBLoginAppContainerPluginWrapperViewController *_pluginWrapperViewController;
    SBAppStatusBarSettingsAssertion *_statusBarAssertion;
    NSMutableSet *_showStatusBarReasons;
    long long _idleTimerMode;
    SBLockScreenPluginManager *_pluginManager;
    SBWallpaperController *_wallpaperController;
    NSHashTable *_observers;
}

- (void).cxx_destruct;
- (void)_addBatteryChargingView;
- (void)_cleanupBatteryChargingViewWithAnimationDuration:(double)arg1;
- (id)_displayLayoutElementIdentifier;
- (void)_fadeViewsForChargingViewVisible:(_Bool)arg1;
- (void)_handleBacklightFadeEnded;
- (void)_hideStatusBarForReason:(id)arg1;
- (id)_hostedAppBundleID;
- (id)_hostedAppView;
- (id)_hostedSceneIdentifier;
- (id)_initWithSceneHoster:(id)arg1 wallpaperController:(id)arg2;
- (void)_killLoginApp;
- (void)_reallyAcquireStatusBarAssertionIfNecessaryInitiallyVisible:(_Bool)arg1;
- (void)_reallyRelinquishStatusBarAssertion;
- (void)_removeBatteryChargingView;
- (void)_setupLoginAppHosting;
- (void)_setupLoginScene;
- (void)_showOrHideThermalTrapUIAnimated:(_Bool)arg1;
- (void)_showStatusBarForReason:(id)arg1;
- (id)_statusBarSettingsAssertion;
- (void)_updateBatteryChargingViewAnimated:(_Bool)arg1;
- (void)_updateLegibility;
- (void)addLoginObserver:(id)arg1;
- (_Bool)canBeDeactivatedForUIUnlockFromSource:(int)arg1;
- (void)chargingViewControllerFadedOutContent:(id)arg1;
- (id)coordinatorRequestedIdleTimerDescriptor:(id)arg1;
- (void)dealloc;
- (void)disableLockScreenPluginWithContext:(id)arg1;
- (void)enableLockScreenPluginWithContext:(id)arg1;
- (_Bool)handleHomeButtonDoublePress;
- (_Bool)handleVolumeDownButtonPress;
- (_Bool)handleVolumeUpButtonPress;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 sceneHoster:(id)arg3 wallpaperController:(id)arg4;
- (void)loadView;
- (id)loginContainerView;
- (void)noteDeviceBlockedStatusUpdated;
- (void)noteExitingLostMode;
- (void)pluginManager:(id)arg1 activePluginDidChange:(id)arg2;
- (void)pluginManager:(id)arg1 didLoadPlugin:(id)arg2;
- (void)pluginManager:(id)arg1 displayedPluginDidChangeFromPlugin:(id)arg2 toPlugin:(id)arg3;
- (void)pluginManager:(id)arg1 displayedPluginDidUpdateAppearance:(id)arg2;
- (_Bool)pluginManager:(id)arg1 plugin:(id)arg2 handleAction:(id)arg3;
- (void)pluginManager:(id)arg1 willUnloadPlugin:(id)arg2;
- (void)prepareForUILock;
- (void)prepareForUIUnlock;
- (void)prepareToEnterLostMode;
- (void)removeLoginObserver:(id)arg1;
- (_Bool)requiresPasscodeInputForUIUnlockFromSource:(int)arg1 withOptions:(id)arg2;
- (void)sceneDeactivatedWithError:(id)arg1;
- (void)sceneUpdatedIdleTimerMode:(long long)arg1;
- (void)sceneUpdatedRotationMode:(long long)arg1;
- (void)sceneUpdatedStatusBarUserName:(id)arg1;
- (_Bool)shouldAutoUnlockForSource:(int)arg1;
- (_Bool)shouldDisableALS;
- (_Bool)shouldShowLockStatusBarTime;
- (void)startLockScreenFadeInAnimationForSource:(int)arg1;
- (_Bool)suppressesControlCenter;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)wallpaperDidChangeForVariant:(long long)arg1;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(long long)arg2;
- (_Bool)wantsLockScreenIdleTimer;
- (_Bool)willUIUnlockFromSource:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

