//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "SBAlertObserver.h"
#import "SBCoverSheetPresentationDelegate.h"
#import "SBDashBoardViewControllerDelegate.h"
#import "SBFPrivateAuthenticationObserver.h"
#import "SBHomeButtonShowPasscodeRecognizerDelegate.h"
#import "SBHomeButtonSuppressAfterUnlockRecognizerDelegate.h"
#import "SBIdleTimerCoordinating.h"
#import "SBIdleTimerProviding.h"
#import "SBLockScreenBiometricAuthenticationCoordinatorDelegate.h"
#import "SBPasscodeEntryAlertViewControllerDelegate.h"
#import "SBTapToWakeDelegate.h"
#import "SBUILockStateProvider.h"
#import "SBWallpaperColorProvider.h"
#import "SBWallpaperObserver.h"

@class NSMutableDictionary, NSString, SBCoverSheetBiometricResourceObserver, SBDashBoardViewController, SBFAuthenticationAssertion, SBFUserAuthenticationController, SBIdleTimerCoordinatorHelper, SBLiftToWakeManager, SBLockScreenAutoUnlockAggregateRule, SBLockScreenBiometricAuthenticationCoordinator, SBLockScreenDisabledAssertionManager, SBLockScreenUnlockRequest, SBLockScreenViewControllerBase, SBPasscodeEntryAlertViewController, SBPearlInterlockObserver, SBTapToWakeController, UINotificationFeedbackGenerator;

@interface SBLockScreenManager : NSObject <BSDescriptionProviding, SBPasscodeEntryAlertViewControllerDelegate, SBAlertObserver, SBFPrivateAuthenticationObserver, SBDashBoardViewControllerDelegate, SBWallpaperColorProvider, SBLockScreenBiometricAuthenticationCoordinatorDelegate, SBHomeButtonShowPasscodeRecognizerDelegate, SBHomeButtonSuppressAfterUnlockRecognizerDelegate, SBWallpaperObserver, SBCoverSheetPresentationDelegate, SBUILockStateProvider, SBTapToWakeDelegate, SBIdleTimerProviding, SBIdleTimerCoordinating>
{
    SBLockScreenBiometricAuthenticationCoordinator *_biometricAuthenticationCoordinator;
    SBCoverSheetBiometricResourceObserver *_biometricResourceObserver;
    SBPearlInterlockObserver *_pearlInterlockObserver;
    SBLockScreenViewControllerBase *_lockScreenViewController;
    id <SBHomeButtonShowPasscodeRecognizer> _homeButtonShowPasscodeRecognizer;
    id <SBHomeButtonSuppressAfterUnlockRecognizer> _homeButtonSuppressAfterUnlockRecognizer;
    _Bool _allowDisablePasscodeLockAssertion;
    _Bool _allowUILockUnlock;
    _Bool _isScreenOn;
    _Bool _isUILocked;
    _Bool _isWaitingToLockUI;
    SBLockScreenUnlockRequest *_unlockRequest;
    _Bool _uiHasBeenLockedOnce;
    _Bool _uiUnlocking;
    SBPasscodeEntryAlertViewController *_passcodeEntryController;
    SBFAuthenticationAssertion *_sustainAuthenticationWhileUIUnlockedAssertion;
    SBLockScreenDisabledAssertionManager *_lockScreenDisabledAssertionManager;
    _Bool _isInLostMode;
    SBLockScreenAutoUnlockAggregateRule *_autoUnlockRuleAggregator;
    _Bool _shouldTransitionIrisWallpaperToStillWhenPlaybackFinishes;
    id <SBFLockOutStatusProvider> _lockOutController;
    SBFUserAuthenticationController *_userAuthController;
    SBLiftToWakeManager *_liftToWakeManager;
    SBTapToWakeController *_tapToWakeController;
    NSMutableDictionary *_mesaCoordinatorDisabledAssertions;
    NSMutableDictionary *_mesaWalletPreArmDisabledAssertions;
    NSMutableDictionary *_mesaAutoUnlockingDisabledAssertions;
    NSMutableDictionary *_mesaUnlockingDisabledAssertions;
    SBIdleTimerCoordinatorHelper *_idleTimerCoordinatorHelper;
    UINotificationFeedbackGenerator *_authenticationFeedbackGenerator;
    CDUnknownBlockType _unlockActionBlock;
}

+ (id)_sharedInstanceCreateIfNeeded:(_Bool)arg1;
+ (id)sharedInstance;
+ (id)sharedInstanceIfExists;
- (void).cxx_destruct;
- (void)_activateLockScreenAnimated:(_Bool)arg1 animationProvider:(CDUnknownBlockType)arg2 automatically:(_Bool)arg3 inScreenOffMode:(_Bool)arg4 dimInAnimation:(_Bool)arg5 dismissNotificationCenter:(_Bool)arg6 completion:(CDUnknownBlockType)arg7;
- (void)_activeCallStateChanged;
- (_Bool)_attemptUnlockWithPasscode:(id)arg1 finishUIUnlock:(_Bool)arg2;
- (_Bool)_attemptUnlockWithPasscode:(id)arg1 mesa:(_Bool)arg2 finishUIUnlock:(_Bool)arg3;
- (_Bool)_attemptUnlockWithPasscode:(id)arg1 mesa:(_Bool)arg2 finishUIUnlock:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_authenticationStateChanged:(id)arg1;
- (_Bool)_canAttemptRealUIUnlockIgnoringBacklightNonsenseWithReason:(out id *)arg1;
- (_Bool)_canHandleTransitionRequest:(id)arg1;
- (void)_clearAuthenticationLockAssertion;
- (void)_createAuthenticationAssertion;
- (void)_deviceBlockedChanged:(id)arg1;
- (void)_disconnectActiveCallIfNeededFromSource:(int)arg1;
- (void)_evaluatePreArmDisabledAssertions;
- (_Bool)_finishUIUnlockFromSource:(int)arg1 withOptions:(id)arg2;
- (void)_handleAuthenticationFeedback:(id)arg1;
- (void)_handleBacklightDidTurnOff:(id)arg1;
- (void)_handleBacklightLevelWillChange:(id)arg1;
- (_Bool)_isPasscodeVisible;
- (_Bool)_isUnlockDisabled;
@property(retain, nonatomic, getter=_liftToWakeManager, setter=_setLiftToWakeManager:) SBLiftToWakeManager *liftToWakeManager; // @synthesize liftToWakeManager=_liftToWakeManager;
- (void)_lockFeaturesForRemoteLock:(_Bool)arg1;
@property(retain, nonatomic, getter=_lockOutController, setter=_setLockOutController:) id <SBFLockOutStatusProvider> lockOutController; // @synthesize lockOutController=_lockOutController;
- (void)_lockScreenDimmed:(id)arg1;
- (_Bool)_lockUI;
- (void)_maybeLaunchSetupForcingCheckIfNotBricked:(_Bool)arg1;
- (id)_newLockScreenController;
- (void)_noteStartupTransitionDidBegin;
- (void)_noteStartupTransitionWillBegin;
- (void)_postLockCompletedNotification:(_Bool)arg1;
- (void)_prepareWallpaperForLockedMode;
- (void)_prepareWallpaperForUnlockedMode;
- (void)_reallySetUILocked:(_Bool)arg1;
- (void)_relockUIForButtonlikeSource:(int)arg1 afterCall:(_Bool)arg2;
- (void)_resetDashBoardInterfaceOrientationAnimated:(_Bool)arg1;
- (void)_resetOrRestoreStateChanged:(id)arg1;
- (void)_runUnlockActionBlock:(_Bool)arg1;
- (void)_sendUILockStateChangedNotification;
- (void)_setHomeButtonShowPasscodeRecognizer:(id)arg1;
- (void)_setHomeButtonSuppressAfterUnlockRecognizer:(id)arg1;
- (void)_setIdleTimerCoordinator:(id)arg1;
- (void)_setMesaAutoUnlockingDisabled:(_Bool)arg1 forReason:(id)arg2;
- (void)_setMesaCoordinatorDisabled:(_Bool)arg1 forReason:(id)arg2;
- (void)_setMesaUnlockingDisabled:(_Bool)arg1 forReason:(id)arg2;
- (_Bool)_setPasscodeVisible:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic, getter=_tapToWakeController, setter=_setTapToWakeController:) SBTapToWakeController *tapToWakeController; // @synthesize tapToWakeController=_tapToWakeController;
- (void)_setUILocked:(_Bool)arg1;
@property(retain, nonatomic, getter=_userAuthController, setter=_setUserAuthController:) SBFUserAuthenticationController *userAuthController; // @synthesize userAuthController=_userAuthController;
- (void)_setWalletPreArmDisabled:(_Bool)arg1 forReason:(id)arg2;
- (void)_setupModeChanged;
- (_Bool)_shouldBeInSetupMode;
- (_Bool)_shouldDisconnectCallWhenLockingForActiveAudioRoute;
- (_Bool)_shouldLockAfterEndingFaceTimeCall;
- (_Bool)_shouldLockAfterEndingTelephonyCall;
- (_Bool)_shouldUnlockUIOnKeyDownEvent;
- (_Bool)_unlockWithRequest:(id)arg1 cancelPendingRequests:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)activateLostModeForRemoteLock:(_Bool)arg1;
- (void)activationChanged:(id)arg1;
- (void)addLockScreenDisableAssertion:(id)arg1;
- (void)alertDidDeactivate:(id)arg1;
- (void)attemptUnlockWithMesa;
- (void)attemptUnlockWithPasscode:(id)arg1;
- (void)attemptUnlockWithPasscode:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)averageColorForCurrentWallpaperInScreenRect:(struct CGRect)arg1;
@property(readonly) _Bool bioAuthenticatedWhileMenuButtonDown;
- (id)biometricAuthenticationCoordinator;
- (_Bool)biometricAuthenticationCoordinator:(id)arg1 requestsAuthenticationFeedback:(id)arg2;
- (_Bool)biometricAuthenticationCoordinator:(id)arg1 requestsUnlockWithIntent:(int)arg2;
- (id)coordinatorRequestedIdleTimerDescriptor:(id)arg1;
- (void)coverSheetPresentationManager:(id)arg1 unlockWithRequest:(id)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) SBDashBoardViewController *dashBoardViewController;
- (void)dashBoardViewController:(id)arg1 requestsTouchIDDisabled:(_Bool)arg2 forReason:(id)arg3;
- (void)dashBoardViewController:(id)arg1 unlockWithRequest:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dashBoardViewControllerIrisPlayingDidFinish:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)enableLostModePlugin;
- (void)exitLostModeIfNecessaryFromRemoteRequest:(_Bool)arg1;
- (void)extendedKeybagLockStateChanged:(_Bool)arg1;
- (_Bool)handleKeyHIDEvent:(struct __IOHIDEvent *)arg1;
- (_Bool)handleTransitionRequest:(id)arg1;
- (_Bool)handlesHomeButtonSinglePresses;
- (_Bool)hasUIEverBeenLocked;
- (void)homeButtonShowPasscodeRecognizerDidFailToRecognize:(id)arg1;
- (void)homeButtonShowPasscodeRecognizerRequestsPasscodeUIToBeShown:(id)arg1;
- (void)homeButtonSuppressAfterUnlockRecognizerRequestsEndOfSuppression:(id)arg1;
- (id)idleTimerProvider:(id)arg1 didProposeDescriptor:(id)arg2 forReason:(id)arg3;
- (id)init;
- (_Bool)isInLostMode;
@property(readonly) _Bool isLockScreenActive;
- (_Bool)isLockScreenDisabledForAssertion;
@property(readonly) _Bool isLockScreenVisible;
- (_Bool)isPasscodeEntryAlertVisible;
@property(readonly) _Bool isUILocked; // @synthesize isUILocked=_isUILocked;
@property(nonatomic, getter=isUIUnlocking) _Bool UIUnlocking; // @synthesize UIUnlocking=_uiUnlocking;
@property(readonly) _Bool isWaitingToLockUI; // @synthesize isWaitingToLockUI=_isWaitingToLockUI;
- (void)loadViewsIfNeeded;
@property(readonly, nonatomic) SBLockScreenViewControllerBase *lockScreenViewController; // @synthesize lockScreenViewController=_lockScreenViewController;
- (void)lockScreenViewControllerDidDismiss;
- (void)lockScreenViewControllerDidPresent;
- (void)lockScreenViewControllerRequestsUnlock;
- (void)lockScreenViewControllerWillDismiss;
- (void)lockScreenViewControllerWillPresent;
- (void)lockUIFromSource:(int)arg1 withOptions:(id)arg2;
- (void)lockUIFromSource:(int)arg1 withOptions:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)noteMenuButtonDoublePress;
- (void)noteMenuButtonSinglePress;
@property(readonly, nonatomic) id <SBNotificationDestination> notificationDestination;
- (_Bool)passcodeEntryAlertViewController:(id)arg1 authenticatePasscode:(id)arg2;
- (void)passcodeEntryAlertViewControllerWantsEmergencyCall:(id)arg1;
- (void)remoteLock:(_Bool)arg1;
- (void)removeLockScreenDisableAssertion:(id)arg1;
- (void)setBiometricAutoUnlockingDisabled:(_Bool)arg1 forReason:(id)arg2;
- (void)setPasscodeVisible:(_Bool)arg1 animated:(_Bool)arg2;
@property(copy, nonatomic) CDUnknownBlockType unlockActionBlock; // @synthesize unlockActionBlock=_unlockActionBlock;
@property(readonly) _Bool shouldHandlePocketStateChanges;
- (_Bool)shouldLockUIAfterEndingCall;
@property(readonly) _Bool shouldPlayLockSound;
- (void)startUIUnlockFromSource:(int)arg1 withOptions:(id)arg2;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (void)tapToWakeControllerDidRecognizeWakeGesture:(id)arg1;
- (_Bool)unlockUIFromSource:(int)arg1 withOptions:(id)arg2;
- (_Bool)unlockWithRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateSpringBoardStatusBarForLockScreenTeardown;
- (void)wallpaperDidChangeForVariant:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

