//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBDashBoardViewControllerBase.h"

@class NSDate, NSTimer;

@interface SBLockScreenTimerViewController : SBDashBoardViewControllerBase
{
    _Bool _enabled;
    NSTimer *_updateTimer;
    NSDate *_endDate;
    id <SBLockScreenTimerViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_handleClockNotificationUpdate:(id)arg1;
- (void)_pendingNotificationRequestsDidChange:(id)arg1;
- (void)_scheduledTimerDidChange:(id)arg1;
- (void)_startTimer;
- (void)_stopTimer;
- (void)_stopTimerNotifyingDelegate:(_Bool)arg1;
- (void)_updateTimerFired;
- (void)_updateTimerLabelView;
- (void)dealloc;
@property(nonatomic) __weak id <SBLockScreenTimerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (_Bool)isEndDateValid;
- (_Bool)isTimerActive;
- (void)loadView;
- (void)setEndDate:(id)arg1;
- (id)timerView;

@end

