//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSceneManager.h"

#import "SBApplicationRestrictionObserver.h"
#import "SBFloatingApplicationControllerInternalDelegate.h"
#import "SBIdleTimerCoordinating.h"
#import "SBIdleTimerProviding.h"
#import "SBLayoutStateTransitionObserver.h"
#import "SBUnlockedEnvironmentWindowsProvider.h"

@class FBSSceneClientSettingsDiffInspector, NSArray, NSMutableArray, NSMutableSet, NSString, SBFaceContactExpectationManager, SBFloatingApplicationController, SBFloatingApplicationLayoutStateNode, SBMainDisplayLayoutState, SBMainDisplayLayoutStateManager, SBMainDisplayPolicyAggregator, SBMainDisplaySceneLayoutViewController, UIApplicationSceneClientSettingsDiffInspector, UISystemNavigationAction, UIWindow;

@interface SBMainDisplaySceneManager : SBSceneManager <SBApplicationRestrictionObserver, SBFloatingApplicationControllerInternalDelegate, SBLayoutStateTransitionObserver, SBIdleTimerCoordinating, SBUnlockedEnvironmentWindowsProvider, SBIdleTimerProviding>
{
    SBMainDisplayPolicyAggregator *_policyAggregator;
    SBFloatingApplicationController *_floatingApplicationController;
    UIApplicationSceneClientSettingsDiffInspector *_internalClientSettingsDiffInspector;
    UIApplicationSceneClientSettingsDiffInspector *_appClientSettingsDiffInspector;
    FBSSceneClientSettingsDiffInspector *_externalClientSettingsDiffInspector;
    long long _validInterfaceOrientation;
    unsigned long long _validInterfaceOrientationChangeCount;
    unsigned long long _processedValidInterfaceOrientationChangeCount;
    SBFaceContactExpectationManager *_faceContactExpectationManager;
    UIWindow *_floatingApplicationWindow;
    NSMutableSet *_requiredContextIdentifiersForMedusaDraggingDestination;
    _Bool _didAddSceneLayoutViewControllerWindowContextIdentifier;
    NSMutableArray *_windows;
    SBFloatingApplicationLayoutStateNode *_mostRecentFloatingApplicationState;
    id <SBIdleTimerCoordinating> _idleTimerCoordinator;
    UISystemNavigationAction *_currentBreadcrumbNavigationAction;
}

+ (Class)_applicationSceneHandleClass;
+ (Class)_layoutStateManagerClass;
+ (Class)_sceneLayoutWindowClass;
- (void).cxx_destruct;
- (void)_activateAppLink:(id)arg1 withAppLinkState:(id)arg2 transitionContext:(id)arg3 wasFromSpotlight:(_Bool)arg4 previousBreadcrumb:(id)arg5;
- (void)_activateBreadcrumbApplication:(id)arg1;
- (void)_addMedusaDraggingDestinationWindow:(id)arg1;
- (_Bool)_animateGeometryChangesForExternalForegroundApplicationScenes;
- (id)_appClientSettingsDiffInspector;
- (void)_appKilledInAppSwitcher:(id)arg1;
- (void)_application:(id)arg1 initiatedChangefromInterfaceOrientation:(long long)arg2 toInterfaceOrientation:(long long)arg3 scene:(id)arg4 sceneSettings:(id)arg5 transitionContext:(id)arg6;
- (void)_applicationDidExit:(id)arg1;
- (id)_breadcrumbBundleIdForApplicationSceneEntity:(id)arg1 withTransitionContext:(id)arg2;
- (id)_breadcrumbNavigationActionForApplicationSceneEntity:(id)arg1 withTransitionContext:(id)arg2;
- (id)_destinationContextsForApplicationSceneEntity:(id)arg1 withTransitionContext:(id)arg2;
- (void)_deviceOrientationChanged:(id)arg1;
- (double)_effectiveKeyboardSceneLevelForClientSettings:(id)arg1;
- (id)_externalClientSettingsDiffInspector;
- (id)_floatingApplicationWindow;
- (_Bool)_handleAction:(id)arg1 forScene:(id)arg2;
- (long long)_hostingPolicyForScene:(id)arg1;
- (id)_internalClientSettingsDiffInspector;
- (_Bool)_isActivatingPinnedBreadcrumbApplicationSceneEntity:(id)arg1 withTransitionContext:(id)arg2;
- (_Bool)_isExternalForegroundScene:(id)arg1;
@property(retain, nonatomic, setter=_setMostRecentFloatingApplicationState:) SBFloatingApplicationLayoutStateNode *_mostRecentFloatingApplicationState; // @synthesize _mostRecentFloatingApplicationState;
- (id)_newSceneLayoutViewController;
- (void)_noteDidChangeToVisibility:(unsigned long long)arg1 forScene:(id)arg2;
- (void)_noteDidCommitUpdateForScene:(id)arg1;
- (long long)_openStrategyForAppLinkState:(id)arg1;
- (void)_presentAssistantFromBreadcrumb;
- (void)_presentSpotlightFromSource:(unsigned long long)arg1 fromBreadcrumb:(_Bool)arg2;
- (id)_proposeIdleTimerDescriptorForReason:(id)arg1;
- (void)_removeMedusaDraggingDestinationWindow:(id)arg1;
- (void)_reorderWindows;
@property(readonly, nonatomic) NSArray *_requiredContextIdentifiersForMedusaDraggingDestination;
- (id)_rotationAnimationSettingsForRotationFromInterfaceOrientation:(long long)arg1 toInterfaceOrientation:(long long)arg2 medusaSettings:(id)arg3;
- (void)_scene:(id)arg1 didUpdateClientSettingsWithDiff:(id)arg2 oldClientSettings:(id)arg3 transitionContext:(id)arg4;
- (void)_scene:(id)arg1 willUpdateWithSettings:(id)arg2 transitionContext:(id)arg3;
- (void)_setupLayoutStateTransitionCoordinator:(id)arg1;
- (_Bool)_shouldBreadcrumbApplicationSceneEntity:(id)arg1 withTransitionContext:(id)arg2;
- (_Bool)_shouldFenceTransitionForScene:(id)arg1 updatedClientSettingsDiff:(id)arg2 oldClientSettings:(id)arg3 transitionContext:(id)arg4;
- (_Bool)_shouldRequestSnapshotActionsForScene:(id)arg1;
- (id)_snapshotRequestsForSceneHandle:(id)arg1 settings:(id)arg2;
- (void)_updateDeviceOrientation:(long long)arg1 ifNeededForScene:(id)arg2;
- (void)_updateExternalForegroundApplicationScenesToInterfaceOrientation:(long long)arg1 force:(_Bool)arg2;
- (void)_updateLevelAndBackgroundSettingsForScene:(id)arg1 transitionContext:(id)arg2;
- (void)_windowDidBecomeKey:(id)arg1;
- (void)addObserver:(id)arg1;
- (id)additionalActionsForApplicationSceneEntity:(id)arg1 withTransitionContext:(id)arg2;
- (void)applicationRestrictionController:(id)arg1 didUpdateVisibleTags:(id)arg2 hiddenTags:(id)arg3;
- (id)coordinatorRequestedIdleTimerDescriptor:(id)arg1;
@property(retain, nonatomic) UISystemNavigationAction *currentBreadcrumbNavigationAction; // @synthesize currentBreadcrumbNavigationAction=_currentBreadcrumbNavigationAction;
- (void)dealloc;
- (id)existingSceneHandleForScene:(id)arg1;
- (id)existingSceneHandleForSceneIdentity:(id)arg1;
- (id)externalApplicationSceneHandles;
- (id)externalForegroundApplicationSceneHandles;
- (id)fetchOrCreateApplicationSceneHandleForApplication:(id)arg1 withIdentity:(id)arg2;
@property(readonly, nonatomic) SBFloatingApplicationController *floatingApplicationController;
- (void)floatingApplicationController:(id)arg1 needsVisibleWindow:(_Bool)arg2;
@property(nonatomic) __weak id <SBIdleTimerCoordinating> idleTimerCoordinator; // @synthesize idleTimerCoordinator=_idleTimerCoordinator;
- (id)idleTimerProvider:(id)arg1 didProposeDescriptor:(id)arg2 forReason:(id)arg3;
- (id)initWithReference:(id)arg1;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidEndWithTransitionContext:(id)arg2;
@property(readonly, nonatomic) SBMainDisplayPolicyAggregator *policyAggregator;
- (void)registerWindow:(id)arg1;
- (void)removeObserver:(id)arg1;
- (id)sceneIdentityForApplication:(id)arg1;
- (void)sceneManager:(id)arg1 didDestroyScene:(id)arg2;
- (id)window;
@property(readonly, nonatomic) NSArray *windows;

// Remaining properties
@property(readonly, nonatomic) SBMainDisplayLayoutStateManager *_layoutStateManager; // @dynamic _layoutStateManager;
@property(readonly, nonatomic) SBMainDisplayLayoutState *currentLayoutState; // @dynamic currentLayoutState;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) SBMainDisplaySceneLayoutViewController *sceneLayoutViewController; // @dynamic sceneLayoutViewController;
@property(readonly) Class superclass;

@end

