//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSystemGestureWorkspaceTransaction.h"

@class SBFloatingApplicationRootViewController, SBMainWorkspaceApplicationSceneLayoutElementViewController, SBMainWorkspaceTransaction, UIPanGestureRecognizer;

@interface SBMoveFloatingApplicationPanSystemGestureRecognizerWorkspaceTransaction : SBSystemGestureWorkspaceTransaction
{
    long long _initialSpaceConfiguration;
    _Bool _tryPreemptiveFloatingApplicationActivation;
    _Bool _didAddActivationLayoutStateTransitionWorkspaceTransaction;
    SBMainWorkspaceApplicationSceneLayoutElementViewController *_primaryLayoutElementViewController;
    SBMainWorkspaceApplicationSceneLayoutElementViewController *_sideLayoutElementViewController;
    double _systemGestureRecognizerBeganValue;
    SBMainWorkspaceTransaction *_layoutStateTransitionWorkspaceTransaction;
    SBMainWorkspaceTransaction *_activationLayoutStateTransitionWorkspaceTransaction;
    SBFloatingApplicationRootViewController *_floatingApplicationRootViewController;
    UIPanGestureRecognizer *_panSystemGestureRecognizer;
    long long _initialFloatingConfiguration;
}

+ (double)prototypeSettingsAnimationSpringFriction;
+ (double)prototypeSettingsAnimationSpringTension;
+ (double)prototypeSettingsGestureRubberbandCoefficient;
+ (double)prototypeSettingsInteractiveAnimationSpringFriction;
+ (double)prototypeSettingsInteractiveAnimationSpringTension;
+ (double)prototypeSettingsMovePanGestureNegativeVelocityThreshold;
+ (double)prototypeSettingsMovePanGesturePositiveVelocityThreshold;
+ (double)prototypeSettingsMovePanGestureThresholdPercentage;
+ (double)prototypeSettingsViewMargin;
- (void).cxx_destruct;
- (void)_begin;
- (void)_captureLayoutElementViewControllers;
- (void)_childTransactionDidComplete:(id)arg1;
- (double)_deviceApplicationSceneViewShadowOffsetWithFloatingApplicationViewCenterX:(double)arg1;
- (double)_deviceApplicationSceneViewShadowOpacityWithFloatingApplicationViewCenterX:(double)arg1;
- (void)_didComplete;
- (void)_finishWithCompletionType:(long long)arg1;
- (double)_floatingApplicationViewCenterXWithTranslation:(double)arg1;
- (double)_floatingApplicationViewDarkenViewAlphaWithFloatingApplicationViewCenterX:(double)arg1;
- (long long)_floatingConfigurationWithTranslation:(double)arg1 velocity:(double)arg2;
- (id)_layoutStateTransitionWorkspaceTransactionForFloatingConfiguration:(long long)arg1;
- (id)_sceneLayoutViewController;
- (void)_systemGestureRecognizerBegan;
- (void)_systemGestureRecognizerChanged;
- (void)_systemGestureRecognizerEnded;
- (void)_systemGestureRecognizerFailed;
- (double)_systemGestureRecognizerTranslation;
- (double)_systemGestureRecognizerVelocity;
- (void)_tryPreemptiveFloatingApplicationActivationWithFloatingApplicationViewCenterX:(double)arg1;
- (void)_updateUserInterfaceAfterLayoutStateTransitionWithFloatingConfiguration:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateUserInterfaceBeforeLayoutStateTransitionWithFloatingConfiguration:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateUserInterfaceWithTranslation:(double)arg1 velocity:(double)arg2 systemGestureRecognizerBegan:(_Bool)arg3;
@property(readonly, nonatomic) __weak SBFloatingApplicationRootViewController *floatingApplicationRootViewController; // @synthesize floatingApplicationRootViewController=_floatingApplicationRootViewController;
- (id)initWithTransitionRequest:(id)arg1;
- (id)initWithTransitionRequest:(id)arg1 floatingApplicationRootViewController:(id)arg2 panSystemGestureRecognizer:(id)arg3 initialFloatingConfiguration:(long long)arg4;
@property(readonly, nonatomic) long long initialFloatingConfiguration; // @synthesize initialFloatingConfiguration=_initialFloatingConfiguration;
@property(readonly, nonatomic) UIPanGestureRecognizer *panSystemGestureRecognizer; // @synthesize panSystemGestureRecognizer=_panSystemGestureRecognizer;
- (_Bool)shouldSuppressMedusaKeyboardDuringGesture;
- (void)systemGestureStateChanged:(id)arg1;

@end

