//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertItem.h"

@class NSURL;

@interface SBNoLocalApplicationAlertItem : SBAlertItem
{
    NSURL *_url;
    CDUnknownBlockType _completion;
}

- (void).cxx_destruct;
- (void)_openAppStore;
- (_Bool)allowMenuButtonDismissal;
@property(readonly, copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void)configure:(_Bool)arg1 requirePasscodeForActions:(_Bool)arg2;
- (void)deactivateForButton;
- (_Bool)dismissOnLock;
- (id)init;
- (id)initWithURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)shouldShowInLockScreen;
@property(readonly, copy, nonatomic) NSURL *url; // @synthesize url=_url;

@end

