//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBSystemGestureWorkspaceTransaction.h"

@class FBUIApplicationSceneDeactivationAssertion, SBFloatingApplicationRootViewController, SBMainDisplayLayoutState, SBMainWorkspaceApplicationSceneLayoutElementViewController, SBMainWorkspaceTransaction, SBPanSystemGestureRecognizer;

@interface SBPinFloatingApplicationPanSystemGestureRecognizerWorkspaceTransaction : SBSystemGestureWorkspaceTransaction
{
    SBMainDisplayLayoutState *_initialLayoutState;
    long long _initialInterfaceOrientation;
    long long _initialSpaceConfiguration;
    long long _initialFloatingConfiguration;
    long long _panDirection;
    long long _completionAction;
    SBMainWorkspaceApplicationSceneLayoutElementViewController *_primaryLayoutElementViewController;
    SBMainWorkspaceApplicationSceneLayoutElementViewController *_sideLayoutElementViewController;
    FBUIApplicationSceneDeactivationAssertion *_applicationSceneDeactivationAssertion;
    SBMainWorkspaceTransaction *_layoutStateTransitionWorkspaceTransaction;
    SBFloatingApplicationRootViewController *_floatingApplicationRootViewController;
    SBPanSystemGestureRecognizer *_panSystemGestureRecognizer;
}

+ (double)prototypeSettingsAnimationSpringFriction;
+ (double)prototypeSettingsAnimationSpringTension;
+ (double)prototypeSettingsBlurFadeAnimationDuration;
+ (double)prototypeSettingsCornerRadius;
+ (double)prototypeSettingsFullScreenEdgeInset;
+ (double)prototypeSettingsGestureRubberbandCoefficient;
+ (double)prototypeSettingsInteractiveAnimationSpringFriction;
+ (double)prototypeSettingsInteractiveAnimationSpringTension;
+ (double)prototypeSettingsPinPanUpGestureRubberbandCoefficient;
+ (double)prototypeSettingsPinPanUpGestureThresholdPercentage;
+ (double)prototypeSettingsPinPanUpGestureTravelDistance;
+ (double)prototypeSettingsPinUnpinPanGestureMaximumScale;
+ (double)prototypeSettingsPinUnpinPanGestureThresholdPercentage;
+ (double)prototypeSettingsPinUnpinPanGestureTravelDistance;
- (void).cxx_destruct;
- (void)_begin;
- (void)_captureCompletionAction;
- (void)_captureLayoutElementViewControllers;
- (void)_capturePanDirection;
- (void)_childTransactionDidComplete:(id)arg1;
- (_Bool)_completeTransactionWithTranslation:(double)arg1 velocity:(double)arg2;
- (void)_didComplete;
- (void)_finishWithCompletionType:(long long)arg1;
- (id)_layoutStateTransitionWorkspaceTransaction;
- (id)_sceneLayoutViewController;
- (void)_systemGestureRecognizerBegan;
- (void)_systemGestureRecognizerChanged;
- (void)_systemGestureRecognizerEnded;
- (void)_systemGestureRecognizerFailed;
- (double)_systemGestureRecognizerTranslation;
- (double)_systemGestureRecognizerVelocity;
- (void)_updateUserInterfaceAfterLayoutStateTransitionWithTransactionCompletion:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateUserInterfaceBeforeLayoutStateTransitionWithTransactionCompletion:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_updateUserInterfaceWithTranslation:(double)arg1 velocity:(double)arg2 systemGestureRecognizerBegan:(_Bool)arg3;
- (double)_valueFromSystemGestureRecognizerWithTranslation:(double)arg1 velocity:(double)arg2;
- (void)dealloc;
@property(readonly, nonatomic) __weak SBFloatingApplicationRootViewController *floatingApplicationRootViewController; // @synthesize floatingApplicationRootViewController=_floatingApplicationRootViewController;
- (id)initWithTransitionRequest:(id)arg1;
- (id)initWithTransitionRequest:(id)arg1 floatingApplicationRootViewController:(id)arg2 panSystemGestureRecognizer:(id)arg3;
@property(readonly, nonatomic) SBPanSystemGestureRecognizer *panSystemGestureRecognizer; // @synthesize panSystemGestureRecognizer=_panSystemGestureRecognizer;
- (void)systemGestureStateChanged:(id)arg1;

@end

