//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XBSnapshotDataProvider.h"

@class FBSceneSnapshot, NSString, SBSnapshotDataProviderContext, SBUIImageDataProvider, UIImage, XBSnapshotDataProviderContext;

@interface SBSceneSnapshotDataProvider : NSObject <XBSnapshotDataProvider>
{
    FBSceneSnapshot *_snapshot;
    SBSnapshotDataProviderContext *_context;
    double _scaleFactor;
    UIImage *_cachedImage;
    SBUIImageDataProvider *_fallbackSnapshotDataProvider;
    struct __IOSurface *_processedSurface;
    struct __IOSurface *_processedFallbackSurface;
}

- (void).cxx_destruct;
- (struct __IOSurface *)IOSurface;
- (void)_invalidateSnapshotData;
@property(readonly, retain, nonatomic) XBSnapshotDataProviderContext *context; // @synthesize context=_context;
- (void)dealloc;
- (struct __IOSurface *)fallbackIOSurface;
- (id)fallbackSnapshotDataProvider;
- (id)fetchImage;
- (void)fetchImages;
- (_Bool)hasProtectedContent;
- (id)initWithSceneSnapshot:(id)arg1 scaleFactor:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

