//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "BSDescriptionProviding.h"
#import "SBDisplayLayoutContext.h"
#import "SBLayoutStateTransitionObserver.h"
#import "SBLayoutStateTransitionSceneEntityFrameProvider.h"
#import "SBSceneViewHostRequester.h"

@class FBDisplayLayoutElement, FBDisplayLayoutTransition, FBSDisplayIdentity, NSArray, NSMutableDictionary, NSMutableSet, NSString, SBLayoutState, SBSceneManager, SBWorkspaceApplicationSceneTransitionContext, UIView;

@interface SBSceneLayoutViewController : UIViewController <SBSceneViewHostRequester, SBLayoutStateTransitionObserver, SBLayoutStateTransitionSceneEntityFrameProvider, BSDescriptionProviding, SBDisplayLayoutContext>
{
    FBDisplayLayoutElement *_homescreenLayoutElement;
    FBDisplayLayoutTransition *_displayLayoutTransition;
    NSMutableDictionary *_layoutElementControllersByRole;
    NSMutableDictionary *_previousLayoutElementControllersByRole;
    NSMutableDictionary *_reusableLayoutElementControllers;
    _Bool _emulatingAsynchronousRendering;
    NSMutableSet *_elementViewControllerUpdatesSuspensionReasons;
    _Bool _userResizing;
    _Bool _elementViewControllerUpdatesSuspended;
    SBLayoutState *_transitioningFromLayoutState;
    SBLayoutState *_transitioningToLayoutState;
    SBWorkspaceApplicationSceneTransitionContext *_transitionContext;
    SBWorkspaceApplicationSceneTransitionContext *_previousSuccessfulTransitionContext;
    SBSceneManager *_sceneManager;
    id <SBSceneLayoutViewControllerDelegate> _delegate;
    UIView *_sceneContainerView;
    id <SBSceneLayoutViewControllerTransitioningDelegate> _layoutTransitionDelegate;
}

+ (id)mainDisplaySceneLayoutViewController;
+ (id)sceneLayoutViewControllerForDisplayIdentity:(id)arg1;
- (void).cxx_destruct;
- (void)_addLayoutElementViewController:(id)arg1 forLayoutElement:(id)arg2 entity:(id)arg3;
- (id)_animationWrapperViewForElement:(id)arg1 entity:(id)arg2 layoutState:(id)arg3;
@property(nonatomic, getter=_areElementViewControllerUpdatesSuspended, setter=_setElementViewControllerUpdatesSuspended:) _Bool elementViewControllerUpdatesSuspended; // @synthesize elementViewControllerUpdatesSuspended=_elementViewControllerUpdatesSuspended;
- (void)_beginLayoutStateTransitionWithContext:(id)arg1;
- (void)_cleanupDisappearedLayoutElementController:(id)arg1;
- (void)_configureVisibilityForCurrentLayoutState;
- (long long)_contentInterfaceOrientationForLayoutElement:(id)arg1;
- (id)_dequeueLayoutElementControllerForReuseOfClass:(Class)arg1;
- (id)_displayConfiguration;
- (void)_doCommonCleanupUponEndingLayoutTransition;
- (void)_endLayoutStateTransitionForFailure;
- (void)_endLayoutStateTransitionWithInterruption:(_Bool)arg1;
- (void)_enqueueLayoutViewControllerForReuse:(id)arg1;
- (id)_existingLayoutElementControllerWithElementIdentifier:(id)arg1;
- (void)_invalidate;
@property(readonly, nonatomic, getter=_isCurrentlyRotating) _Bool _currentlyRotating;
@property(readonly, nonatomic, getter=_isCurrentlyTransitioning) _Bool _currentlyTransitioning;
@property(nonatomic, getter=_isEmulatingAsynchronousRendering, setter=_setEmulatesAsynchronousRendering:) _Bool _emulatesAsynchronousRendering; // @synthesize _emulatesAsynchronousRendering=_emulatingAsynchronousRendering;
- (_Bool)_isLayoutElementViewControllerOccluded:(id)arg1;
- (id)_layoutElementControllerForLayoutRole:(long long)arg1;
- (id)_layoutElementViewContainerViewForLayoutRole:(long long)arg1;
@property(readonly, nonatomic) long long _layoutOrientation;
- (long long)_overrideWindowActiveInterfaceOrientation;
- (id)_previousLayoutElementControllerWithElementIdentifier:(id)arg1;
@property(readonly, nonatomic) SBWorkspaceApplicationSceneTransitionContext *_previousSuccessfulTransitionContext; // @synthesize _previousSuccessfulTransitionContext;
- (_Bool)_shouldAdjustViewAffordancesAfterTransition;
- (_Bool)_shouldConsiderHomeScreenAsActive;
- (_Bool)_shouldRepositionViewAfterTransition;
- (_Bool)_shouldRotateToLayoutOrientation:(long long)arg1;
@property(readonly, nonatomic) SBWorkspaceApplicationSceneTransitionContext *_transitionContext; // @synthesize _transitionContext;
@property(readonly, copy, nonatomic) NSArray *_transitioningAppViewControllers;
- (id)_transitioningFromLayoutElementControllerForLayoutRole:(long long)arg1;
@property(readonly, nonatomic) long long _transitioningFromLayoutOrientation;
@property(readonly, nonatomic) SBLayoutState *_transitioningFromLayoutState; // @synthesize _transitioningFromLayoutState;
@property(readonly, copy, nonatomic) NSArray *_transitioningLayoutElementControllers;
@property(readonly, nonatomic) long long _transitioningToLayoutOrientation;
@property(readonly, nonatomic) SBLayoutState *_transitioningToLayoutState; // @synthesize _transitioningToLayoutState;
- (void)_updateAuxiliaryViews;
- (void)_verifyLayoutElementControllersAreValidForCurrentLayoutState;
- (void)_willEndLayoutStateTransition;
- (id)animationControllerForRotatingWithTransitionRequest:(id)arg1;
- (id)animationControllerForTransitionRequest:(id)arg1;
- (id)animationWrapperViewForLayoutState:(id)arg1 roleMask:(unsigned long long)arg2 interfaceOrientation:(long long)arg3;
@property(readonly, nonatomic) NSArray *appViewControllers;
- (id)appViewForWorkspaceEntity:(id)arg1 inLayoutRole:(long long)arg2 withLayoutState:(id)arg3;
- (id)appViewForWorkspaceEntity:(id)arg1 inLayoutRole:(long long)arg2 withLayoutState:(id)arg3 hostRequester:(id)arg4;
- (struct CGPoint)convertPointFromInterfaceOrientationCoordinateSpace:(struct CGPoint)arg1;
- (struct CGPoint)convertPointToInterfaceOrientationCoordinateSpace:(struct CGPoint)arg1;
- (struct CGRect)convertRectFromInterfaceOrientationCoordinateSpace:(struct CGRect)arg1;
- (struct CGRect)convertRectToInterfaceOrientationCoordinateSpace:(struct CGRect)arg1;
- (id)coordinateSpace;
- (id)coordinateSpaceForInterfaceOrientation:(long long)arg1;
- (id)coordinateSpaceForLayoutState:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <SBSceneLayoutViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
@property(readonly, nonatomic) FBSDisplayIdentity *displayIdentity;
@property(readonly, nonatomic) _Bool hasVisibleElements;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithSceneManager:(id)arg1;
@property(nonatomic, getter=isUserResizing) _Bool userResizing; // @synthesize userResizing=_userResizing;
@property(readonly, nonatomic) NSArray *layoutElementControllers;
@property(readonly, nonatomic) SBLayoutState *layoutState;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidBeginWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidEndWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionWillEndWithTransitionContext:(id)arg2;
@property(nonatomic) __weak id <SBSceneLayoutViewControllerTransitioningDelegate> layoutTransitionDelegate; // @synthesize layoutTransitionDelegate=_layoutTransitionDelegate;
- (void)loadView;
- (struct CGRect)referenceFrameForEntity:(id)arg1 inLayoutState:(id)arg2;
- (struct CGRect)referenceFrameForIdentifier:(id)arg1 inLayoutState:(id)arg2;
@property(readonly, nonatomic) UIView *sceneContainerView; // @synthesize sceneContainerView=_sceneContainerView;
- (struct CGRect)sceneEntityFrameForWorkspaceEntity:(id)arg1 inLayoutState:(id)arg2;
@property(readonly, nonatomic) __weak SBSceneManager *sceneManager; // @synthesize sceneManager=_sceneManager;
- (long long)sceneViewHostingPriority:(id)arg1;
- (id)sceneViewHostingRequestIdentifier:(id)arg1;
- (_Bool)shouldAutorotate;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (unsigned long long)supportedInterfaceOrientations;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

