//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBWorkspaceTransaction.h"

#import "FBApplicationUpdateScenesTransactionObserver.h"
#import "FBSynchronizedTransaction.h"
#import "FBSynchronizedTransactionGroupDelegate.h"

@class FBDisplayLayoutTransition, FBSynchronizedTransactionGroup, NSMutableSet, NSSet, NSString, SBAlertManager, SBSceneBackgroundedStatusAssertion, SBSceneLayoutSynchronizeTransitionTransaction, SBWorkspaceApplicationSceneTransitionContext, SBWorkspaceTransitionRequest;

@interface SBSceneLayoutWorkspaceTransaction : SBWorkspaceTransaction <FBSynchronizedTransactionGroupDelegate, FBApplicationUpdateScenesTransactionObserver, FBSynchronizedTransaction>
{
    id <SBSceneLayoutWorkspaceTransactionDelegate> _delegate;
    unsigned long long _options;
    FBDisplayLayoutTransition *_fbLayoutTransition;
    _Bool _isTransitioning;
    _Bool _transitionFailed;
    _Bool _delegateTransitionComplete;
    _Bool _performSceneUpdates;
    _Bool _waitForSceneUpdates;
    _Bool _waitingForSynchronizedCommit;
    SBSceneLayoutSynchronizeTransitionTransaction *_synchronizePrepareTransitionTransaction;
    SBSceneLayoutSynchronizeTransitionTransaction *_synchronizeSendActivationResultTransaction;
    SBSceneLayoutSynchronizeTransitionTransaction *_synchronizeBeginTransitionTransaction;
    SBSceneLayoutSynchronizeTransitionTransaction *_synchronizeAddSlavesTransaction;
    SBAlertManager *_alertManager;
    SBWorkspaceApplicationSceneTransitionContext *_transitionContext;
    FBSynchronizedTransactionGroup *_sceneUpdateTransactionGroup;
    SBSceneBackgroundedStatusAssertion *_scenesBackgroundedStatusAssertion;
    NSMutableSet *_updateTransactions;
    NSMutableSet *_fromAppSceneEntities;
    NSMutableSet *_foregroundingAppSceneEntities;
    NSMutableSet *_backgroundingAppSceneEntities;
    NSMutableSet *_scenesToBackground;
    SBWorkspaceTransitionRequest *_interruptingTransitionRequest;
    id <FBSynchronizedTransactionDelegate> _synchronizationDelegate;
}

- (void).cxx_destruct;
- (void)_begin;
- (void)_beginLayoutTransition;
- (_Bool)_canBeInterrupted;
- (void)_captureAppsForTransition;
- (void)_childTransactionDidComplete:(id)arg1;
- (void)_completeTransition;
- (void)_didComplete;
- (void)_evaluateTransitionCompletion;
- (void)_mainDisplayUpdateAggregateDictionaryForLayoutRoleWithApplication:(id)arg1;
- (_Bool)_overrideInterfaceOrientationForOrientationMismatch:(long long *)arg1;
- (void)_performTransition;
- (void)_prepareLayoutTransition;
- (void)_prepareScenesForTransition;
- (_Bool)_sceneEntities:(id)arg1 hasEntityRepresentingSceneID:(id)arg2;
- (void)_sendActivationResultWithSuccess:(_Bool)arg1;
- (void)_setupKeyboardSuppression;
- (void)_teardownKeyboardSuppression;
- (void)_updateAggregateDictionary;
- (void)_updateScenesForTransitionCompletion;
- (void)_willBegin;
- (void)_willFailWithReason:(id)arg1;
- (void)_willInterruptWithReason:(id)arg1;
@property(readonly, nonatomic) NSSet *backgroundingApplicationSceneEntities; // @synthesize backgroundingApplicationSceneEntities=_backgroundingAppSceneEntities;
- (_Bool)canInterruptForTransitionRequest:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <SBSceneLayoutWorkspaceTransactionDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSSet *foregroundingApplicationSceneEntities; // @synthesize foregroundingApplicationSceneEntities=_foregroundingAppSceneEntities;
@property(readonly, nonatomic) NSSet *fromApplicationSceneEntities; // @synthesize fromApplicationSceneEntities=_fromAppSceneEntities;
- (id)initWithTransitionRequest:(id)arg1;
- (_Bool)isReadyForSynchronizedCommit;
@property(readonly, nonatomic, getter=isTransitioning) _Bool transitioning; // @synthesize transitioning=_isTransitioning;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
- (void)performSynchronizedCommit;
@property(readonly, nonatomic) NSSet *sceneUpdateTransactions; // @synthesize sceneUpdateTransactions=_updateTransactions;
@property(nonatomic) __weak id <FBSynchronizedTransactionDelegate> synchronizationDelegate; // @synthesize synchronizationDelegate=_synchronizationDelegate;
- (void)synchronizedTransaction:(id)arg1 didCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransaction:(id)arg1 willCommitSynchronizedTransactions:(id)arg2;
- (_Bool)synchronizedTransactionGroup:(id)arg1 shouldFailForSynchronizedTransaction:(id)arg2;
- (void)synchronizedTransactionReadyToCommit:(id)arg1;
@property(readonly, nonatomic) NSSet *toApplicationSceneEntities;
- (void)transaction:(id)arg1 didCommitSceneUpdate:(id)arg2;
- (void)transaction:(id)arg1 didCreateScene:(id)arg2;
- (void)transaction:(id)arg1 didLaunchProcess:(id)arg2;
- (void)transaction:(id)arg1 willCommitSceneUpdate:(id)arg2;
- (void)transaction:(id)arg1 willLaunchProcess:(id)arg2;
- (void)transaction:(id)arg1 willUpdateScene:(id)arg2;
@property(readonly, nonatomic) SBWorkspaceApplicationSceneTransitionContext *transitionContext; // @synthesize transitionContext=_transitionContext;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

