//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBPasscodeEntryAlertView.h"

#import "SBSIMLockEntryViewInterface.h"
#import "SBUIPasscodeLockViewDelegate.h"

@class NSString;

@interface SBSIMLockEntryAlertView : SBPasscodeEntryAlertView <SBUIPasscodeLockViewDelegate, SBSIMLockEntryViewInterface>
{
    NSString *_languageCode;
    NSString *_code;
}

- (void).cxx_destruct;
- (void)_doUnlock;
- (id)_failureLabel;
- (id)_failureTitle;
- (id)_passcodeView;
- (CDUnknownBlockType)_passcodeViewGenerator;
- (id)_pinAttemptsRemainingLabel;
- (void)_unlock;
- (void)alertDisplayWillBecomeVisible;
- (id)initWithFrame:(struct CGRect)arg1 languageCode:(id)arg2;
- (id)label;
- (id)localizedStringWithKey:(id)arg1;
- (void)passcodeLockViewCancelButtonPressed:(id)arg1;
- (void)passcodeLockViewPasscodeEntered:(id)arg1;
- (void)setupCurrentLockAttemptState;
- (void)setupFailureState;
- (void)setupSuccess;
- (void)setupUnlockAttemptState;
- (id)titleText;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

