//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBWindow.h"

@class SBStarkStatusBarViewController;

@interface SBStarkStatusBarWindow : SBWindow
{
    id <SBStarkSessionConfiguring> _configuration;
}

- (void).cxx_destruct;
- (_Bool)_reversesLinearFocusWrapping;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithScreen:(id)arg1 layoutStrategy:(id)arg2 debugName:(id)arg3 configuration:(id)arg4;
@property(retain, nonatomic) SBStarkStatusBarViewController *rootViewController;

@end

