//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, UIButton, UIImageView, UILabel, UITapGestureRecognizer;

@interface SBStarkLockOutView : UIView
{
    id <SBStarkSessionConfiguring> _configuration;
    UILabel *_titleLabel;
    double _titleAscender;
    double _titleDescender;
    UIImageView *_imageView;
    struct CGSize _imageSize;
    UILabel *_messageLabel;
    double _messageAscender;
    double _messageDescender;
    UIButton *_backToOEMButton;
    UITapGestureRecognizer *_backToOEMGestureRecognizer;
    NSArray *_baselineSeparations;
}

- (void).cxx_destruct;
- (void)_backToOEM;
- (id)_messageFontOfSize:(double)arg1;
- (struct CGSize)_sizeMessageToFitInFrame:(struct CGRect)arg1;
- (struct CGSize)_sizeTitleToFitInFrame:(struct CGRect)arg1;
- (id)_titleFontOfSize:(double)arg1;
@property(readonly, nonatomic) UIButton *backToOEMButton; // @synthesize backToOEMButton=_backToOEMButton;
@property(readonly, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 configuration:(id)arg2 title:(id)arg3 image:(id)arg4 message:(id)arg5 baselineSeparations:(id)arg6;
- (void)layoutSubviews;
@property(readonly, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
- (id)preferredFocusEnvironments;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

