//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBWorkspaceTransaction.h"

#import "SBAlertManagerObserver.h"

@class FBDisplayLayoutTransition, NSString, SBAlertManager, SBStarkScreenController;

@interface SBStarkWorkspaceTransaction : SBWorkspaceTransaction <SBAlertManagerObserver>
{
    FBDisplayLayoutTransition *_rootLayoutTransition;
    SBStarkScreenController *_starkScreenController;
    SBAlertManager *_starkScreenAlertManager;
}

- (void).cxx_destruct;
- (_Bool)_canBeInterrupted;
- (void)_didComplete;
- (void)_willBegin;
- (_Bool)canInterruptForTransitionRequest:(id)arg1;
- (void)dealloc;
- (id)initWithTransitionRequest:(id)arg1;
@property(readonly, nonatomic) SBAlertManager *starkScreenAlertManager; // @synthesize starkScreenAlertManager=_starkScreenAlertManager;
@property(readonly, nonatomic) SBStarkScreenController *starkScreenController; // @synthesize starkScreenController=_starkScreenController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

