//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBIconView.h"

@interface SBStarkIconView : SBIconView
{
    _Bool _alwaysAppearsFocused;
}

+ (int)_defaultIconFormat;
+ (double)_labelHeight;
+ (struct CGRect)_rectForLayoutMetric:(int)arg1;
+ (_Bool)_supportsDragInteraction;
+ (_Bool)canShowLabelAccessoryView;
+ (struct CGSize)defaultIconSize;
+ (struct UIEdgeInsets)iconImagePaddingInsets;
+ (struct CGSize)maxLabelSize;
+ (struct UIEdgeInsets)minimumInterIconSpacing;
- (struct CGRect)_frameForLabel;
- (id)_labelImageParameters;
@property(nonatomic) _Bool alwaysAppearsFocused; // @synthesize alwaysAppearsFocused=_alwaysAppearsFocused;
- (_Bool)canBecomeFocused;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (void)prepareForReuse;

@end

