//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBMainWorkspaceTransaction.h"

@class SBStarkScreenController;

@interface SBStarkDisconnectWorkspaceTransaction : SBMainWorkspaceTransaction
{
    SBStarkScreenController *_screenController;
    _Bool _invalidating;
}

- (void).cxx_destruct;
- (void)_begin;
- (void)_didComplete;
- (id)initWithTransitionRequest:(id)arg1;
- (id)initWithTransitionRequest:(id)arg1 starkScreenController:(id)arg2 invalidating:(_Bool)arg3;

@end

