//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CAAnimationDelegate.h"
#import "SBDosidoAnimator.h"

@class CAMutableMeshTransform, NSString, SBStretchTransformerView, UIView;

@interface SBStretchTransformer : NSObject <CAAnimationDelegate, SBDosidoAnimator>
{
    double _percentage;
    CAMutableMeshTransform *_mesh;
    CDUnknownBlockType _completionBlock;
    double _stretchFactor;
    UIView *_parentView;
    SBStretchTransformerView *_transformView;
    UIView *_view;
    unsigned long long _anchorEdge;
    long long _orientation;
}

- (void).cxx_destruct;
- (void)_animateToZeroStretchFactor;
@property(nonatomic, setter=_setAnchorEdge:) unsigned long long anchorEdge; // @synthesize anchorEdge=_anchorEdge;
@property(nonatomic, setter=_setOrientation:) long long orientation; // @synthesize orientation=_orientation;
- (void)_setStretchFactor:(double)arg1;
- (void)animateDosidoWithFactory:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)cancelDosido;
- (void)dealloc;
- (void)finishSteppingBackwardToStart;
- (void)finishSteppingForwardToEnd;
- (id)initWithParentView:(id)arg1 anchorEdge:(unsigned long long)arg2 orientation:(long long)arg3;
@property(readonly, nonatomic, getter=isStepped) _Bool stepped;
@property(nonatomic) double stepPercentage;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
- (void)updateMeshTransform:(id)arg1 stretchFactor:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

