//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBStarkToAppWorkspaceTransaction.h"

#import "SBUIAnimationControllerObserver.h"

@class NSString, SBAlert, SBUIAnimationController;

@interface SBStarkAlertToAppWorkspaceTransaction : SBStarkToAppWorkspaceTransaction <SBUIAnimationControllerObserver>
{
    SBAlert *_alert;
    SBUIAnimationController *_animation;
    _Bool _animatedAppActivation;
    _Bool _animatingAlertSuspension;
    _Bool _deactivateAfterNextLaunch;
    _Bool _fromAssistant;
    _Bool _waitingForAppActivation;
}

- (void).cxx_destruct;
- (void)_alertAnimationComplete:(id)arg1;
- (void)_alertDidDeactivate;
- (void)_begin;
- (void)_beginAnimation;
- (void)_cleanUpAnimation;
- (void)_deactivateAlertIfNecessary;
- (void)_didComplete;
- (void)_handleFailure;
- (_Bool)_hasAnimation;
@property(readonly, nonatomic) SBAlert *alert; // @synthesize alert=_alert;
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)dealloc;
@property(readonly, copy) NSString *debugDescription;
- (id)initWithTransitionRequest:(id)arg1;
- (void)mainScreenApplicationSceneDidCommit:(id)arg1;
- (void)mainScreenApplicationUpdateScenesTransactionCompleted:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

