//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MTPlatterView.h"

@class SBBestAppSuggestion, UIImageView, UILabel, UIView;

@interface SBSwitcherAppSuggestionBannerView : MTPlatterView
{
    SBBestAppSuggestion *_suggestion;
    UIImageView *_iconView;
    UILabel *_appLabel;
    UILabel *_descriptionLabel;
    unsigned long long _style;
    _Bool _highlighted;
    UIView *_highlightDarkeningView;
}

- (void).cxx_destruct;
- (id)_appTitleForSuggestion:(id)arg1;
- (void)_configureConstraints;
- (void)_createAppLabelForSuggestion:(id)arg1;
- (void)_createDarkeningView;
- (void)_createDescriptionLabelForSuggestion:(id)arg1;
- (void)_createIconViewForSuggestion:(id)arg1;
- (id)_descriptionFont;
- (id)_descriptionStringForSuggestion:(id)arg1;
- (id)_firstWakeGreetingString;
- (id)_iconImageFromAppWithBundleIdentifier:(id)arg1 withIconFormat:(int)arg2;
- (_Bool)_isSingleLine;
- (id)_meCardShortName;
- (id)_textStyle;
- (id)_titleFont;
- (id)initWithFrame:(struct CGRect)arg1 appSuggestion:(id)arg2 style:(unsigned long long)arg3;
- (id)initWithRecipe:(long long)arg1 options:(unsigned long long)arg2;
@property(nonatomic, getter=isHighlighted) _Bool highlighted; // @dynamic highlighted;
@property(readonly, nonatomic) SBBestAppSuggestion *representedAppSuggestion;
@property(readonly, nonatomic) unsigned long long style; // @synthesize style=_style;

@end

