//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBAppLayout;

@interface SBSwitcherInsertionRemovalLayoutParameters : NSObject
{
    SBAppLayout *_appLayout;
    unsigned long long _targetVisibilityState;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SBAppLayout *appLayout; // @synthesize appLayout=_appLayout;
- (id)initWithAppLayout:(id)arg1 targetVisibilityState:(unsigned long long)arg2;
@property(readonly, nonatomic) unsigned long long targetVisibilityState; // @synthesize targetVisibilityState=_targetVisibilityState;

@end

