//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBTouchTemplatePanGestureRecognizer.h"

@interface SBSwitchAppSystemGestureRecognizer : SBTouchTemplatePanGestureRecognizer
{
}

- (void)_installTemplates;
- (double)animationDistance;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
- (id)logCategory;

@end

