//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SBPolygon, SBTouchTemplate;

@interface SBTemplateAndMorph : NSObject
{
    SBPolygon *_morphedCandidate;
    SBTouchTemplate *_touchTemplate;
}

- (void).cxx_destruct;
- (id)initWithTemplate:(id)arg1 morph:(id)arg2;
@property(readonly, nonatomic) SBPolygon *morphedCandidate; // @synthesize morphedCandidate=_morphedCandidate;
@property(readonly, nonatomic) SBTouchTemplate *touchTemplate; // @synthesize touchTemplate=_touchTemplate;

@end

