//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@class SBAppStatusBarSettingsAssertion, SBDosidoAnimator, SBWindowSelfHostWrapper, UIView;

@interface SBUIAnimationDosidoTransitionController : SBUIMainScreenAnimationController
{
    UIView *_fromView;
    UIView *_toView;
    SBWindowSelfHostWrapper *_homeScreenHostWrapper;
    SBDosidoAnimator *_dosidoAnimator;
    long long _fromOrientation;
    _Bool _requiresHostView;
    _Bool _fromAppWantsLiveContent;
    _Bool _dosidoDidComplete;
    _Bool _crossfadeDidComplete;
    _Bool _activationFailed;
    _Bool _finishedActivating;
    unsigned long long _direction;
    SBAppStatusBarSettingsAssertion *_hideStatusBarAssertion;
}

- (void).cxx_destruct;
- (void)__startAnimation;
- (id)_animationFactory;
- (void)_application:(id)arg1 processStateDidChange:(id)arg2;
- (void)_cleanupAnimation;
- (void)_evaluateDependencies;
- (void)_evaluateTransparency;
- (id)_getTransitionWindow;
- (void)_invalidateWrapperView:(id)arg1;
- (_Bool)_isFromCommandTab;
- (_Bool)_isTransitionToSpotlight;
- (id)_mainScreenSnapshot;
- (void)_maybeReportAnimationFinished;
- (void)_maybeStartCrossfade;
- (void)_performCrossfadeIfNeeded;
- (void)_prepareAnimation;
- (id)_progressDependencies;
- (void)_sceneHandle:(id)arg1 didUpdateContentState:(long long)arg2;
- (void)_setFromView:(id)arg1;
- (void)_setHidden:(_Bool)arg1;
- (void)_setupDisplayModeForActivatingAppView:(id)arg1;
- (void)_setupDisplayModeForAppView:(id)arg1 displayMode:(long long)arg2;
- (void)_setupDisplayModeForDeactivatingAppView:(id)arg1;
- (void)_startAnimation;
- (_Bool)_waitsForActivatingSceneContentAvailableIfNecessary;
- (id)animationSettings;
- (void)captureFlagsForActivatingApp:(id)arg1;
- (void)dealloc;
@property(nonatomic) unsigned long long direction; // @synthesize direction=_direction;
- (void)enableSteppingWithAnimationSettings:(id)arg1;
@property(nonatomic) _Bool fromAppWantsLiveContent; // @synthesize fromAppWantsLiveContent=_fromAppWantsLiveContent;
- (id)initWithTransitionContextProvider:(id)arg1;
- (_Bool)isInterruptible;
- (_Bool)isReasonableMomentToInterrupt;
- (long long)orientationAtLaunch;
- (void)setToView:(id)arg1;

@end

