//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIWorkspaceAnimationController.h"

@class SBMainSwitcherViewController;

@interface SBUISwitcherAnimationController : SBUIWorkspaceAnimationController
{
    _Bool _interruptible;
    SBMainSwitcherViewController *_switcherViewController;
    CDUnknownBlockType _animationBlock;
}

- (void).cxx_destruct;
- (void)_addSignpostsForAnimationEnd;
- (void)_addSignpostsForAnimationStart;
- (void)_didComplete;
@property(nonatomic, getter=_isInterruptible, setter=_setInterruptible:) _Bool _interruptible; // @synthesize _interruptible;
- (id)_layoutState;
- (id)_previousLayoutState;
- (void)_startAnimation;
- (void)_updatePPTsForAnimationEnd;
- (void)_updatePPTsForAnimationStart;
@property(copy, nonatomic) CDUnknownBlockType animationBlock; // @synthesize animationBlock=_animationBlock;
- (id)animationSettings;
- (id)initWithWorkspaceTransitionRequest:(id)arg1 switcherViewController:(id)arg2 animationBlock:(CDUnknownBlockType)arg3;
- (_Bool)isInterruptible;
- (_Bool)isReasonableMomentToInterrupt;
@property(nonatomic) __weak SBMainSwitcherViewController *switcherViewController; // @synthesize switcherViewController=_switcherViewController;

@end

