//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIStarkScreenAnimationController.h"

#import "SBIconAnimatorDelegate.h"

@class NSString, SBAlert, SBIconAnimator, UIView;

@interface SBUIStarkZoomDownAppToHomeAnimation : SBUIStarkScreenAnimationController <SBIconAnimatorDelegate>
{
    UIView *_viewToAnimate;
    SBIconAnimator *_iconAnimator;
    SBAlert *_alertImpersonator;
    _Bool _animationFinished;
    _Bool _fromAssistant;
}

- (void).cxx_destruct;
- (void)_animateZoomWithCompletion:(CDUnknownBlockType)arg1;
- (double)_animationDelay;
- (void)_cleanupAnimation;
- (void)_cleanupHosting;
- (void)_noteDependencyDidInvalidate;
- (void)_noteZoomDidFinish;
- (void)_prepareAnimation;
- (void)_prepareZoom;
- (void)_setReferenceIconViewHiddenIfAppropriate:(_Bool)arg1;
- (void)_startAnimation;
- (id)_viewToAnimate;
- (id)animationSettings;
- (void)dealloc;
- (void)iconAnimatorWasInvalidated:(id)arg1;
- (id)initWithDeactivatingApplicationSceneEntity:(id)arg1 alertImpersonator:(id)arg2 starkScreenController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

