//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@class SBAlertManager, SBUIFullscreenAlertAdapter;

@interface SBUIAnimationFadeHomeToPluginAlert : SBUIMainScreenAnimationController
{
    SBAlertManager *_alertManager;
    SBUIFullscreenAlertAdapter *_alert;
    _Bool _alertIsTransparent;
    _Bool _alertViewIsAnimatingItself;
    _Bool _finishedPrimaryFadeAnimation;
}

- (void).cxx_destruct;
- (void)_alertViewFinishedAnimatingItself;
- (void)_animationFinished;
- (void)_cleanupAnimation;
- (void)_evaluateTotalAnimationCompletion;
- (void)_fadeAnimationFinished;
- (void)_prepareAnimation;
- (void)_startAnimation;
- (double)animationDuration;
- (id)animationSettings;
- (void)dealloc;
- (id)initWithTransitionContextProvider:(id)arg1;

@end

