//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlertViewAdapter.h"

@interface SBUIFullscreenAlertViewAdapter : SBAlertViewAdapter
{
    _Bool _revealedContentBeneathForDismiss;
    _Bool _animatingOut;
}

- (id)alert;
- (void)alertDisplayWillBecomeVisible;
- (void)dismiss;
- (_Bool)isAnimatingOut;
- (_Bool)isReadyToBeRemovedFromView;
- (void)setAlert:(id)arg1;
- (void)setShouldAnimateIn:(_Bool)arg1;
- (_Bool)shouldAnimateIconsIn;
- (void)viewAnimatedOut;

@end

