//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NSURL, SBAlertItem, SBAwayViewPluginController, SBUIFullscreenAlertController;

@protocol SBUIUserAgent <NSObject>
- (void)activateModalBulletinAlert:(SBAlertItem *)arg1;
- (void)activateRemoteAlertService:(NSString *)arg1 options:(NSDictionary *)arg2;
- (void)activateRemoteAlertService:(NSString *)arg1 options:(NSDictionary *)arg2 activationHandler:(void (^)(_Bool))arg3 deactivationHandler:(void (^)(_Bool))arg4;
- (long long)activeInterfaceOrientation;
- (void)addActiveInterfaceOrientationObserver:(id <SBUIActiveOrientationObserver>)arg1;
- (void)addIdleTimerHandler:(id <SBUIIdleTimerHandler>)arg1;
- (void)adjustLockScreenContentByOffset:(double)arg1 forAwayViewPlugin:(SBAwayViewPluginController *)arg2 withAnimationDuration:(double)arg3;
- (_Bool)alertIsActive;
- (_Bool)applicationInstalledForDisplayID:(NSString *)arg1;
- (_Bool)canLaunchFromAwayViewPluginWithURL:(NSURL *)arg1 bundleID:(NSString *)arg2;
- (_Bool)canLaunchFromSource:(int)arg1 withURL:(NSURL *)arg2 bundleID:(NSString *)arg3;
- (_Bool)deviceIsBlocked;
- (_Bool)deviceIsLocked;
- (_Bool)deviceIsPasscodeLocked;
- (_Bool)deviceIsPasscodeLockedRemotely;
- (_Bool)deviceIsTethered;
- (void)disableLockScreenBundleNamed:(NSString *)arg1 deactivationContext:(NSDictionary *)arg2;
- (void)enableLockScreenBundleNamed:(NSString *)arg1 activationContext:(NSDictionary *)arg2;
- (NSString *)folderNameForDisplayID:(NSString *)arg1;
- (NSString *)foregroundApplicationDisplayID;
- (NSString *)foregroundDisplayID;
- (_Bool)isApplicationForegroundObscured:(NSString *)arg1;
- (_Bool)isApplicationRestrictedOrHidden:(NSString *)arg1;
- (_Bool)isIdleTimerDisabledForReason:(NSString *)arg1;
- (_Bool)isInternalInstall;
- (_Bool)isNamedRemoteAlertServiceActive:(NSString *)arg1 controllerClassName:(NSString *)arg2;
- (_Bool)isScreenOn;
- (_Bool)launchApplicationFromSource:(int)arg1 withDisplayID:(NSString *)arg2 options:(NSDictionary *)arg3;
- (_Bool)launchApplicationFromSource:(int)arg1 withURL:(NSURL *)arg2 options:(NSDictionary *)arg3;
- (_Bool)launchFromAwayViewPluginWithURL:(NSURL *)arg1 bundleID:(NSString *)arg2 allowUnlock:(_Bool)arg3 animate:(_Bool)arg4;
- (_Bool)launchFromSource:(int)arg1 withURL:(NSURL *)arg2 bundleID:(NSString *)arg3 allowUnlock:(_Bool)arg4;
- (NSString *)localizedDisplayNameForDisplayID:(NSString *)arg1;
- (void)lockAndDimDevice;
- (void)lockAndDimDeviceDisconnectingCallIfNecessary:(_Bool)arg1;
- (void)lockAndDimDeviceDisconnectingCallIfNecessary:(_Bool)arg1 andDimScreen:(_Bool)arg2;
- (_Bool)lockScreenIsShowing;
- (id <SBBulletinAlertHandlerRegistry>)modalBulletinAlertHandlerRegistry;
- (int)networkUsageTypeForAppWithDisplayID:(NSString *)arg1;
- (void)notifyOnNextUserEvent;
- (_Bool)openURL:(NSURL *)arg1 allowUnlock:(_Bool)arg2 animated:(_Bool)arg3;
- (void)removeActiveInterfaceOrientationObserver:(id <SBUIActiveOrientationObserver>)arg1;
- (void)removeIdleTimerHandler:(id <SBUIIdleTimerHandler>)arg1;
- (void)setBadgeNumberOrString:(id)arg1 forApplicationWithID:(NSString *)arg2;
- (void)setIdleText:(NSString *)arg1;
- (void)setIdleTimerDisabled:(_Bool)arg1 forReason:(NSString *)arg2;
- (void)setMinimumBacklightLevel:(float)arg1 animated:(_Bool)arg2;
- (void)setWallpaperTunnelActive:(_Bool)arg1 forFullscreenAlertController:(SBUIFullscreenAlertController *)arg2;
- (_Bool)springBoardIsActive;
- (NSString *)topSuspendedEventsOnlyDisplayID;
- (void)undimScreen;
- (void)updateCustomSubtitleTextForAwayViewPlugin:(SBAwayViewPluginController *)arg1;
- (void)updateInterfaceOrientationIfNecessary;
- (void)updateLockScreenInterfaceIfNecessary;
- (struct __CFRunLoop *)wifiRunLoopRef;
@end

