//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlert.h"

@class NSTimer;

@interface SBUSSDAlert : SBAlert
{
    unsigned int _receivedString:1;
    unsigned int _dismissOnActivate:1;
    NSTimer *_delayedDismissTimer;
}

+ (void)_daemonRestart:(id)arg1;
+ (void)_newSIM:(id)arg1;
+ (id)errorStringForCode:(id)arg1;
+ (void)registerForAlerts;
+ (void)registerForSettingsAlerts;
+ (void)test;
- (void).cxx_destruct;
- (void)USSDStringAvailable:(id)arg1 allowsResponse:(_Bool)arg2;
- (void)_delayedDismiss;
- (void)activate;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (_Bool)allowsResponse;
- (_Bool)allowsStackingOfAlert:(id)arg1;
- (void)deactivate;
- (void)dealloc;
- (_Bool)receivedString;
- (_Bool)sentResponse;
- (void)setDismissOnActivate:(_Bool)arg1;
- (long long)statusBarStyle;

@end

