//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SBValueConvergenceAnimator : NSObject
{
    double _previousForce;
    double _diff;
    _Bool _finishesOnValueConvergence;
    double _currentValue;
    double _targetValue;
    CDUnknownBlockType _convergenceFunction;
    CDUnknownBlockType _applier;
    CDUnknownBlockType _completion;
    long long _frameInterval;
    double _startTime;
    double _lastFireTime;
}

- (void).cxx_destruct;
- (void)_convergeValue;
- (void)_invokeApplier;
- (void)_invokeCompletionWithFinished:(_Bool)arg1;
- (void)_reset;
@property(copy, nonatomic) CDUnknownBlockType applier; // @synthesize applier=_applier;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(copy, nonatomic) CDUnknownBlockType convergenceFunction; // @synthesize convergenceFunction=_convergenceFunction;
@property(nonatomic) double currentValue; // @synthesize currentValue=_currentValue;
- (void)dealloc;
@property(readonly, nonatomic) double elapsedTime;
@property(nonatomic) _Bool finishesOnValueConvergence; // @synthesize finishesOnValueConvergence=_finishesOnValueConvergence;
@property(nonatomic) long long frameInterval; // @synthesize frameInterval=_frameInterval;
- (id)init;
- (_Bool)isRunning;
@property(nonatomic) double lastFireTime; // @synthesize lastFireTime=_lastFireTime;
- (void)setConvergenceFunctionWithConstant:(long long)arg1;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) double targetValue; // @synthesize targetValue=_targetValue;
- (void)start;
- (void)stop;

@end

