//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBAlert.h"

#import "SBDashBoardExternalBehaviorProviding.h"

@class NSString, _UIBackdropView;

@interface SBVoiceControlAlert : SBAlert <SBDashBoardExternalBehaviorProviding>
{
    struct {
        unsigned int shouldBeActivated:1;
        unsigned int isReadyToBeActivated:1;
        unsigned int hasBeenActivated:1;
    } _voiceControlFlags;
    _UIBackdropView *_backdrop;
    _Bool _didDismiss;
}

+ (_Bool)_bluetoothDevicesPickable;
+ (void)_configureSession:(id)arg1 forAlert:(id)arg2;
+ (void)_setNextRecognitionAudioInputPathForSession:(id)arg1 resetting:(_Bool)arg2;
+ (void)bluetoothDeviceRequestedVoiceControl:(id)arg1;
+ (void)bluetoothDeviceTerminatedVoiceControl:(id)arg1;
+ (id)pendingOrActiveAlert;
+ (void)registerForAlerts;
+ (_Bool)resetVoiceControlIfNecessary:(_Bool)arg1;
+ (void)setNextRecognitionAudioInputPaths:(id)arg1;
+ (_Bool)shouldEnterVoiceControl;
+ (void)unregisterForAlerts;
- (void).cxx_destruct;
- (void)_makeActive;
- (void)_proximityChanged:(id)arg1;
- (void)_resign;
- (id)_session;
- (void)_setRoutingAttributesForWiredHeadset:(_Bool)arg1;
- (void)_workspaceActivate;
- (void)activate;
- (void)activateWhenReady;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;
- (_Bool)allowsEventOnlySuspension;
- (double)autoDimTime;
- (void)cancel;
- (void)cancelIfNotActivated;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (void)deactivate;
- (void)dealloc;
- (void)dismissAlert;
- (void)handleHeadsetButtonUpFromActivation:(_Bool)arg1;
- (_Bool)handleHomeButtonPress;
@property(readonly, nonatomic) long long idleTimerDuration;
@property(readonly, nonatomic) long long idleTimerMode;
@property(readonly, nonatomic) long long idleWarnMode;
- (id)init;
- (id)initFromBluetoothDevice:(id)arg1;
- (id)initFromMenuButton;
- (id)initFromWiredHeadsetButton;
- (void)loadView;
@property(readonly, nonatomic) long long notificationBehavior;
@property(readonly, nonatomic) long long participantState;
@property(readonly, nonatomic) long long proximityDetectionMode;
- (_Bool)recognitionSessionWillBeginAction:(id)arg1;
@property(readonly, nonatomic) unsigned long long restrictedCapabilities;
@property(readonly, nonatomic) long long scrollingStrategy;
- (void)setBackgroundWeighting:(double)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)wantsHomeButtonPress;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

