//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBPressPrecedenceArbiter.h"
#import "UIGestureRecognizerDelegate.h"

@class NSHashTable, NSString, SBPressGestureRecognizer, SBPressSequenceObserver, SBVolumeHardwareButtonActions, UIGestureRecognizer;

@interface SBVolumeHardwareButton : NSObject <UIGestureRecognizerDelegate, SBPressPrecedenceArbiter>
{
    unsigned long long _volumeUpAggdStartTime;
    unsigned long long _volumeDownAggdStartTime;
    long long _homeButtonType;
    SBPressGestureRecognizer *_volumeIncreaseButtonPressGestureRecognizer;
    SBPressGestureRecognizer *_volumeDecreaseButtonPressGestureRecognizer;
    UIGestureRecognizer *_screenshotGestureRecognizer;
    NSHashTable *_volumePressBandits;
    SBPressSequenceObserver *_volumeIncreaseSequenceObserver;
    SBPressSequenceObserver *_volumeDecreaseSequenceObserver;
    SBVolumeHardwareButtonActions *_buttonActions;
}

- (void).cxx_destruct;
- (void)_aggdLogVolumeDecreaseButtonDown:(_Bool)arg1;
- (void)_aggdLogVolumeIncreaseButtonDown:(_Bool)arg1;
- (void)_createGestureRecognizers;
- (void)_logVolumeButtonWithObserver:(id)arg1 down:(_Bool)arg2;
- (void)addVolumePressBandit:(id)arg1;
@property(readonly, nonatomic) SBVolumeHardwareButtonActions *buttonActions; // @synthesize buttonActions=_buttonActions;
- (void)cancelVolumePress;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)initWithScreenshotGestureRecognizer:(id)arg1 homeButtonType:(long long)arg2;
- (id)preemptablePressGestureRecognizers;
- (void)removeVolumePressBandit:(id)arg1;
@property(nonatomic) __weak NSHashTable *volumePressBandits; // @synthesize volumePressBandits=_volumePressBandits;
- (void)volumeDecreasePress:(id)arg1;
@property(readonly, nonatomic) SBPressSequenceObserver *volumeDecreaseSequenceObserver; // @synthesize volumeDecreaseSequenceObserver=_volumeDecreaseSequenceObserver;
- (void)volumeIncreasePress:(id)arg1;
@property(readonly, nonatomic) SBPressSequenceObserver *volumeIncreaseSequenceObserver; // @synthesize volumeIncreaseSequenceObserver=_volumeIncreaseSequenceObserver;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

