//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "BSDescriptionProviding.h"
#import "SBDashBoardWallpaperOverlayHosting.h"
#import "SBFLegibilitySettingsProviderDelegate.h"
#import "SBFWallpaperConfigurationManagerDelegate.h"
#import "SBFWallpaperViewInternalObserver.h"
#import "SBFWallpaperViewSettingsProvider.h"
#import "SBUIActiveOrientationObserver.h"
#import "SBWallpaperServerDelegate.h"
#import "UIWindowDelegate.h"
#import "_UISettingsKeyObserver.h"

@class NSHashTable, NSMutableSet, NSString, SBFWallpaperConfigurationManager, SBFWallpaperSettings, SBFWallpaperView, SBRootSettings, SBWallpaperAggdLogger, SBWallpaperStyleInfo, UIImage, UIScreen, UIView, UIView<SBUIWallpaperOverlay>, UIWindow;

@interface SBWallpaperController : NSObject <SBFLegibilitySettingsProviderDelegate, SBFWallpaperViewInternalObserver, SBUIActiveOrientationObserver, _UISettingsKeyObserver, SBFWallpaperConfigurationManagerDelegate, BSDescriptionProviding, SBWallpaperServerDelegate, SBFWallpaperViewSettingsProvider, UIWindowDelegate, SBDashBoardWallpaperOverlayHosting>
{
    UIWindow *_wallpaperWindow;
    UIView *_wallpaperContainerView;
    UIView *_wallpaperOverlayContainerView;
    long long _orientation;
    SBFWallpaperView *_lockscreenWallpaperView;
    SBFWallpaperView *_homescreenWallpaperView;
    SBFWallpaperView *_sharedWallpaperView;
    NSHashTable *_lockscreenObservers;
    NSHashTable *_homescreenObservers;
    NSMutableSet *_suspendColorSamplingReasons;
    NSMutableSet *_suspendWallpaperAnimationReasons;
    NSMutableSet *_requireWallpaperReasons;
    NSMutableSet *_hideHomescreenWallpaperReasons;
    NSMutableSet *_hideLockscreenWallpaperReasons;
    long long _displayedVariant;
    double _lockscreenOnlyWallpaperAlpha;
    NSHashTable *_lockscreenBlurViews;
    NSHashTable *_homescreenBlurViews;
    long long _disallowRasterizationBlockCount;
    NSMutableSet *_disallowRasterizationReasonsHomeVariant;
    NSMutableSet *_disallowRasterizationReasonsLockVariant;
    UIImage *_homescreenLightForegroundBlurImage;
    struct CGRect _homescreenLightForegroundBlurImageDisplayRect;
    _Bool _creatingHomescreenLightForegroundBlurImage;
    _Bool _isSuspendingMotionEffectsForStyle;
    long long _activeOrientationSource;
    _Bool _coalescingGeometryChanges;
    long long _locationsWithCoalescedGeometryChanges;
    NSMutableSet *_homescreenStyleChangeDelayReasons;
    SBFWallpaperConfigurationManager *_wallpaperConfigurationManager;
    UIView<SBUIWallpaperOverlay> *_wallpaperOverlay;
    UIScreen *_screen;
    NSString *_cachingIdentifier;
    double _homescreenWallpaperScale;
    double _lockscreenWallpaperScale;
    SBWallpaperStyleInfo *_homescreenStyleInfo;
    SBWallpaperStyleInfo *_lockscreenStyleInfo;
    SBWallpaperAggdLogger *_wallpaperAggdLogger;
    SBRootSettings *_rootSettings;
}

+ (id)sharedInstance;
+ (id)substitutionFlatColorForWallpaperName:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=_WallpaperOrientationNotForYou) long long _orientation; // @synthesize _orientation;
- (void)_accessibilityReduceTransparencyChanged:(id)arg1;
- (id)_activeWallpaperView;
- (void)_batterySaverModeChanged:(id)arg1;
- (void)_beginDisallowRasterizationBlock;
- (void)_beginSuspendingMotionEffectsForStyleIfNeeded;
- (unsigned long long)_bestStaticWallpaperViewInitializationOptionsForVariant:(long long)arg1 shared:(_Bool)arg2 options:(unsigned long long)arg3;
- (id)_blurViewsForVariant:(long long)arg1;
- (void)_clearWallpaperEffectView:(id)arg1;
- (void)_clearWallpaperView:(id)arg1;
- (void)_createHomescreenLightForegroundBlurImageIfNecessary;
- (void)_endDisallowRasterizationBlock;
- (void)_endSuspendingMotionEffectsForStyleIfNeeded;
- (void)_forceUpdateToSpringBoardInterfaceOrientationWithAnimationDuration:(double)arg1;
- (id)_getImageInRect:(struct CGRect)arg1 withZoomFactor:(double)arg2 forVariant:(long long)arg3 style:(inout long long *)arg4;
- (void)_handleWallpaperChangedForVariant:(long long)arg1;
- (void)_handleWallpaperGeometryChangedForVariant:(long long)arg1;
- (void)_handleWallpaperLegibilitySettingsChanged:(id)arg1 forVariant:(long long)arg2;
- (_Bool)_isAcceptingOrientationChangesFromSource:(long long)arg1;
- (_Bool)_isRasterizationDisallowedForCurrentVariant;
- (_Bool)_isWallpaperHiddenForVariant:(long long)arg1;
- (_Bool)_isWallpaperView:(id)arg1 displayingWallpaperWithConfiguration:(id)arg2 forVariant:(long long)arg3;
- (id)_makeAndInsertWallpaperViewWithConfiguration:(id)arg1 forVariant:(long long)arg2 shared:(_Bool)arg3 options:(unsigned long long)arg4;
- (void)_motionEffectsChanged;
- (id)_newFakeBlurViewForVariant:(long long)arg1 style:(long long)arg2 transformOptions:(unsigned long long)arg3;
- (id)_newWallpaperEffectViewForVariant:(long long)arg1 transitionState:(CDStruct_059c2b36)arg2;
- (void)_noteSignificantTimeChanged:(id)arg1;
- (id)_observersForVariant:(long long)arg1;
- (void)_reconfigureBlurViewsForVariant:(long long)arg1;
- (void)_registerFakeBlurView:(id)arg1;
- (void)_reloadWallpaperAndFlushCaches:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)_saveWallpaperAggdKeysForLocations:(long long)arg1 withConfiguration:(id)arg2;
- (_Bool)_setDisallowRasterization:(_Bool)arg1 withReason:(id)arg2 reasons:(id)arg3;
- (void)_setWallpaperHidden:(_Bool)arg1 variant:(long long)arg2 reason:(id)arg3;
- (_Bool)_shouldSuspendMotionEffectsForState:(CDStruct_059c2b36)arg1;
- (_Bool)_shouldSuspendMotionEffectsForStyle:(long long)arg1;
- (id)_sourceForFakeBlurView:(id)arg1;
- (void)_suspendOrResumeColorSampling;
- (void)_suspendOrResumeWallpaperAnimation;
- (void)_unregisterFakeBlurView:(id)arg1;
- (void)_updateBlurGeneration;
- (void)_updateBlurImagesForVariant:(long long)arg1;
- (_Bool)_updateEffectViewForVariant:(long long)arg1 oldState:(CDStruct_059c2b36 *)arg2 newState:(CDStruct_059c2b36 *)arg3 oldEffectView:(id *)arg4 newEffectView:(id *)arg5;
- (_Bool)_updateEffectViewForVariant:(long long)arg1 withFactory:(id)arg2;
- (void)_updateMotionEffectsForState:(CDStruct_059c2b36)arg1;
- (void)_updateRasterizationState;
- (void)_updateScreenBlanked;
- (void)_updateSeparateWallpaperForVariants:(long long)arg1 options:(unsigned long long)arg2;
- (void)_updateSharedWallpaperWithOptions:(unsigned long long)arg1;
- (void)_updateWallpaperForLocations:(long long)arg1 options:(unsigned long long)arg2 withCompletion:(CDUnknownBlockType)arg3;
- (void)_updateWallpaperHidden;
- (void)_updateWallpaperParallax;
- (id)_wallpaperViewForVariant:(long long)arg1;
- (id)_window;
- (void)activeInterfaceOrientationDidChangeToOrientation:(long long)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(long long)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(long long)arg1;
@property(readonly, nonatomic) long long activeOrientationSource; // @synthesize activeOrientationSource=_activeOrientationSource;
- (void)addObserver:(id)arg1 forVariant:(long long)arg2;
- (id)averageColorForVariant:(long long)arg1;
- (id)averageColorInRect:(struct CGRect)arg1 forVariant:(long long)arg2;
- (id)averageColorInRect:(struct CGRect)arg1 forVariant:(long long)arg2 withSmudgeRadius:(double)arg3;
- (void)beginDelayingHomescreenStyleChangesForReason:(id)arg1;
- (void)beginRequiringWithReason:(id)arg1;
@property(readonly, copy, nonatomic) NSString *cachingIdentifier; // @synthesize cachingIdentifier=_cachingIdentifier;
- (void)cancelInProcessAnimations;
- (double)contrastForVariant:(long long)arg1;
- (double)contrastInRect:(struct CGRect)arg1 contrastWithinBoxes:(double *)arg2 contrastBetweenBoxes:(double *)arg3 forVariant:(long long)arg4;
- (double)contrastInRect:(struct CGRect)arg1 forVariant:(long long)arg2;
@property(readonly, nonatomic) CDStruct_059c2b36 currentHomescreenStyleTransitionState;
- (void)dealloc;
@property(readonly, copy) NSString *description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)endDelayingHomescreenStyleChangesForReason:(id)arg1 animationFactory:(id)arg2;
- (void)endRequiringWithReason:(id)arg1;
- (id)homescreenLightForegroundBlurImage;
- (struct CGRect)homescreenLightForegroundBlurImageContentsRectForWallpaperRelativeRect:(struct CGRect)arg1;
@property(readonly, nonatomic) SBWallpaperStyleInfo *homescreenStyleInfo; // @synthesize homescreenStyleInfo=_homescreenStyleInfo;
@property(nonatomic) double homescreenWallpaperScale; // @synthesize homescreenWallpaperScale=_homescreenWallpaperScale;
@property(retain, nonatomic) SBFWallpaperView *homescreenWallpaperView; // @synthesize homescreenWallpaperView=_homescreenWallpaperView;
- (id)init;
- (id)initWithScreen:(id)arg1 orientation:(long long)arg2 variant:(long long)arg3 wallpaperConfigurationManager:(id)arg4 cachingIdentifier:(id)arg5 rootSettings:(id)arg6;
- (id)initWithWallpaperConfigurationManager:(id)arg1;
- (id)initWithWallpaperConfigurationManager:(id)arg1 cachingIdentifier:(id)arg2 rootSettings:(id)arg3;
@property(readonly, nonatomic) id <SBFIrisWallpaperView> irisWallpaperView;
- (id)legibilitySettingsForVariant:(long long)arg1;
@property(readonly, nonatomic) SBWallpaperStyleInfo *lockscreenStyleInfo; // @synthesize lockscreenStyleInfo=_lockscreenStyleInfo;
@property(nonatomic) double lockscreenWallpaperScale; // @synthesize lockscreenWallpaperScale=_lockscreenWallpaperScale;
@property(retain, nonatomic) SBFWallpaperView *lockscreenWallpaperView; // @synthesize lockscreenWallpaperView=_lockscreenWallpaperView;
- (void)orientationSource:(long long)arg1 didRotateFromInterfaceOrientation:(long long)arg2;
- (void)orientationSource:(long long)arg1 willAnimateRotationToInterfaceOrientation:(long long)arg2 duration:(double)arg3;
- (void)orientationSource:(long long)arg1 willRotateToInterfaceOrientation:(long long)arg2 duration:(double)arg3;
- (void)providerLegibilitySettingsChanged:(id)arg1;
- (id)relinquishHostingOfWallpaperOverlay;
- (void)removeObserver:(id)arg1 forVariant:(long long)arg2;
- (_Bool)removeWallpaperStyleForPriority:(long long)arg1 forVariant:(long long)arg2 withAnimationFactory:(id)arg3;
- (void)resumeColorSamplingForReason:(id)arg1;
- (void)resumeWallpaperAnimationForReason:(id)arg1;
@property(retain, nonatomic) SBRootSettings *rootSettings; // @synthesize rootSettings=_rootSettings;
@property(readonly, nonatomic) UIScreen *screen; // @synthesize screen=_screen;
- (void)setActiveOrientationSource:(long long)arg1 andUpdateToOrientation:(long long)arg2 usingCrossfadeToBlack:(_Bool)arg3;
- (void)setAlpha:(double)arg1 forWallpaperVariant:(long long)arg2;
- (void)setDisallowsRasterization:(_Bool)arg1 forVariant:(long long)arg2 withReason:(id)arg3;
- (void)setHomescreenWallpaperScale:(double)arg1 withAnimationFactory:(id)arg2;
- (void)setLockscreenOnlyWallpaperAlpha:(double)arg1;
- (void)setLockscreenWallpaperContentsRect:(struct CGRect)arg1;
- (void)setLockscreenWallpaperScale:(double)arg1 withAnimationFactory:(id)arg2;
@property(retain, nonatomic) SBFWallpaperView *sharedWallpaperView; // @synthesize sharedWallpaperView=_sharedWallpaperView;
@property(nonatomic) long long variant;
- (void)setVariant:(long long)arg1 withOutAnimationFactory:(id)arg2 inAnimationFactory:(id)arg3 completion:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) SBWallpaperAggdLogger *wallpaperAggdLogger; // @synthesize wallpaperAggdLogger=_wallpaperAggdLogger;
- (_Bool)setWallpaperStyle:(long long)arg1 forPriority:(long long)arg2 forVariant:(long long)arg3 withAnimationFactory:(id)arg4;
- (_Bool)setWallpaperStyleTransitionState:(CDStruct_059c2b36)arg1 forPriority:(long long)arg2 forVariant:(long long)arg3 withAnimationFactory:(id)arg4;
@property(nonatomic) double windowLevel;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (_Bool)shouldDelayHomescreenStyleUpdates;
- (void)startHostingWallpaperOverlay:(id)arg1;
- (id)substitutionWallpaperConfigurationForWallpaperConfiguration:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (void)suspendColorSamplingForReason:(id)arg1;
- (void)suspendWallpaperAnimationForReason:(id)arg1;
- (void)updateIrisWallpaperForLockedState;
- (_Bool)updateIrisWallpaperForUnlockedState;
- (_Bool)variantsShareWallpaper;
- (id)vendWallpaperViewForConfiguration:(id)arg1 forVariant:(long long)arg2 shared:(_Bool)arg3 options:(unsigned long long)arg4;
- (id)wallpaperConfigurationForUpdatingWallpaperViewsForVariant:(long long)arg1;
- (id)wallpaperConfigurationForVariant:(long long)arg1 includingValuesForTypes:(unsigned long long)arg2;
@property(readonly, nonatomic) SBFWallpaperConfigurationManager *wallpaperConfigurationManager; // @synthesize wallpaperConfigurationManager=_wallpaperConfigurationManager;
- (void)wallpaperConfigurationManager:(id)arg1 didChangeWallpaperConfigurationForVariants:(long long)arg2;
- (unsigned long long)wallpaperDataTypesToRequestForUpdatingWallpaperViews;
- (id)wallpaperParallaxSettingsForVariant:(long long)arg1;
- (void)wallpaperServer:(id)arg1 fetchThumbnailDataForVariant:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) SBFWallpaperSettings *wallpaperSettings;
- (id)wallpaperStyleInfoForVariant:(long long)arg1;
- (void)wallpaperView:(id)arg1 didChangeZoomFactor:(double)arg2;
- (void)wallpaperViewDidChangeWantsRasterization:(id)arg1;
- (void)wallpaperViewDidInvalidateBlurs:(id)arg1;
- (void)wallpaperViewDidInvalidateGeometry:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

