//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SBIdleTimerCoordinating.h"
#import "SBIdleTimerProviding.h"

@class FBWorkspaceEventQueue, NSString, SBWorkspaceTransaction;

@interface SBWorkspace : NSObject <SBIdleTimerProviding, SBIdleTimerCoordinating>
{
    FBWorkspaceEventQueue *_eventQueue;
    SBWorkspaceTransaction *_currentTransaction;
}

+ (id)mainWorkspace;
- (void).cxx_destruct;
- (_Bool)_executeTransitionRequest:(id)arg1 options:(unsigned long long)arg2 validator:(CDUnknownBlockType)arg3;
- (id)coordinatorRequestedIdleTimerDescriptor:(id)arg1;
- (id)createRequestForApplicationActivation:(id)arg1 options:(unsigned long long)arg2;
- (id)createRequestWithOptions:(unsigned long long)arg1;
@property(readonly, nonatomic) SBWorkspaceTransaction *currentTransaction; // @synthesize currentTransaction=_currentTransaction;
@property(readonly, nonatomic) FBWorkspaceEventQueue *eventQueue; // @synthesize eventQueue=_eventQueue;
- (_Bool)executeTransitionRequest:(id)arg1;
- (_Bool)executeTransitionRequest:(id)arg1 withValidator:(CDUnknownBlockType)arg2;
- (id)idleTimerProvider:(id)arg1 didProposeDescriptor:(id)arg2 forReason:(id)arg3;
- (id)init;
- (id)initWithEventQueue:(id)arg1;
- (_Bool)requestTransitionWithBuilder:(CDUnknownBlockType)arg1;
- (_Bool)requestTransitionWithOptions:(unsigned long long)arg1 builder:(CDUnknownBlockType)arg2 validator:(CDUnknownBlockType)arg3;
- (id)transactionForTransitionRequest:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

