//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIStatusBar;

@interface SBZoomView : UIView
{
    UIStatusBar *_statusBar;
}

+ (id)_chromeStatusBarImageForInterfaceOrientation:(long long)arg1;
- (void).cxx_destruct;
- (id)_initWithFrame:(struct CGRect)arg1;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak UIStatusBar *statusBar; // @synthesize statusBar=_statusBar;

@end

