//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NSString;

@interface VolumeControl : NSObject
{
    _Bool _debounce;
    int _numberOfVolumeDecreasesSinceDownButtonDown;
    int _mode;
    NSMutableSet *_alwaysHiddenCategories;
    NSString *_lastDisplayedCategory;
    NSString *_lastEventCategory;
    _Bool _hudHandledLastVolumeChange;
    _Bool _euDevice;
    float _euVolumeLimit;
    _Bool _euVolumeLimitEnforced;
    _Bool _lastVolumeChangedWasBlocked;
    _Bool _volumeDownButtonIsDown;
    _Bool _volumeUpButtonIsDown;
}

+ (id)sharedVolumeControl;
- (void).cxx_destruct;
- (void)_EUVolumeEnforcementChanged:(id)arg1;
- (void)_EUVolumeLimitChanged:(id)arg1;
- (_Bool)_HUDIsDisplayableForCategory:(id)arg1;
- (float)_calcButtonRepeatDelay;
- (void)_changeVolumeBy:(float)arg1;
- (void)_effectiveVolumeChanged:(id)arg1;
- (void)_initializeEUVolumeLimits;
- (_Bool)_isCategoryAlwaysHidden:(id)arg1;
- (_Bool)_isMusicPlayingSomewhere;
- (_Bool)_isVolumeHUDVisible;
- (_Bool)_isVolumeHUDVisibleOrFading;
- (void)_presentVolumeHUDWithMode:(int)arg1 volume:(float)arg2;
- (void)_registerForAVSystemControllerNotifications;
- (void)_serverConnectionDied:(id)arg1;
- (_Bool)_turnOnScreenIfNecessaryForEULimit:(_Bool)arg1;
- (void)_unregisterForAVSystemControllerNotifications;
- (void)_userAcknowledgedEUEnforcement;
- (id)_volumeHUDViewWithMode:(int)arg1 volume:(float)arg2;
- (int)_volumeModeForCategory:(id)arg1;
- (void)addAlwaysHiddenCategory:(id)arg1;
- (void)cancelVolumeEvent;
- (void)clearAlwaysHiddenCategories;
- (void)dealloc;
- (void)decreaseVolume;
- (float)getMediaVolume;
- (void)handleVolumeButtonWithType:(long long)arg1 down:(_Bool)arg2;
- (_Bool)headphonesPresent;
- (void)hideVolumeHUDIfVisible;
- (void)increaseVolume;
- (id)init;
- (id)lastDisplayedCategory;
- (void)removeAlwaysHiddenCategory:(id)arg1;
- (void)sendEUVolumeLimitAcknowledgementIfNecessary;
- (void)setMediaVolume:(float)arg1;
- (void)toggleMute;
- (float)volume;
- (id)volumeHUDForCurrentCategory;
- (float)volumeStepDown;
- (float)volumeStepUp;

@end

